/*
 * generated by Xtext 2.43.0
 */
package dact.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExprDslRuntimeModule extends AbstractExprDslRuntimeModule {
}
