/**
 * generated by Xtext 2.43.0
 */
package dact.dsl.formatting2;

import com.google.inject.Inject;
import dact.BinaryExpression;
import dact.Expression;
import dact.NotExpression;
import dact.Operator;
import dact.dsl.services.ExprDslGrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;

@SuppressWarnings("all")
public class ExprDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private ExprDslGrammarAccess _exprDslGrammarAccess;

  protected void _format(final BinaryExpression binaryExpression, @Extension final IFormattableDocument document) {
    document.<Operator>format(binaryExpression.getOperator());
    document.<Expression>format(binaryExpression.getRightExpr());
    document.<Expression>format(binaryExpression.getLeftExpr());
  }

  protected void _format(final NotExpression notExpression, @Extension final IFormattableDocument document) {
    document.<Expression>format(notExpression.getExpr());
  }

  @XbaseGenerated
  public void format(final Object binaryExpression, final IFormattableDocument document) {
    if (binaryExpression instanceof BinaryExpression) {
      _format((BinaryExpression)binaryExpression, document);
      return;
    } else if (binaryExpression instanceof NotExpression) {
      _format((NotExpression)binaryExpression, document);
      return;
    } else if (binaryExpression instanceof XtextResource) {
      _format((XtextResource)binaryExpression, document);
      return;
    } else if (binaryExpression instanceof EObject) {
      _format((EObject)binaryExpression, document);
      return;
    } else if (binaryExpression == null) {
      _format((Void)null, document);
      return;
    } else if (binaryExpression != null) {
      _format(binaryExpression, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(binaryExpression, document).toString());
    }
  }
}
