/**
 *
 * $Id$
 */
package lemma.adapted.xcore.technology.validation;

import lemma.adapted.xcore.technology.OperationAspect;
import lemma.adapted.xcore.technology.OperationAspectPointcut;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.technology.OperationAspectPointcutSelector}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperationAspectPointcutSelectorValidator {
	boolean validate();

	boolean validatePointcuts(EList<OperationAspectPointcut> value);
	boolean validateOperationAspect(OperationAspect value);
	boolean validateSelectorString(String value);
}
