/**
 *
 * $Id$
 */
package lemma.adapted.xcore.technology.validation;

import lemma.adapted.xcore.data.Type;

import lemma.adapted.xcore.technology.CompatibilityMatrixEntry;
import lemma.adapted.xcore.technology.TechnologyImport;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.technology.PossiblyImportedTechnologySpecificType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PossiblyImportedTechnologySpecificTypeValidator {
	boolean validate();

	boolean validateImport(TechnologyImport value);
	boolean validateType(Type value);
	boolean validateMappingEntry(CompatibilityMatrixEntry value);
	boolean validateCompatibleEntry(CompatibilityMatrixEntry value);
}
