/**
 *
 * $Id$
 */
package lemma.adapted.xcore.technology.validation;

import lemma.adapted.xcore.technology.CommunicationType;
import lemma.adapted.xcore.technology.DataFormat;
import lemma.adapted.xcore.technology.Technology;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.technology.Protocol}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProtocolValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateCommunicationType(CommunicationType value);
	boolean validateDefault(boolean value);
	boolean validateDefaultFormat(DataFormat value);
	boolean validateDataFormats(EList<DataFormat> value);
	boolean validateTechnology(Technology value);
}
