/**
 *
 * $Id$
 */
package lemma.adapted.xcore.technology.validation;

import lemma.adapted.xcore.technology.CompatibilityMatrixEntry;
import lemma.adapted.xcore.technology.DeploymentTechnology;
import lemma.adapted.xcore.technology.InfrastructureTechnology;
import lemma.adapted.xcore.technology.OperationAspect;
import lemma.adapted.xcore.technology.Protocol;
import lemma.adapted.xcore.technology.ServiceAspect;
import lemma.adapted.xcore.technology.TechnologyImport;
import lemma.adapted.xcore.technology.TechnologySpecificCollectionType;
import lemma.adapted.xcore.technology.TechnologySpecificDataStructure;
import lemma.adapted.xcore.technology.TechnologySpecificPrimitiveType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.technology.Technology}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TechnologyValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateImports(EList<TechnologyImport> value);
	boolean validatePrimitiveTypes(EList<TechnologySpecificPrimitiveType> value);
	boolean validateCollectionTypes(EList<TechnologySpecificCollectionType> value);
	boolean validateDataStructures(EList<TechnologySpecificDataStructure> value);
	boolean validateCompatibilityEntries(EList<CompatibilityMatrixEntry> value);
	boolean validateProtocols(EList<Protocol> value);
	boolean validateServiceAspects(EList<ServiceAspect> value);
	boolean validateDeploymentTechnologies(EList<DeploymentTechnology> value);
	boolean validateInfrastructureTechnologies(EList<InfrastructureTechnology> value);
	boolean validateOperationAspects(EList<OperationAspect> value);
}
