#

pluginName = lemma.adapted.data.metamodel Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_DataModel_type = Model
_UI_ComplexTypeImport_type = Complex Type Import
_UI_Version_type = Version
_UI_Context_type = Context
_UI_Type_type = Type
_UI_PrimitiveType_type = Primitive Type
_UI_PrimitiveBoolean_type = Primitive Boolean
_UI_PrimitiveByte_type = Primitive Byte
_UI_PrimitiveCharacter_type = Primitive Character
_UI_PrimitiveDate_type = Primitive Date
_UI_PrimitiveDouble_type = Primitive Double
_UI_PrimitiveFloat_type = Primitive Float
_UI_PrimitiveInteger_type = Primitive Integer
_UI_PrimitiveLong_type = Primitive Long
_UI_PrimitiveShort_type = Primitive Short
_UI_PrimitiveString_type = Primitive String
_UI_PrimitiveUnspecified_type = Primitive Unspecified
_UI_ComplexType_type = Complex Type
_UI_ImportedComplexType_type = Imported Complex Type
_UI_DataStructure_type = Structure
_UI_DataOperation_type = Operation
_UI_DataOperationParameter_type = Operation Parameter
_UI_CollectionType_type = Collection Type
_UI_DataField_type = Field
_UI_Enumeration_type = Enumeration
_UI_EnumerationField_type = Enumeration Field
_UI_PrimitiveValue_type = Primitive Value
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_DataModel_t_modelUri_feature = Tmodel Uri
_UI_DataModel_complexTypeImports_feature = Complex Type Imports
_UI_DataModel_versions_feature = Versions
_UI_DataModel_contexts_feature = Contexts
_UI_DataModel_complexTypes_feature = Complex Types
_UI_ComplexTypeImport_name_feature = Name
_UI_ComplexTypeImport_importURI_feature = Import URI
_UI_ComplexTypeImport_dataModel_feature = Data Model
_UI_Version_name_feature = Name
_UI_Version_complexTypes_feature = Complex Types
_UI_Version_contexts_feature = Contexts
_UI_Version_dataModel_feature = Data Model
_UI_Context_name_feature = Name
_UI_Context_complexTypes_feature = Complex Types
_UI_Context_dataModel_feature = Data Model
_UI_Context_version_feature = Version
_UI_PrimitiveType_typeName_feature = Type Name
_UI_PrimitiveType_typeSize_feature = Type Size
_UI_ComplexType_name_feature = Name
_UI_ComplexType_features_feature = Features
_UI_ComplexType_dataModel_feature = Data Model
_UI_ComplexType_version_feature = Version
_UI_ComplexType_context_feature = Context
_UI_ComplexType_isStructure_feature = Is Structure
_UI_ComplexType_isPrimitiveCollection_feature = Is Primitive Collection
_UI_ComplexType_isStructuredCollection_feature = Is Structured Collection
_UI_ComplexType_isEnumeration_feature = Is Enumeration
_UI_ImportedComplexType_import_feature = Import
_UI_ImportedComplexType_importedType_feature = Imported Type
_UI_ImportedComplexType_dataField_feature = Data Field
_UI_ImportedComplexType_operation_feature = Operation
_UI_ImportedComplexType_parameter_feature = Parameter
_UI_DataStructure_super_feature = Super
_UI_DataStructure_dataFields_feature = Data Fields
_UI_DataStructure_operations_feature = Operations
_UI_DataOperation_name_feature = Name
_UI_DataOperation_hidden_feature = Hidden
_UI_DataOperation_hasNoReturnType_feature = Has No Return Type
_UI_DataOperation_features_feature = Features
_UI_DataOperation_complexReturnType_feature = Complex Return Type
_UI_DataOperation_importedComplexReturnType_feature = Imported Complex Return Type
_UI_DataOperation_primitiveReturnType_feature = Primitive Return Type
_UI_DataOperation_parameters_feature = Parameters
_UI_DataOperation_dataStructure_feature = Data Structure
_UI_DataOperation_lacksReturnTypeSpecification_feature = Lacks Return Type Specification
_UI_DataOperation_inherited_feature = Inherited
_UI_DataOperationParameter_name_feature = Name
_UI_DataOperationParameter_complexType_feature = Complex Type
_UI_DataOperationParameter_importedComplexType_feature = Imported Complex Type
_UI_DataOperationParameter_primitiveType_feature = Primitive Type
_UI_DataOperationParameter_operation_feature = Operation
_UI_CollectionType_primitiveType_feature = Primitive Type
_UI_CollectionType_dataFields_feature = Data Fields
_UI_DataField_name_feature = Name
_UI_DataField_hidden_feature = Hidden
_UI_DataField_immutable_feature = Immutable
_UI_DataField_complexType_feature = Complex Type
_UI_DataField_importedComplexType_feature = Imported Complex Type
_UI_DataField_primitiveType_feature = Primitive Type
_UI_DataField_initializationValue_feature = Initialization Value
_UI_DataField_features_feature = Features
_UI_DataField_dataStructure_feature = Data Structure
_UI_DataField_collectionType_feature = Collection Type
_UI_Enumeration_fields_feature = Fields
_UI_EnumerationField_name_feature = Name
_UI_EnumerationField_initializationValue_feature = Initialization Value
_UI_EnumerationField_enumeration_feature = Enumeration
_UI_PrimitiveValue_stringValue_feature = String Value
_UI_PrimitiveValue_booleanValue_feature = Boolean Value
_UI_PrimitiveValue_numericValue_feature = Numeric Value
_UI_Unknown_feature = Unspecified

_UI_PrimitiveTypeConstants_BOOLEAN_literal = boolean
_UI_PrimitiveTypeConstants_BYTE_literal = byte
_UI_PrimitiveTypeConstants_CHARACTER_literal = char
_UI_PrimitiveTypeConstants_DATE_literal = date
_UI_PrimitiveTypeConstants_DOUBLE_literal = double
_UI_PrimitiveTypeConstants_FLOAT_literal = float
_UI_PrimitiveTypeConstants_INTEGER_literal = int
_UI_PrimitiveTypeConstants_LONG_literal = long
_UI_PrimitiveTypeConstants_SHORT_literal = short
_UI_PrimitiveTypeConstants_STRING_literal = string
_UI_PrimitiveTypeConstants_UNSPECIFIED_literal = unspecified
_UI_ComplexTypeFeature_AGGREGATE_literal = AGGREGATE
_UI_ComplexTypeFeature_APPLICATION_SERVICE_literal = APPLICATION_SERVICE
_UI_ComplexTypeFeature_DOMAIN_EVENT_literal = DOMAIN_EVENT
_UI_ComplexTypeFeature_DOMAIN_SERVICE_literal = DOMAIN_SERVICE
_UI_ComplexTypeFeature_ENTITY_literal = ENTITY
_UI_ComplexTypeFeature_FACTORY_literal = FACTORY
_UI_ComplexTypeFeature_INFRASTRUCTURE_SERVICE_literal = INFRASTRUCTURE_SERVICE
_UI_ComplexTypeFeature_REPOSITORY_literal = REPOSITORY
_UI_ComplexTypeFeature_SERVICE_literal = SERVICE
_UI_ComplexTypeFeature_SPECIFICATION_literal = SPECIFICATION
_UI_ComplexTypeFeature_VALUE_OBJECT_literal = VALUE_OBJECT
_UI_ComplexTypeFeature_SHARED_VALUED_OBJECT_literal = SHARED_VALUED_OBJECT
_UI_DataOperationFeature_CLOSURE_literal = CLOSURE
_UI_DataOperationFeature_IDENTIFIER_literal = IDENTIFIER
_UI_DataOperationFeature_SIDE_EFFECT_FREE_literal = SIDE_EFFECT_FREE
_UI_DataOperationFeature_VALIDATOR_literal = VALIDATOR
_UI_DataFieldFeature_IDENTIFIER_literal = IDENTIFIER
_UI_DataFieldFeature_NEVER_EMPTY_literal = NEVER_EMPTY
_UI_DataFieldFeature_PART_literal = PART
_UI_EAttribute_type = EAttribute
_UI_EAnnotation_type = EAnnotation
_UI_EClass_type = EClass
_UI_EClassifier_type = EClassifier
_UI_EDataType_type = EData Type
_UI_EEnum_type = EEnum
_UI_EEnumLiteral_type = EEnum Literal
_UI_EFactory_type = EFactory
_UI_EModelElement_type = EModel Element
_UI_ENamedElement_type = ENamed Element
_UI_EObject_type = EObject
_UI_EOperation_type = EOperation
_UI_EPackage_type = EPackage
_UI_EParameter_type = EParameter
_UI_EReference_type = EReference
_UI_EStructuralFeature_type = EStructural Feature
_UI_ETypedElement_type = ETyped Element
_UI_EStringToStringMapEntry_type = EString To String Map Entry
_UI_EGenericType_type = EGeneric Type
_UI_ETypeParameter_type = EType Parameter
_UI_EAttribute_iD_feature = ID
_UI_EAttribute_iD_description = Whether the value of this attribute uniquely identifies an object within its containing resource
_UI_EAttribute_eAttributeType_feature = EAttribute Type
_UI_EAttribute_eAttributeType_description = The data type of this attribute
_UI_EAnnotation_source_feature = Source
_UI_EAnnotation_source_description = An identifier, typically an absolute URI, that uniquely identifies this kind of annotation
_UI_EAnnotation_details_feature = Details
_UI_EAnnotation_eModelElement_feature = EModel Element
_UI_EAnnotation_contents_feature = Contents
_UI_EAnnotation_references_feature = References
_UI_EAnnotation_references_description = Objects referenced by this annotation
_UI_EClass_abstract_feature = Abstract
_UI_EClass_abstract_description = Whether instances of this class can be created
_UI_EClass_interface_feature = Interface
_UI_EClass_interface_description = Whether no corresponding implementation will be generated for this class
_UI_EClass_eSuperTypes_feature = ESuper Types
_UI_EClass_eSuperTypes_description = The immediate super types of this class
_UI_EClass_eOperations_feature = EOperations
_UI_EClass_eOperations_description = The operations defined by this class
_UI_EClass_eAllAttributes_feature = EAll Attributes
_UI_EClass_eAllReferences_feature = EAll References
_UI_EClass_eReferences_feature = EReferences
_UI_EClass_eAttributes_feature = EAttributes
_UI_EClass_eAllContainments_feature = EAll Containments
_UI_EClass_eAllOperations_feature = EAll Operations
_UI_EClass_eAllStructuralFeatures_feature = EAll Structural Features
_UI_EClass_eAllSuperTypes_feature = EAll Super Types
_UI_EClass_eIDAttribute_feature = EID Attribute
_UI_EClass_eStructuralFeatures_feature = EStructural Features
_UI_EClass_eGenericSuperTypes_feature = EGeneric Super Types
_UI_EClass_eAllGenericSuperTypes_feature = EAll Generic Super Types
_UI_EClassifier_instanceClassName_feature = Instance Class Name
_UI_EClassifier_instanceClassName_description = The erased instance class name denoted by this classifier
_UI_EClassifier_instanceClass_feature = Instance Class
_UI_EClassifier_defaultValue_feature = Default Value
_UI_EClassifier_defaultValue_description = The default value for features of this type
_UI_EClassifier_instanceTypeName_feature = Instance Type Name
_UI_EClassifier_instanceTypeName_description = The full instance type name denoted by this classifier
_UI_EClassifier_ePackage_feature = EPackage
_UI_EClassifier_eTypeParameters_feature = EType Parameters
_UI_EDataType_serializable_feature = Serializable
_UI_EDataType_serializable_description = Whether a value of this data type can be serialized using the factory
_UI_EEnum_eLiterals_feature = ELiterals
_UI_EEnumLiteral_value_feature = Value
_UI_EEnumLiteral_value_description = The integer value associated with this enumerator
_UI_EEnumLiteral_instance_feature = Instance
_UI_EEnumLiteral_literal_feature = Literal
_UI_EEnumLiteral_literal_description = The literal value associated with this enumerator
_UI_EEnumLiteral_eEnum_feature = EEnum
_UI_EFactory_ePackage_feature = EPackage
_UI_EFactory_ePackage_description = The package corresponding to this factory
_UI_EModelElement_eAnnotations_feature = EAnnotations
_UI_ENamedElement_name_feature = Name
_UI_ENamedElement_name_description = The name of this model element
_UI_EOperation_eContainingClass_feature = EContaining Class
_UI_EOperation_eTypeParameters_feature = EType Parameters
_UI_EOperation_eParameters_feature = EParameters
_UI_EOperation_eExceptions_feature = EExceptions
_UI_EOperation_eExceptions_description = The exceptions thrown by this operation
_UI_EOperation_eGenericExceptions_feature = EGeneric Exceptions
_UI_EPackage_nsURI_feature = Ns URI
_UI_EPackage_nsURI_description = The universally unique namespace identifier, typically an absolute URI, for this package
_UI_EPackage_nsPrefix_feature = Ns Prefix
_UI_EPackage_nsPrefix_description = The namespace prefix used by default when serializing instances of the package's classes
_UI_EPackage_eFactoryInstance_feature = EFactory Instance
_UI_EPackage_eFactoryInstance_description = The factory corresponding to this package
_UI_EPackage_eClassifiers_feature = EClassifiers
_UI_EPackage_eSubpackages_feature = ESubpackages
_UI_EPackage_eSuperPackage_feature = ESuper Package
_UI_EParameter_eOperation_feature = EOperation
_UI_EReference_containment_feature = Containment
_UI_EReference_containment_description = Whether this reference represents a composite relationship
_UI_EReference_container_feature = Container
_UI_EReference_container_description = Whether this reference has as its opposite a containment reference
_UI_EReference_resolveProxies_feature = Resolve Proxies
_UI_EReference_resolveProxies_description = Whether this reference resolves proxies automatically
_UI_EReference_eOpposite_feature = EOpposite
_UI_EReference_eOpposite_description = The reference that represents the bidirectional opposite of this reference
_UI_EReference_eReferenceType_feature = EReference Type
_UI_EReference_eReferenceType_description = The target class of the reference
_UI_EReference_eKeys_feature = EKeys
_UI_EReference_eKeys_description = The attributes of the referenced class that uniquely identify a referenced instance
_UI_EStructuralFeature_changeable_feature = Changeable
_UI_EStructuralFeature_changeable_description = Whether the value of this feature can be changed
_UI_EStructuralFeature_volatile_feature = Volatile
_UI_EStructuralFeature_volatile_description = Whether no field will be generated for this feature
_UI_EStructuralFeature_transient_feature = Transient
_UI_EStructuralFeature_transient_description = Whether the value of this feature will be serialized
_UI_EStructuralFeature_defaultValueLiteral_feature = Default Value Literal
_UI_EStructuralFeature_defaultValueLiteral_description = The literal representation of the default value for this feature
_UI_EStructuralFeature_defaultValue_feature = Default Value
_UI_EStructuralFeature_defaultValue_description = The default value for this feature
_UI_EStructuralFeature_unsettable_feature = Unsettable
_UI_EStructuralFeature_unsettable_description = Whether the value space for this feature includes the state of not being set
_UI_EStructuralFeature_derived_feature = Derived
_UI_EStructuralFeature_derived_description = Whether the value of this feature is derived from the values of other features
_UI_EStructuralFeature_eContainingClass_feature = EContaining Class
_UI_EStructuralFeature_eContainingClass_description = The class that defines this feature
_UI_ETypedElement_ordered_feature = Ordered
_UI_ETypedElement_ordered_description = Whether the order in which values occur is meaningful
_UI_ETypedElement_unique_feature = Unique
_UI_ETypedElement_unique_description = Whether the same value may occur more than once
_UI_ETypedElement_lowerBound_feature = Lower Bound
_UI_ETypedElement_lowerBound_description = The minimum number of values that must occur
_UI_ETypedElement_upperBound_feature = Upper Bound
_UI_ETypedElement_upperBound_description = The maximum number of values that may occur; -1 represents unbounded and -2 represents unspecified
_UI_ETypedElement_many_feature = Many
_UI_ETypedElement_many_description = Whether more than one value may occur
_UI_ETypedElement_required_feature = Required
_UI_ETypedElement_required_description = Whether at least one value must occur
_UI_ETypedElement_eType_feature = EType
_UI_ETypedElement_eType_description = The type of this element
_UI_ETypedElement_eGenericType_feature = EGeneric Type
_UI_EStringToStringMapEntry_key_feature = Key
_UI_EStringToStringMapEntry_key_description = The key of this map entry
_UI_EStringToStringMapEntry_value_feature = Value
_UI_EStringToStringMapEntry_value_description = The value of this map entry
_UI_EGenericType_eUpperBound_feature = EUpper Bound
_UI_EGenericType_eTypeArguments_feature = EType Arguments
_UI_EGenericType_eRawType_feature = ERaw Type
_UI_EGenericType_eRawType_description = The erased type denoted by this generic type
_UI_EGenericType_eLowerBound_feature = ELower Bound
_UI_EGenericType_eTypeParameter_feature = EType Parameter
_UI_EGenericType_eTypeParameter_description = The type parameter denoted by this generic type
_UI_EGenericType_eClassifier_feature = EClassifier
_UI_EGenericType_eClassifier_description = The classifier denoted by this generic type
_UI_ETypeParameter_eBounds_feature = EBounds
_UI_ComplexTypeFeature_SHARED_VALUE_OBJECT_literal = SHARED_VALUE_OBJECT
_UI_CollectionType_lowerBound_feature = Lower Bound
_UI_CollectionType_upperBound_feature = Upper Bound
_UI_DataField_lowerBound_feature = Lower Bound
_UI_DataField_upperBound_feature = Upper Bound
_UI_DataOperationParameter_lowerBound_feature = Lower Bound
_UI_DataOperationParameter_upperBound_feature = Upper Bound
_UI_DataOperationParameterDirection_IN_literal = IN
_UI_DataOperationParameterDirection_RETURN_literal = RETURN
_UI_DataOperationParameter_direction_feature = Direction
_UI_DataOperationParameter_exchangePattern_feature = Exchange Pattern
_UI_ExchangePattern_IN_literal = IN
_UI_ExchangePattern_OUT_literal = OUT
_UI_DataOperationParameter_operationType_feature = Operation Type
_UI_OperationType_I0_INBOUND_GET_literal = I0_INBOUND_GET
_UI_OperationType_I1_INBOUND_PUT_literal = I1_INBOUND_PUT
_UI_OperationType_I2_INBOUND_POST_literal = I2_INBOUND_POST
_UI_OperationType_I3_INBOUND_DELETE_literal = I3_INBOUND_DELETE
_UI_OperationType_I4_MESSAGE_HANDLER_literal = I4_MESSAGE_HANDLER
_UI_OperationType_S0_DOMAIN_SERVICE_literal = S0_DOMAIN_SERVICE
_UI_OperationType_S1_APPLICATION_SERVICE_literal = S1_APPLICATION_SERVICE
_UI_OperationType_R0_REPOSITORY_CREATE_literal = R0_REPOSITORY_CREATE
_UI_OperationType_R1_REPOSITORY_READ_literal = R1_REPOSITORY_READ
_UI_OperationType_R2_UPDATE_CREATE_literal = R2_UPDATE_CREATE
_UI_OperationType_R3_DELETE_DELETE_literal = R3_DELETE_DELETE
_UI_OperationType_O0_OUTBOUND_GET_literal = O0_OUTBOUND_GET
_UI_OperationType_O1_OUTBOUND_PUT_literal = O1_OUTBOUND_PUT
_UI_OperationType_O2_OUTBOUND_POST_literal = O2_OUTBOUND_POST
_UI_OperationType_O3_OUTBOUND_DELETE_literal = O3_OUTBOUND_DELETE
_UI_OperationType_O4_MESSAGE_DISPATCHER_literal = O4_MESSAGE_DISPATCHER
_UI_OperationType_O5_OUTBOX_POLLER_literal = O5_OUTBOX_POLLER
_UI_OperationType_D0_CONSTRUCTOR_literal = D0_CONSTRUCTOR
_UI_OperationType_D1_SIMPLE_MUTATOR_literal = D1_SIMPLE_MUTATOR
_UI_OperationType_D2_COMPOUND_MUTATOR_literal = D2_COMPOUND_MUTATOR
_UI_OperationType_D3_SIMPLE_ACCESSOR_literal = D3_SIMPLE_ACCESSOR
_UI_OperationType_D4_COMPOUND_ACCESSOR_literal = D4_COMPOUND_ACCESSOR
_UI_OperationType_D5_SPECIFICATION_literal = D5_SPECIFICATION
_UI_OperationType_A0_INTERNAL_ACL_literal = A0_INTERNAL_ACL
_UI_OperationType_A1_EXTERNAL_ACL_literal = A1_EXTERNAL_ACL
_UI_DataOperation_operationType_feature = Operation Type
_UI_DataOperationParameter_initializationValue_feature = Initialization Value
_UI_PrimitiveValue_length_feature = Length
_UI_ValueSpecification_type = Value Specification
_UI_OperationType_R2_REPOSITORY_CREATE_literal = R2_REPOSITORY_CREATE
_UI_OperationType_R3_REPOSITORY_DELETE_literal = R3_REPOSITORY_DELETE
_UI_OperationType_R4_REPOSITORY_EXIST_literal = R4_REPOSITORY_EXIST
_UI_ComplexTypeFeature_PAYLOAD_literal = PAYLOAD
_UI_ComplexTypeFeature_EXCEPTION_literal = EXCEPTION
_UI_ComplexTypeFeature_OUTBOUND_PAYLOAD_literal = OUTBOUND_PAYLOAD
_UI_ComplexTypeFeature_INBOUND_PAYLOAD_literal = INBOUND_PAYLOAD
_UI_ComplexTypeFeature_REQUEST_PAYLOAD_literal = REQUEST_PAYLOAD
_UI_ComplexTypeFeature_RESPONSE_PAYLOAD_literal = RESPONSE_PAYLOAD
_UI_ComplexTypeFeature_NOTFOUND_EXCEPTION_literal = NOTFOUND_EXCEPTION
_UI_ComplexTypeFeature_RUNTIME_EXCEPTION_literal = RUNTIME_EXCEPTION
_UI_ComplexTypeFeature_EXTERNAL_literal = EXTERNAL
