/*
 * generated by Xtext 2.43.0
 */
grammar InternalExprDsl;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package dact.dsl.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package dact.dsl.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import dact.dsl.services.ExprDslGrammarAccess;

}
@parser::members {
	private ExprDslGrammarAccess grammarAccess;

	public void setGrammarAccess(ExprDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleExpression
entryRuleExpression
:
{ before(grammarAccess.getExpressionRule()); }
	 ruleExpression
{ after(grammarAccess.getExpressionRule()); } 
	 EOF 
;

// Rule Expression
ruleExpression 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getExpressionAccess().getAssignmentExpressionParserRuleCall()); }
		ruleAssignmentExpression
		{ after(grammarAccess.getExpressionAccess().getAssignmentExpressionParserRuleCall()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleAssignmentExpression
entryRuleAssignmentExpression
:
{ before(grammarAccess.getAssignmentExpressionRule()); }
	 ruleAssignmentExpression
{ after(grammarAccess.getAssignmentExpressionRule()); } 
	 EOF 
;

// Rule AssignmentExpression
ruleAssignmentExpression 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getAssignmentExpressionAccess().getAlternatives()); }
		(rule__AssignmentExpression__Alternatives)
		{ after(grammarAccess.getAssignmentExpressionAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleOrExpression
entryRuleOrExpression
:
{ before(grammarAccess.getOrExpressionRule()); }
	 ruleOrExpression
{ after(grammarAccess.getOrExpressionRule()); } 
	 EOF 
;

// Rule OrExpression
ruleOrExpression 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getOrExpressionAccess().getGroup()); }
		(rule__OrExpression__Group__0)
		{ after(grammarAccess.getOrExpressionAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleOrOperator
entryRuleOrOperator
:
{ before(grammarAccess.getOrOperatorRule()); }
	 ruleOrOperator
{ after(grammarAccess.getOrOperatorRule()); } 
	 EOF 
;

// Rule OrOperator
ruleOrOperator 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getOrOperatorAccess().getGroup()); }
		(rule__OrOperator__Group__0)
		{ after(grammarAccess.getOrOperatorAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleAndExpression
entryRuleAndExpression
:
{ before(grammarAccess.getAndExpressionRule()); }
	 ruleAndExpression
{ after(grammarAccess.getAndExpressionRule()); } 
	 EOF 
;

// Rule AndExpression
ruleAndExpression 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getAndExpressionAccess().getGroup()); }
		(rule__AndExpression__Group__0)
		{ after(grammarAccess.getAndExpressionAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleAndOperator
entryRuleAndOperator
:
{ before(grammarAccess.getAndOperatorRule()); }
	 ruleAndOperator
{ after(grammarAccess.getAndOperatorRule()); } 
	 EOF 
;

// Rule AndOperator
ruleAndOperator 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getAndOperatorAccess().getGroup()); }
		(rule__AndOperator__Group__0)
		{ after(grammarAccess.getAndOperatorAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleComparisonExpression
entryRuleComparisonExpression
:
{ before(grammarAccess.getComparisonExpressionRule()); }
	 ruleComparisonExpression
{ after(grammarAccess.getComparisonExpressionRule()); } 
	 EOF 
;

// Rule ComparisonExpression
ruleComparisonExpression 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getComparisonExpressionAccess().getGroup()); }
		(rule__ComparisonExpression__Group__0)
		{ after(grammarAccess.getComparisonExpressionAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleComparisonOperator
entryRuleComparisonOperator
:
{ before(grammarAccess.getComparisonOperatorRule()); }
	 ruleComparisonOperator
{ after(grammarAccess.getComparisonOperatorRule()); } 
	 EOF 
;

// Rule ComparisonOperator
ruleComparisonOperator 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getComparisonOperatorAccess().getAlternatives()); }
		(rule__ComparisonOperator__Alternatives)
		{ after(grammarAccess.getComparisonOperatorAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleAdditiveExpression
entryRuleAdditiveExpression
:
{ before(grammarAccess.getAdditiveExpressionRule()); }
	 ruleAdditiveExpression
{ after(grammarAccess.getAdditiveExpressionRule()); } 
	 EOF 
;

// Rule AdditiveExpression
ruleAdditiveExpression 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getAdditiveExpressionAccess().getGroup()); }
		(rule__AdditiveExpression__Group__0)
		{ after(grammarAccess.getAdditiveExpressionAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleAdditiveOperator
entryRuleAdditiveOperator
:
{ before(grammarAccess.getAdditiveOperatorRule()); }
	 ruleAdditiveOperator
{ after(grammarAccess.getAdditiveOperatorRule()); } 
	 EOF 
;

// Rule AdditiveOperator
ruleAdditiveOperator 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getAdditiveOperatorAccess().getAlternatives()); }
		(rule__AdditiveOperator__Alternatives)
		{ after(grammarAccess.getAdditiveOperatorAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleInExpression
entryRuleInExpression
:
{ before(grammarAccess.getInExpressionRule()); }
	 ruleInExpression
{ after(grammarAccess.getInExpressionRule()); } 
	 EOF 
;

// Rule InExpression
ruleInExpression 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getInExpressionAccess().getGroup()); }
		(rule__InExpression__Group__0)
		{ after(grammarAccess.getInExpressionAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleInOperator
entryRuleInOperator
:
{ before(grammarAccess.getInOperatorRule()); }
	 ruleInOperator
{ after(grammarAccess.getInOperatorRule()); } 
	 EOF 
;

// Rule InOperator
ruleInOperator 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getInOperatorAccess().getGroup()); }
		(rule__InOperator__Group__0)
		{ after(grammarAccess.getInOperatorAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleMultiplicativeExpression
entryRuleMultiplicativeExpression
:
{ before(grammarAccess.getMultiplicativeExpressionRule()); }
	 ruleMultiplicativeExpression
{ after(grammarAccess.getMultiplicativeExpressionRule()); } 
	 EOF 
;

// Rule MultiplicativeExpression
ruleMultiplicativeExpression 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getMultiplicativeExpressionAccess().getGroup()); }
		(rule__MultiplicativeExpression__Group__0)
		{ after(grammarAccess.getMultiplicativeExpressionAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleMultiplicativeOperator
entryRuleMultiplicativeOperator
:
{ before(grammarAccess.getMultiplicativeOperatorRule()); }
	 ruleMultiplicativeOperator
{ after(grammarAccess.getMultiplicativeOperatorRule()); } 
	 EOF 
;

// Rule MultiplicativeOperator
ruleMultiplicativeOperator 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getMultiplicativeOperatorAccess().getAlternatives()); }
		(rule__MultiplicativeOperator__Alternatives)
		{ after(grammarAccess.getMultiplicativeOperatorAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleUnaryExpression
entryRuleUnaryExpression
:
{ before(grammarAccess.getUnaryExpressionRule()); }
	 ruleUnaryExpression
{ after(grammarAccess.getUnaryExpressionRule()); } 
	 EOF 
;

// Rule UnaryExpression
ruleUnaryExpression 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getUnaryExpressionAccess().getAlternatives()); }
		(rule__UnaryExpression__Alternatives)
		{ after(grammarAccess.getUnaryExpressionAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRulePrimaryExpression
entryRulePrimaryExpression
:
{ before(grammarAccess.getPrimaryExpressionRule()); }
	 rulePrimaryExpression
{ after(grammarAccess.getPrimaryExpressionRule()); } 
	 EOF 
;

// Rule PrimaryExpression
rulePrimaryExpression 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getPrimaryExpressionAccess().getAlternatives()); }
		(rule__PrimaryExpression__Alternatives)
		{ after(grammarAccess.getPrimaryExpressionAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleLiteralReal
entryRuleLiteralReal
:
{ before(grammarAccess.getLiteralRealRule()); }
	 ruleLiteralReal
{ after(grammarAccess.getLiteralRealRule()); } 
	 EOF 
;

// Rule LiteralReal
ruleLiteralReal 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getLiteralRealAccess().getValueAssignment()); }
		(rule__LiteralReal__ValueAssignment)
		{ after(grammarAccess.getLiteralRealAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleRealSpecification
entryRuleRealSpecification
:
{ before(grammarAccess.getRealSpecificationRule()); }
	 ruleRealSpecification
{ after(grammarAccess.getRealSpecificationRule()); } 
	 EOF 
;

// Rule RealSpecification
ruleRealSpecification 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getRealSpecificationAccess().getValueAssignment()); }
		(rule__RealSpecification__ValueAssignment)
		{ after(grammarAccess.getRealSpecificationAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEDoubleObject
entryRuleEDoubleObject
:
{ before(grammarAccess.getEDoubleObjectRule()); }
	 ruleEDoubleObject
{ after(grammarAccess.getEDoubleObjectRule()); } 
	 EOF 
;

// Rule EDoubleObject
ruleEDoubleObject 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEDoubleObjectAccess().getGroup()); }
		(rule__EDoubleObject__Group__0)
		{ after(grammarAccess.getEDoubleObjectAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleLiteralInteger
entryRuleLiteralInteger
:
{ before(grammarAccess.getLiteralIntegerRule()); }
	 ruleLiteralInteger
{ after(grammarAccess.getLiteralIntegerRule()); } 
	 EOF 
;

// Rule LiteralInteger
ruleLiteralInteger 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getLiteralIntegerAccess().getValueAssignment()); }
		(rule__LiteralInteger__ValueAssignment)
		{ after(grammarAccess.getLiteralIntegerAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleIntegerSpecification
entryRuleIntegerSpecification
:
{ before(grammarAccess.getIntegerSpecificationRule()); }
	 ruleIntegerSpecification
{ after(grammarAccess.getIntegerSpecificationRule()); } 
	 EOF 
;

// Rule IntegerSpecification
ruleIntegerSpecification 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getIntegerSpecificationAccess().getValueAssignment()); }
		(rule__IntegerSpecification__ValueAssignment)
		{ after(grammarAccess.getIntegerSpecificationAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEIntegerObject
entryRuleEIntegerObject
:
{ before(grammarAccess.getEIntegerObjectRule()); }
	 ruleEIntegerObject
{ after(grammarAccess.getEIntegerObjectRule()); } 
	 EOF 
;

// Rule EIntegerObject
ruleEIntegerObject 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEIntegerObjectAccess().getGroup()); }
		(rule__EIntegerObject__Group__0)
		{ after(grammarAccess.getEIntegerObjectAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleLiteralString
entryRuleLiteralString
:
{ before(grammarAccess.getLiteralStringRule()); }
	 ruleLiteralString
{ after(grammarAccess.getLiteralStringRule()); } 
	 EOF 
;

// Rule LiteralString
ruleLiteralString 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getLiteralStringAccess().getValueAssignment()); }
		(rule__LiteralString__ValueAssignment)
		{ after(grammarAccess.getLiteralStringAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleStringSpecification
entryRuleStringSpecification
:
{ before(grammarAccess.getStringSpecificationRule()); }
	 ruleStringSpecification
{ after(grammarAccess.getStringSpecificationRule()); } 
	 EOF 
;

// Rule StringSpecification
ruleStringSpecification 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getStringSpecificationAccess().getValueAssignment()); }
		(rule__StringSpecification__ValueAssignment)
		{ after(grammarAccess.getStringSpecificationAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleLiteralBoolean
entryRuleLiteralBoolean
:
{ before(grammarAccess.getLiteralBooleanRule()); }
	 ruleLiteralBoolean
{ after(grammarAccess.getLiteralBooleanRule()); } 
	 EOF 
;

// Rule LiteralBoolean
ruleLiteralBoolean 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getLiteralBooleanAccess().getValueAssignment()); }
		(rule__LiteralBoolean__ValueAssignment)
		{ after(grammarAccess.getLiteralBooleanAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleBooleanSpecification
entryRuleBooleanSpecification
:
{ before(grammarAccess.getBooleanSpecificationRule()); }
	 ruleBooleanSpecification
{ after(grammarAccess.getBooleanSpecificationRule()); } 
	 EOF 
;

// Rule BooleanSpecification
ruleBooleanSpecification 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getBooleanSpecificationAccess().getGroup()); }
		(rule__BooleanSpecification__Group__0)
		{ after(grammarAccess.getBooleanSpecificationAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleLiteralNull
entryRuleLiteralNull
:
{ before(grammarAccess.getLiteralNullRule()); }
	 ruleLiteralNull
{ after(grammarAccess.getLiteralNullRule()); } 
	 EOF 
;

// Rule LiteralNull
ruleLiteralNull 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getLiteralNullAccess().getValueAssignment()); }
		(rule__LiteralNull__ValueAssignment)
		{ after(grammarAccess.getLiteralNullAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleNullSpecification
entryRuleNullSpecification
:
{ before(grammarAccess.getNullSpecificationRule()); }
	 ruleNullSpecification
{ after(grammarAccess.getNullSpecificationRule()); } 
	 EOF 
;

// Rule NullSpecification
ruleNullSpecification 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getNullSpecificationAccess().getGroup()); }
		(rule__NullSpecification__Group__0)
		{ after(grammarAccess.getNullSpecificationAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRulePropertyAccess
entryRulePropertyAccess
:
{ before(grammarAccess.getPropertyAccessRule()); }
	 rulePropertyAccess
{ after(grammarAccess.getPropertyAccessRule()); } 
	 EOF 
;

// Rule PropertyAccess
rulePropertyAccess 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getPropertyAccessAccess().getGroup()); }
		(rule__PropertyAccess__Group__0)
		{ after(grammarAccess.getPropertyAccessAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleIdentifier
entryRuleIdentifier
:
{ before(grammarAccess.getIdentifierRule()); }
	 ruleIdentifier
{ after(grammarAccess.getIdentifierRule()); } 
	 EOF 
;

// Rule Identifier
ruleIdentifier 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getIdentifierAccess().getGroup()); }
		(rule__Identifier__Group__0)
		{ after(grammarAccess.getIdentifierAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleSignedInt
entryRuleSignedInt
:
{ before(grammarAccess.getSignedIntRule()); }
	 ruleSignedInt
{ after(grammarAccess.getSignedIntRule()); } 
	 EOF 
;

// Rule SignedInt
ruleSignedInt 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getSignedIntAccess().getGroup()); }
		(rule__SignedInt__Group__0)
		{ after(grammarAccess.getSignedIntAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleQualifiedName
entryRuleQualifiedName
:
{ before(grammarAccess.getQualifiedNameRule()); }
	 ruleQualifiedName
{ after(grammarAccess.getQualifiedNameRule()); } 
	 EOF 
;

// Rule QualifiedName
ruleQualifiedName 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getQualifiedNameAccess().getGroup()); }
		(rule__QualifiedName__Group__0)
		{ after(grammarAccess.getQualifiedNameAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleLiteralEnum
entryRuleLiteralEnum
:
{ before(grammarAccess.getLiteralEnumRule()); }
	 ruleLiteralEnum
{ after(grammarAccess.getLiteralEnumRule()); } 
	 EOF 
;

// Rule LiteralEnum
ruleLiteralEnum 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getLiteralEnumAccess().getValueAssignment()); }
		(rule__LiteralEnum__ValueAssignment)
		{ after(grammarAccess.getLiteralEnumAccess().getValueAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEnumSpecification
entryRuleEnumSpecification
:
{ before(grammarAccess.getEnumSpecificationRule()); }
	 ruleEnumSpecification
{ after(grammarAccess.getEnumSpecificationRule()); } 
	 EOF 
;

// Rule EnumSpecification
ruleEnumSpecification 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEnumSpecificationAccess().getNameAssignment()); }
		(rule__EnumSpecification__NameAssignment)
		{ after(grammarAccess.getEnumSpecificationAccess().getNameAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleEnumQualifiedName
entryRuleEnumQualifiedName
:
{ before(grammarAccess.getEnumQualifiedNameRule()); }
	 ruleEnumQualifiedName
{ after(grammarAccess.getEnumQualifiedNameRule()); } 
	 EOF 
;

// Rule EnumQualifiedName
ruleEnumQualifiedName 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getEnumQualifiedNameAccess().getGroup()); }
		(rule__EnumQualifiedName__Group__0)
		{ after(grammarAccess.getEnumQualifiedNameAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AssignmentExpression__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAssignmentExpressionAccess().getGroup_0()); }
		(rule__AssignmentExpression__Group_0__0)
		{ after(grammarAccess.getAssignmentExpressionAccess().getGroup_0()); }
	)
	|
	(
		{ before(grammarAccess.getAssignmentExpressionAccess().getOrExpressionParserRuleCall_1()); }
		ruleOrExpression
		{ after(grammarAccess.getAssignmentExpressionAccess().getOrExpressionParserRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__OrOperator__Alternatives_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getOrOperatorAccess().getVerticalLineVerticalLineKeyword_1_0()); }
		'||'
		{ after(grammarAccess.getOrOperatorAccess().getVerticalLineVerticalLineKeyword_1_0()); }
	)
	|
	(
		{ before(grammarAccess.getOrOperatorAccess().getORKeyword_1_1()); }
		'OR'
		{ after(grammarAccess.getOrOperatorAccess().getORKeyword_1_1()); }
	)
	|
	(
		{ before(grammarAccess.getOrOperatorAccess().getOrKeyword_1_2()); }
		'or'
		{ after(grammarAccess.getOrOperatorAccess().getOrKeyword_1_2()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AndOperator__Alternatives_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAndOperatorAccess().getAmpersandAmpersandKeyword_1_0()); }
		'&&'
		{ after(grammarAccess.getAndOperatorAccess().getAmpersandAmpersandKeyword_1_0()); }
	)
	|
	(
		{ before(grammarAccess.getAndOperatorAccess().getANDKeyword_1_1()); }
		'AND'
		{ after(grammarAccess.getAndOperatorAccess().getANDKeyword_1_1()); }
	)
	|
	(
		{ before(grammarAccess.getAndOperatorAccess().getAndKeyword_1_2()); }
		'and'
		{ after(grammarAccess.getAndOperatorAccess().getAndKeyword_1_2()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getComparisonOperatorAccess().getGroup_0()); }
		(rule__ComparisonOperator__Group_0__0)
		{ after(grammarAccess.getComparisonOperatorAccess().getGroup_0()); }
	)
	|
	(
		{ before(grammarAccess.getComparisonOperatorAccess().getGroup_1()); }
		(rule__ComparisonOperator__Group_1__0)
		{ after(grammarAccess.getComparisonOperatorAccess().getGroup_1()); }
	)
	|
	(
		{ before(grammarAccess.getComparisonOperatorAccess().getGroup_2()); }
		(rule__ComparisonOperator__Group_2__0)
		{ after(grammarAccess.getComparisonOperatorAccess().getGroup_2()); }
	)
	|
	(
		{ before(grammarAccess.getComparisonOperatorAccess().getGroup_3()); }
		(rule__ComparisonOperator__Group_3__0)
		{ after(grammarAccess.getComparisonOperatorAccess().getGroup_3()); }
	)
	|
	(
		{ before(grammarAccess.getComparisonOperatorAccess().getGroup_4()); }
		(rule__ComparisonOperator__Group_4__0)
		{ after(grammarAccess.getComparisonOperatorAccess().getGroup_4()); }
	)
	|
	(
		{ before(grammarAccess.getComparisonOperatorAccess().getGroup_5()); }
		(rule__ComparisonOperator__Group_5__0)
		{ after(grammarAccess.getComparisonOperatorAccess().getGroup_5()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveOperator__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAdditiveOperatorAccess().getGroup_0()); }
		(rule__AdditiveOperator__Group_0__0)
		{ after(grammarAccess.getAdditiveOperatorAccess().getGroup_0()); }
	)
	|
	(
		{ before(grammarAccess.getAdditiveOperatorAccess().getGroup_1()); }
		(rule__AdditiveOperator__Group_1__0)
		{ after(grammarAccess.getAdditiveOperatorAccess().getGroup_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__InOperator__Alternatives_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInOperatorAccess().getINKeyword_1_0()); }
		'IN'
		{ after(grammarAccess.getInOperatorAccess().getINKeyword_1_0()); }
	)
	|
	(
		{ before(grammarAccess.getInOperatorAccess().getInKeyword_1_1()); }
		'in'
		{ after(grammarAccess.getInOperatorAccess().getInKeyword_1_1()); }
	)
	|
	(
		{ before(grammarAccess.getInOperatorAccess().getInKeyword_1_2()); }
		'In'
		{ after(grammarAccess.getInOperatorAccess().getInKeyword_1_2()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeOperator__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMultiplicativeOperatorAccess().getGroup_0()); }
		(rule__MultiplicativeOperator__Group_0__0)
		{ after(grammarAccess.getMultiplicativeOperatorAccess().getGroup_0()); }
	)
	|
	(
		{ before(grammarAccess.getMultiplicativeOperatorAccess().getGroup_1()); }
		(rule__MultiplicativeOperator__Group_1__0)
		{ after(grammarAccess.getMultiplicativeOperatorAccess().getGroup_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__UnaryExpression__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getUnaryExpressionAccess().getGroup_0()); }
		(rule__UnaryExpression__Group_0__0)
		{ after(grammarAccess.getUnaryExpressionAccess().getGroup_0()); }
	)
	|
	(
		{ before(grammarAccess.getUnaryExpressionAccess().getPrimaryExpressionParserRuleCall_1()); }
		rulePrimaryExpression
		{ after(grammarAccess.getUnaryExpressionAccess().getPrimaryExpressionParserRuleCall_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__UnaryExpression__Alternatives_0_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getUnaryExpressionAccess().getExclamationMarkKeyword_0_1_0()); }
		'!'
		{ after(grammarAccess.getUnaryExpressionAccess().getExclamationMarkKeyword_0_1_0()); }
	)
	|
	(
		{ before(grammarAccess.getUnaryExpressionAccess().getNOTKeyword_0_1_1()); }
		'NOT'
		{ after(grammarAccess.getUnaryExpressionAccess().getNOTKeyword_0_1_1()); }
	)
	|
	(
		{ before(grammarAccess.getUnaryExpressionAccess().getNotKeyword_0_1_2()); }
		'not'
		{ after(grammarAccess.getUnaryExpressionAccess().getNotKeyword_0_1_2()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__PrimaryExpression__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getPrimaryExpressionAccess().getLiteralRealParserRuleCall_0()); }
		ruleLiteralReal
		{ after(grammarAccess.getPrimaryExpressionAccess().getLiteralRealParserRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getPrimaryExpressionAccess().getLiteralIntegerParserRuleCall_1()); }
		ruleLiteralInteger
		{ after(grammarAccess.getPrimaryExpressionAccess().getLiteralIntegerParserRuleCall_1()); }
	)
	|
	(
		{ before(grammarAccess.getPrimaryExpressionAccess().getLiteralStringParserRuleCall_2()); }
		ruleLiteralString
		{ after(grammarAccess.getPrimaryExpressionAccess().getLiteralStringParserRuleCall_2()); }
	)
	|
	(
		{ before(grammarAccess.getPrimaryExpressionAccess().getLiteralBooleanParserRuleCall_3()); }
		ruleLiteralBoolean
		{ after(grammarAccess.getPrimaryExpressionAccess().getLiteralBooleanParserRuleCall_3()); }
	)
	|
	(
		{ before(grammarAccess.getPrimaryExpressionAccess().getLiteralNullParserRuleCall_4()); }
		ruleLiteralNull
		{ after(grammarAccess.getPrimaryExpressionAccess().getLiteralNullParserRuleCall_4()); }
	)
	|
	(
		{ before(grammarAccess.getPrimaryExpressionAccess().getLiteralEnumParserRuleCall_5()); }
		ruleLiteralEnum
		{ after(grammarAccess.getPrimaryExpressionAccess().getLiteralEnumParserRuleCall_5()); }
	)
	|
	(
		{ before(grammarAccess.getPrimaryExpressionAccess().getPropertyAccessParserRuleCall_6()); }
		rulePropertyAccess
		{ after(grammarAccess.getPrimaryExpressionAccess().getPropertyAccessParserRuleCall_6()); }
	)
	|
	(
		{ before(grammarAccess.getPrimaryExpressionAccess().getGroup_7()); }
		(rule__PrimaryExpression__Group_7__0)
		{ after(grammarAccess.getPrimaryExpressionAccess().getGroup_7()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__BooleanSpecification__Alternatives_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBooleanSpecificationAccess().getValueAssignment_1_0()); }
		(rule__BooleanSpecification__ValueAssignment_1_0)
		{ after(grammarAccess.getBooleanSpecificationAccess().getValueAssignment_1_0()); }
	)
	|
	(
		{ before(grammarAccess.getBooleanSpecificationAccess().getFalseKeyword_1_1()); }
		'false'
		{ after(grammarAccess.getBooleanSpecificationAccess().getFalseKeyword_1_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__NullSpecification__Alternatives_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getNullSpecificationAccess().getNullKeyword_1_0()); }
		'null'
		{ after(grammarAccess.getNullSpecificationAccess().getNullKeyword_1_0()); }
	)
	|
	(
		{ before(grammarAccess.getNullSpecificationAccess().getNULLKeyword_1_1()); }
		'NULL'
		{ after(grammarAccess.getNullSpecificationAccess().getNULLKeyword_1_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AssignmentExpression__Group_0__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AssignmentExpression__Group_0__0__Impl
	rule__AssignmentExpression__Group_0__1
;
finally {
	restoreStackSize(stackSize);
}

rule__AssignmentExpression__Group_0__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAssignmentExpressionAccess().getVariableAssignmentAction_0_0()); }
	()
	{ after(grammarAccess.getAssignmentExpressionAccess().getVariableAssignmentAction_0_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AssignmentExpression__Group_0__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AssignmentExpression__Group_0__1__Impl
	rule__AssignmentExpression__Group_0__2
;
finally {
	restoreStackSize(stackSize);
}

rule__AssignmentExpression__Group_0__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAssignmentExpressionAccess().getIdentifierAssignment_0_1()); }
	(rule__AssignmentExpression__IdentifierAssignment_0_1)
	{ after(grammarAccess.getAssignmentExpressionAccess().getIdentifierAssignment_0_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AssignmentExpression__Group_0__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AssignmentExpression__Group_0__2__Impl
	rule__AssignmentExpression__Group_0__3
;
finally {
	restoreStackSize(stackSize);
}

rule__AssignmentExpression__Group_0__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAssignmentExpressionAccess().getEqualsSignKeyword_0_2()); }
	'='
	{ after(grammarAccess.getAssignmentExpressionAccess().getEqualsSignKeyword_0_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AssignmentExpression__Group_0__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AssignmentExpression__Group_0__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__AssignmentExpression__Group_0__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAssignmentExpressionAccess().getExprAssignment_0_3()); }
	(rule__AssignmentExpression__ExprAssignment_0_3)
	{ after(grammarAccess.getAssignmentExpressionAccess().getExprAssignment_0_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__OrExpression__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__OrExpression__Group__0__Impl
	rule__OrExpression__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__OrExpression__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOrExpressionAccess().getAndExpressionParserRuleCall_0()); }
	ruleAndExpression
	{ after(grammarAccess.getOrExpressionAccess().getAndExpressionParserRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__OrExpression__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__OrExpression__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__OrExpression__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOrExpressionAccess().getGroup_1()); }
	(rule__OrExpression__Group_1__0)*
	{ after(grammarAccess.getOrExpressionAccess().getGroup_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__OrExpression__Group_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__OrExpression__Group_1__0__Impl
	rule__OrExpression__Group_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__OrExpression__Group_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOrExpressionAccess().getBinaryExpressionLeftExprAction_1_0()); }
	()
	{ after(grammarAccess.getOrExpressionAccess().getBinaryExpressionLeftExprAction_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__OrExpression__Group_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__OrExpression__Group_1__1__Impl
	rule__OrExpression__Group_1__2
;
finally {
	restoreStackSize(stackSize);
}

rule__OrExpression__Group_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOrExpressionAccess().getOperatorAssignment_1_1()); }
	(rule__OrExpression__OperatorAssignment_1_1)
	{ after(grammarAccess.getOrExpressionAccess().getOperatorAssignment_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__OrExpression__Group_1__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__OrExpression__Group_1__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__OrExpression__Group_1__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOrExpressionAccess().getRightExprAssignment_1_2()); }
	(rule__OrExpression__RightExprAssignment_1_2)
	{ after(grammarAccess.getOrExpressionAccess().getRightExprAssignment_1_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__OrOperator__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__OrOperator__Group__0__Impl
	rule__OrOperator__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__OrOperator__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOrOperatorAccess().getOrAction_0()); }
	()
	{ after(grammarAccess.getOrOperatorAccess().getOrAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__OrOperator__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__OrOperator__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__OrOperator__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getOrOperatorAccess().getAlternatives_1()); }
	(rule__OrOperator__Alternatives_1)
	{ after(grammarAccess.getOrOperatorAccess().getAlternatives_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__AndExpression__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AndExpression__Group__0__Impl
	rule__AndExpression__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__AndExpression__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAndExpressionAccess().getComparisonExpressionParserRuleCall_0()); }
	ruleComparisonExpression
	{ after(grammarAccess.getAndExpressionAccess().getComparisonExpressionParserRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AndExpression__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AndExpression__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__AndExpression__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAndExpressionAccess().getGroup_1()); }
	(rule__AndExpression__Group_1__0)*
	{ after(grammarAccess.getAndExpressionAccess().getGroup_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__AndExpression__Group_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AndExpression__Group_1__0__Impl
	rule__AndExpression__Group_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__AndExpression__Group_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAndExpressionAccess().getBinaryExpressionLeftExprAction_1_0()); }
	()
	{ after(grammarAccess.getAndExpressionAccess().getBinaryExpressionLeftExprAction_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AndExpression__Group_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AndExpression__Group_1__1__Impl
	rule__AndExpression__Group_1__2
;
finally {
	restoreStackSize(stackSize);
}

rule__AndExpression__Group_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAndExpressionAccess().getOperatorAssignment_1_1()); }
	(rule__AndExpression__OperatorAssignment_1_1)
	{ after(grammarAccess.getAndExpressionAccess().getOperatorAssignment_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AndExpression__Group_1__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AndExpression__Group_1__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__AndExpression__Group_1__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAndExpressionAccess().getRightExprAssignment_1_2()); }
	(rule__AndExpression__RightExprAssignment_1_2)
	{ after(grammarAccess.getAndExpressionAccess().getRightExprAssignment_1_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__AndOperator__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AndOperator__Group__0__Impl
	rule__AndOperator__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__AndOperator__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAndOperatorAccess().getAndAction_0()); }
	()
	{ after(grammarAccess.getAndOperatorAccess().getAndAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AndOperator__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AndOperator__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__AndOperator__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAndOperatorAccess().getAlternatives_1()); }
	(rule__AndOperator__Alternatives_1)
	{ after(grammarAccess.getAndOperatorAccess().getAlternatives_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__ComparisonExpression__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonExpression__Group__0__Impl
	rule__ComparisonExpression__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonExpression__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonExpressionAccess().getAdditiveExpressionParserRuleCall_0()); }
	ruleAdditiveExpression
	{ after(grammarAccess.getComparisonExpressionAccess().getAdditiveExpressionParserRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonExpression__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonExpression__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonExpression__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonExpressionAccess().getGroup_1()); }
	(rule__ComparisonExpression__Group_1__0)*
	{ after(grammarAccess.getComparisonExpressionAccess().getGroup_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__ComparisonExpression__Group_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonExpression__Group_1__0__Impl
	rule__ComparisonExpression__Group_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonExpression__Group_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonExpressionAccess().getBinaryExpressionLeftExprAction_1_0()); }
	()
	{ after(grammarAccess.getComparisonExpressionAccess().getBinaryExpressionLeftExprAction_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonExpression__Group_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonExpression__Group_1__1__Impl
	rule__ComparisonExpression__Group_1__2
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonExpression__Group_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonExpressionAccess().getOperatorAssignment_1_1()); }
	(rule__ComparisonExpression__OperatorAssignment_1_1)
	{ after(grammarAccess.getComparisonExpressionAccess().getOperatorAssignment_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonExpression__Group_1__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonExpression__Group_1__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonExpression__Group_1__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonExpressionAccess().getRightExprAssignment_1_2()); }
	(rule__ComparisonExpression__RightExprAssignment_1_2)
	{ after(grammarAccess.getComparisonExpressionAccess().getRightExprAssignment_1_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__ComparisonOperator__Group_0__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonOperator__Group_0__0__Impl
	rule__ComparisonOperator__Group_0__1
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_0__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonOperatorAccess().getGtAction_0_0()); }
	()
	{ after(grammarAccess.getComparisonOperatorAccess().getGtAction_0_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_0__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonOperator__Group_0__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_0__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonOperatorAccess().getGreaterThanSignKeyword_0_1()); }
	'>'
	{ after(grammarAccess.getComparisonOperatorAccess().getGreaterThanSignKeyword_0_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__ComparisonOperator__Group_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonOperator__Group_1__0__Impl
	rule__ComparisonOperator__Group_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonOperatorAccess().getGeAction_1_0()); }
	()
	{ after(grammarAccess.getComparisonOperatorAccess().getGeAction_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonOperator__Group_1__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonOperatorAccess().getGreaterThanSignEqualsSignKeyword_1_1()); }
	'>='
	{ after(grammarAccess.getComparisonOperatorAccess().getGreaterThanSignEqualsSignKeyword_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__ComparisonOperator__Group_2__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonOperator__Group_2__0__Impl
	rule__ComparisonOperator__Group_2__1
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_2__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonOperatorAccess().getLtAction_2_0()); }
	()
	{ after(grammarAccess.getComparisonOperatorAccess().getLtAction_2_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_2__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonOperator__Group_2__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_2__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonOperatorAccess().getLessThanSignKeyword_2_1()); }
	'<'
	{ after(grammarAccess.getComparisonOperatorAccess().getLessThanSignKeyword_2_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__ComparisonOperator__Group_3__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonOperator__Group_3__0__Impl
	rule__ComparisonOperator__Group_3__1
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_3__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonOperatorAccess().getLeAction_3_0()); }
	()
	{ after(grammarAccess.getComparisonOperatorAccess().getLeAction_3_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_3__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonOperator__Group_3__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_3__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonOperatorAccess().getLessThanSignEqualsSignKeyword_3_1()); }
	'<='
	{ after(grammarAccess.getComparisonOperatorAccess().getLessThanSignEqualsSignKeyword_3_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__ComparisonOperator__Group_4__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonOperator__Group_4__0__Impl
	rule__ComparisonOperator__Group_4__1
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_4__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonOperatorAccess().getEqAction_4_0()); }
	()
	{ after(grammarAccess.getComparisonOperatorAccess().getEqAction_4_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_4__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonOperator__Group_4__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_4__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonOperatorAccess().getEqualsSignEqualsSignKeyword_4_1()); }
	'=='
	{ after(grammarAccess.getComparisonOperatorAccess().getEqualsSignEqualsSignKeyword_4_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__ComparisonOperator__Group_5__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonOperator__Group_5__0__Impl
	rule__ComparisonOperator__Group_5__1
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_5__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonOperatorAccess().getNeAction_5_0()); }
	()
	{ after(grammarAccess.getComparisonOperatorAccess().getNeAction_5_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_5__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__ComparisonOperator__Group_5__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonOperator__Group_5__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getComparisonOperatorAccess().getExclamationMarkEqualsSignKeyword_5_1()); }
	'!='
	{ after(grammarAccess.getComparisonOperatorAccess().getExclamationMarkEqualsSignKeyword_5_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__AdditiveExpression__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AdditiveExpression__Group__0__Impl
	rule__AdditiveExpression__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveExpression__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAdditiveExpressionAccess().getInExpressionParserRuleCall_0()); }
	ruleInExpression
	{ after(grammarAccess.getAdditiveExpressionAccess().getInExpressionParserRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveExpression__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AdditiveExpression__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveExpression__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAdditiveExpressionAccess().getGroup_1()); }
	(rule__AdditiveExpression__Group_1__0)*
	{ after(grammarAccess.getAdditiveExpressionAccess().getGroup_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__AdditiveExpression__Group_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AdditiveExpression__Group_1__0__Impl
	rule__AdditiveExpression__Group_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveExpression__Group_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAdditiveExpressionAccess().getBinaryExpressionLeftExprAction_1_0()); }
	()
	{ after(grammarAccess.getAdditiveExpressionAccess().getBinaryExpressionLeftExprAction_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveExpression__Group_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AdditiveExpression__Group_1__1__Impl
	rule__AdditiveExpression__Group_1__2
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveExpression__Group_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAdditiveExpressionAccess().getOperatorAssignment_1_1()); }
	(rule__AdditiveExpression__OperatorAssignment_1_1)
	{ after(grammarAccess.getAdditiveExpressionAccess().getOperatorAssignment_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveExpression__Group_1__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AdditiveExpression__Group_1__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveExpression__Group_1__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAdditiveExpressionAccess().getRightExprAssignment_1_2()); }
	(rule__AdditiveExpression__RightExprAssignment_1_2)
	{ after(grammarAccess.getAdditiveExpressionAccess().getRightExprAssignment_1_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__AdditiveOperator__Group_0__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AdditiveOperator__Group_0__0__Impl
	rule__AdditiveOperator__Group_0__1
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveOperator__Group_0__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAdditiveOperatorAccess().getPlusAction_0_0()); }
	()
	{ after(grammarAccess.getAdditiveOperatorAccess().getPlusAction_0_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveOperator__Group_0__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AdditiveOperator__Group_0__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveOperator__Group_0__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAdditiveOperatorAccess().getPlusSignKeyword_0_1()); }
	'+'
	{ after(grammarAccess.getAdditiveOperatorAccess().getPlusSignKeyword_0_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__AdditiveOperator__Group_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AdditiveOperator__Group_1__0__Impl
	rule__AdditiveOperator__Group_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveOperator__Group_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAdditiveOperatorAccess().getMinusAction_1_0()); }
	()
	{ after(grammarAccess.getAdditiveOperatorAccess().getMinusAction_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveOperator__Group_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AdditiveOperator__Group_1__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveOperator__Group_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAdditiveOperatorAccess().getHyphenMinusKeyword_1_1()); }
	'-'
	{ after(grammarAccess.getAdditiveOperatorAccess().getHyphenMinusKeyword_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__InExpression__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InExpression__Group__0__Impl
	rule__InExpression__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__InExpression__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInExpressionAccess().getMultiplicativeExpressionParserRuleCall_0()); }
	ruleMultiplicativeExpression
	{ after(grammarAccess.getInExpressionAccess().getMultiplicativeExpressionParserRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__InExpression__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InExpression__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__InExpression__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInExpressionAccess().getGroup_1()); }
	(rule__InExpression__Group_1__0)*
	{ after(grammarAccess.getInExpressionAccess().getGroup_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__InExpression__Group_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InExpression__Group_1__0__Impl
	rule__InExpression__Group_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__InExpression__Group_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInExpressionAccess().getBinaryExpressionLeftExprAction_1_0()); }
	()
	{ after(grammarAccess.getInExpressionAccess().getBinaryExpressionLeftExprAction_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__InExpression__Group_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InExpression__Group_1__1__Impl
	rule__InExpression__Group_1__2
;
finally {
	restoreStackSize(stackSize);
}

rule__InExpression__Group_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInExpressionAccess().getOperatorAssignment_1_1()); }
	(rule__InExpression__OperatorAssignment_1_1)
	{ after(grammarAccess.getInExpressionAccess().getOperatorAssignment_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__InExpression__Group_1__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InExpression__Group_1__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__InExpression__Group_1__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInExpressionAccess().getRightExprAssignment_1_2()); }
	(rule__InExpression__RightExprAssignment_1_2)
	{ after(grammarAccess.getInExpressionAccess().getRightExprAssignment_1_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__InOperator__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InOperator__Group__0__Impl
	rule__InOperator__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__InOperator__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInOperatorAccess().getInAction_0()); }
	()
	{ after(grammarAccess.getInOperatorAccess().getInAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__InOperator__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__InOperator__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__InOperator__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getInOperatorAccess().getAlternatives_1()); }
	(rule__InOperator__Alternatives_1)
	{ after(grammarAccess.getInOperatorAccess().getAlternatives_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__MultiplicativeExpression__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MultiplicativeExpression__Group__0__Impl
	rule__MultiplicativeExpression__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeExpression__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMultiplicativeExpressionAccess().getUnaryExpressionParserRuleCall_0()); }
	ruleUnaryExpression
	{ after(grammarAccess.getMultiplicativeExpressionAccess().getUnaryExpressionParserRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeExpression__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MultiplicativeExpression__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeExpression__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMultiplicativeExpressionAccess().getGroup_1()); }
	(rule__MultiplicativeExpression__Group_1__0)*
	{ after(grammarAccess.getMultiplicativeExpressionAccess().getGroup_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__MultiplicativeExpression__Group_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MultiplicativeExpression__Group_1__0__Impl
	rule__MultiplicativeExpression__Group_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeExpression__Group_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMultiplicativeExpressionAccess().getBinaryExpressionLeftExprAction_1_0()); }
	()
	{ after(grammarAccess.getMultiplicativeExpressionAccess().getBinaryExpressionLeftExprAction_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeExpression__Group_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MultiplicativeExpression__Group_1__1__Impl
	rule__MultiplicativeExpression__Group_1__2
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeExpression__Group_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMultiplicativeExpressionAccess().getOperatorAssignment_1_1()); }
	(rule__MultiplicativeExpression__OperatorAssignment_1_1)
	{ after(grammarAccess.getMultiplicativeExpressionAccess().getOperatorAssignment_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeExpression__Group_1__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MultiplicativeExpression__Group_1__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeExpression__Group_1__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMultiplicativeExpressionAccess().getRightExprAssignment_1_2()); }
	(rule__MultiplicativeExpression__RightExprAssignment_1_2)
	{ after(grammarAccess.getMultiplicativeExpressionAccess().getRightExprAssignment_1_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__MultiplicativeOperator__Group_0__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MultiplicativeOperator__Group_0__0__Impl
	rule__MultiplicativeOperator__Group_0__1
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeOperator__Group_0__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMultiplicativeOperatorAccess().getTimesAction_0_0()); }
	()
	{ after(grammarAccess.getMultiplicativeOperatorAccess().getTimesAction_0_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeOperator__Group_0__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MultiplicativeOperator__Group_0__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeOperator__Group_0__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMultiplicativeOperatorAccess().getAsteriskKeyword_0_1()); }
	'*'
	{ after(grammarAccess.getMultiplicativeOperatorAccess().getAsteriskKeyword_0_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__MultiplicativeOperator__Group_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MultiplicativeOperator__Group_1__0__Impl
	rule__MultiplicativeOperator__Group_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeOperator__Group_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMultiplicativeOperatorAccess().getDivideAction_1_0()); }
	()
	{ after(grammarAccess.getMultiplicativeOperatorAccess().getDivideAction_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeOperator__Group_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MultiplicativeOperator__Group_1__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeOperator__Group_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMultiplicativeOperatorAccess().getSolidusKeyword_1_1()); }
	'/'
	{ after(grammarAccess.getMultiplicativeOperatorAccess().getSolidusKeyword_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__UnaryExpression__Group_0__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__UnaryExpression__Group_0__0__Impl
	rule__UnaryExpression__Group_0__1
;
finally {
	restoreStackSize(stackSize);
}

rule__UnaryExpression__Group_0__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getUnaryExpressionAccess().getNotExpressionAction_0_0()); }
	()
	{ after(grammarAccess.getUnaryExpressionAccess().getNotExpressionAction_0_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__UnaryExpression__Group_0__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__UnaryExpression__Group_0__1__Impl
	rule__UnaryExpression__Group_0__2
;
finally {
	restoreStackSize(stackSize);
}

rule__UnaryExpression__Group_0__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getUnaryExpressionAccess().getAlternatives_0_1()); }
	(rule__UnaryExpression__Alternatives_0_1)
	{ after(grammarAccess.getUnaryExpressionAccess().getAlternatives_0_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__UnaryExpression__Group_0__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__UnaryExpression__Group_0__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__UnaryExpression__Group_0__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getUnaryExpressionAccess().getExprAssignment_0_2()); }
	(rule__UnaryExpression__ExprAssignment_0_2)
	{ after(grammarAccess.getUnaryExpressionAccess().getExprAssignment_0_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__PrimaryExpression__Group_7__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__PrimaryExpression__Group_7__0__Impl
	rule__PrimaryExpression__Group_7__1
;
finally {
	restoreStackSize(stackSize);
}

rule__PrimaryExpression__Group_7__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPrimaryExpressionAccess().getLeftParenthesisKeyword_7_0()); }
	'('
	{ after(grammarAccess.getPrimaryExpressionAccess().getLeftParenthesisKeyword_7_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__PrimaryExpression__Group_7__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__PrimaryExpression__Group_7__1__Impl
	rule__PrimaryExpression__Group_7__2
;
finally {
	restoreStackSize(stackSize);
}

rule__PrimaryExpression__Group_7__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPrimaryExpressionAccess().getAssignmentExpressionParserRuleCall_7_1()); }
	ruleAssignmentExpression
	{ after(grammarAccess.getPrimaryExpressionAccess().getAssignmentExpressionParserRuleCall_7_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__PrimaryExpression__Group_7__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__PrimaryExpression__Group_7__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__PrimaryExpression__Group_7__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPrimaryExpressionAccess().getRightParenthesisKeyword_7_2()); }
	')'
	{ after(grammarAccess.getPrimaryExpressionAccess().getRightParenthesisKeyword_7_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__EDoubleObject__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDoubleObject__Group__0__Impl
	rule__EDoubleObject__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleObjectAccess().getHyphenMinusKeyword_0()); }
	('-')?
	{ after(grammarAccess.getEDoubleObjectAccess().getHyphenMinusKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDoubleObject__Group__1__Impl
	rule__EDoubleObject__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleObjectAccess().getINTTerminalRuleCall_1()); }
	RULE_INT
	{ after(grammarAccess.getEDoubleObjectAccess().getINTTerminalRuleCall_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDoubleObject__Group__2__Impl
	rule__EDoubleObject__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleObjectAccess().getFullStopKeyword_2()); }
	'.'
	{ after(grammarAccess.getEDoubleObjectAccess().getFullStopKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EDoubleObject__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__EDoubleObject__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEDoubleObjectAccess().getINTTerminalRuleCall_3()); }
	RULE_INT
	{ after(grammarAccess.getEDoubleObjectAccess().getINTTerminalRuleCall_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__EIntegerObject__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EIntegerObject__Group__0__Impl
	rule__EIntegerObject__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__EIntegerObject__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEIntegerObjectAccess().getHyphenMinusKeyword_0()); }
	('-')?
	{ after(grammarAccess.getEIntegerObjectAccess().getHyphenMinusKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EIntegerObject__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EIntegerObject__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__EIntegerObject__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEIntegerObjectAccess().getINTTerminalRuleCall_1()); }
	RULE_INT
	{ after(grammarAccess.getEIntegerObjectAccess().getINTTerminalRuleCall_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__BooleanSpecification__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BooleanSpecification__Group__0__Impl
	rule__BooleanSpecification__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__BooleanSpecification__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBooleanSpecificationAccess().getLiteralBooleanAction_0()); }
	()
	{ after(grammarAccess.getBooleanSpecificationAccess().getLiteralBooleanAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__BooleanSpecification__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__BooleanSpecification__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__BooleanSpecification__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getBooleanSpecificationAccess().getAlternatives_1()); }
	(rule__BooleanSpecification__Alternatives_1)
	{ after(grammarAccess.getBooleanSpecificationAccess().getAlternatives_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__NullSpecification__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__NullSpecification__Group__0__Impl
	rule__NullSpecification__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__NullSpecification__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNullSpecificationAccess().getLiteralNullAction_0()); }
	()
	{ after(grammarAccess.getNullSpecificationAccess().getLiteralNullAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__NullSpecification__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__NullSpecification__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__NullSpecification__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getNullSpecificationAccess().getAlternatives_1()); }
	(rule__NullSpecification__Alternatives_1)
	{ after(grammarAccess.getNullSpecificationAccess().getAlternatives_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__PropertyAccess__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__PropertyAccess__Group__0__Impl
	rule__PropertyAccess__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__PropertyAccess__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPropertyAccessAccess().getUnaryExpressionAction_0()); }
	()
	{ after(grammarAccess.getPropertyAccessAccess().getUnaryExpressionAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__PropertyAccess__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__PropertyAccess__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__PropertyAccess__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPropertyAccessAccess().getIdentifierAssignment_1()); }
	(rule__PropertyAccess__IdentifierAssignment_1)
	{ after(grammarAccess.getPropertyAccessAccess().getIdentifierAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Identifier__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Identifier__Group__0__Impl
	rule__Identifier__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Identifier__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getIdentifierAccess().getIdentifierAction_0()); }
	()
	{ after(grammarAccess.getIdentifierAccess().getIdentifierAction_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Identifier__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Identifier__Group__1__Impl
	rule__Identifier__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Identifier__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getIdentifierAccess().getNameAssignment_1()); }
	(rule__Identifier__NameAssignment_1)
	{ after(grammarAccess.getIdentifierAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Identifier__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Identifier__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Identifier__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getIdentifierAccess().getGroup_2()); }
	(rule__Identifier__Group_2__0)?
	{ after(grammarAccess.getIdentifierAccess().getGroup_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Identifier__Group_2__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Identifier__Group_2__0__Impl
	rule__Identifier__Group_2__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Identifier__Group_2__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getIdentifierAccess().getLeftSquareBracketKeyword_2_0()); }
	'['
	{ after(grammarAccess.getIdentifierAccess().getLeftSquareBracketKeyword_2_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Identifier__Group_2__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Identifier__Group_2__1__Impl
	rule__Identifier__Group_2__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Identifier__Group_2__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getIdentifierAccess().getIndexAssignment_2_1()); }
	(rule__Identifier__IndexAssignment_2_1)
	{ after(grammarAccess.getIdentifierAccess().getIndexAssignment_2_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Identifier__Group_2__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Identifier__Group_2__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Identifier__Group_2__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getIdentifierAccess().getRightSquareBracketKeyword_2_2()); }
	']'
	{ after(grammarAccess.getIdentifierAccess().getRightSquareBracketKeyword_2_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__SignedInt__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__SignedInt__Group__0__Impl
	rule__SignedInt__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__SignedInt__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSignedIntAccess().getHyphenMinusKeyword_0()); }
	('-')?
	{ after(grammarAccess.getSignedIntAccess().getHyphenMinusKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__SignedInt__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__SignedInt__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__SignedInt__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getSignedIntAccess().getINTTerminalRuleCall_1()); }
	RULE_INT
	{ after(grammarAccess.getSignedIntAccess().getINTTerminalRuleCall_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__QualifiedName__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QualifiedName__Group__0__Impl
	rule__QualifiedName__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__QualifiedName__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQualifiedNameAccess().getIDTerminalRuleCall_0()); }
	RULE_ID
	{ after(grammarAccess.getQualifiedNameAccess().getIDTerminalRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QualifiedName__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QualifiedName__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__QualifiedName__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQualifiedNameAccess().getGroup_1()); }
	(rule__QualifiedName__Group_1__0)*
	{ after(grammarAccess.getQualifiedNameAccess().getGroup_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__QualifiedName__Group_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QualifiedName__Group_1__0__Impl
	rule__QualifiedName__Group_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__QualifiedName__Group_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQualifiedNameAccess().getFullStopKeyword_1_0()); }
	'.'
	{ after(grammarAccess.getQualifiedNameAccess().getFullStopKeyword_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__QualifiedName__Group_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__QualifiedName__Group_1__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__QualifiedName__Group_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getQualifiedNameAccess().getIDTerminalRuleCall_1_1()); }
	RULE_ID
	{ after(grammarAccess.getQualifiedNameAccess().getIDTerminalRuleCall_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__EnumQualifiedName__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EnumQualifiedName__Group__0__Impl
	rule__EnumQualifiedName__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__EnumQualifiedName__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEnumQualifiedNameAccess().getIDTerminalRuleCall_0()); }
	RULE_ID
	{ after(grammarAccess.getEnumQualifiedNameAccess().getIDTerminalRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EnumQualifiedName__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EnumQualifiedName__Group__1__Impl
	rule__EnumQualifiedName__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__EnumQualifiedName__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEnumQualifiedNameAccess().getColonColonKeyword_1()); }
	'::'
	{ after(grammarAccess.getEnumQualifiedNameAccess().getColonColonKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__EnumQualifiedName__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__EnumQualifiedName__Group__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__EnumQualifiedName__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getEnumQualifiedNameAccess().getIDTerminalRuleCall_2()); }
	RULE_ID
	{ after(grammarAccess.getEnumQualifiedNameAccess().getIDTerminalRuleCall_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__AssignmentExpression__IdentifierAssignment_0_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAssignmentExpressionAccess().getIdentifierIdentifierParserRuleCall_0_1_0()); }
		ruleIdentifier
		{ after(grammarAccess.getAssignmentExpressionAccess().getIdentifierIdentifierParserRuleCall_0_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AssignmentExpression__ExprAssignment_0_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAssignmentExpressionAccess().getExprAssignmentExpressionParserRuleCall_0_3_0()); }
		ruleAssignmentExpression
		{ after(grammarAccess.getAssignmentExpressionAccess().getExprAssignmentExpressionParserRuleCall_0_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__OrExpression__OperatorAssignment_1_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getOrExpressionAccess().getOperatorOrOperatorParserRuleCall_1_1_0()); }
		ruleOrOperator
		{ after(grammarAccess.getOrExpressionAccess().getOperatorOrOperatorParserRuleCall_1_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__OrExpression__RightExprAssignment_1_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getOrExpressionAccess().getRightExprAndExpressionParserRuleCall_1_2_0()); }
		ruleAndExpression
		{ after(grammarAccess.getOrExpressionAccess().getRightExprAndExpressionParserRuleCall_1_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AndExpression__OperatorAssignment_1_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAndExpressionAccess().getOperatorAndOperatorParserRuleCall_1_1_0()); }
		ruleAndOperator
		{ after(grammarAccess.getAndExpressionAccess().getOperatorAndOperatorParserRuleCall_1_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AndExpression__RightExprAssignment_1_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAndExpressionAccess().getRightExprComparisonExpressionParserRuleCall_1_2_0()); }
		ruleComparisonExpression
		{ after(grammarAccess.getAndExpressionAccess().getRightExprComparisonExpressionParserRuleCall_1_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonExpression__OperatorAssignment_1_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getComparisonExpressionAccess().getOperatorComparisonOperatorParserRuleCall_1_1_0()); }
		ruleComparisonOperator
		{ after(grammarAccess.getComparisonExpressionAccess().getOperatorComparisonOperatorParserRuleCall_1_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__ComparisonExpression__RightExprAssignment_1_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getComparisonExpressionAccess().getRightExprAdditiveExpressionParserRuleCall_1_2_0()); }
		ruleAdditiveExpression
		{ after(grammarAccess.getComparisonExpressionAccess().getRightExprAdditiveExpressionParserRuleCall_1_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveExpression__OperatorAssignment_1_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAdditiveExpressionAccess().getOperatorAdditiveOperatorParserRuleCall_1_1_0()); }
		ruleAdditiveOperator
		{ after(grammarAccess.getAdditiveExpressionAccess().getOperatorAdditiveOperatorParserRuleCall_1_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AdditiveExpression__RightExprAssignment_1_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAdditiveExpressionAccess().getRightExprInExpressionParserRuleCall_1_2_0()); }
		ruleInExpression
		{ after(grammarAccess.getAdditiveExpressionAccess().getRightExprInExpressionParserRuleCall_1_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__InExpression__OperatorAssignment_1_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInExpressionAccess().getOperatorInOperatorParserRuleCall_1_1_0()); }
		ruleInOperator
		{ after(grammarAccess.getInExpressionAccess().getOperatorInOperatorParserRuleCall_1_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__InExpression__RightExprAssignment_1_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInExpressionAccess().getRightExprMultiplicativeExpressionParserRuleCall_1_2_0()); }
		ruleMultiplicativeExpression
		{ after(grammarAccess.getInExpressionAccess().getRightExprMultiplicativeExpressionParserRuleCall_1_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeExpression__OperatorAssignment_1_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMultiplicativeExpressionAccess().getOperatorMultiplicativeOperatorParserRuleCall_1_1_0()); }
		ruleMultiplicativeOperator
		{ after(grammarAccess.getMultiplicativeExpressionAccess().getOperatorMultiplicativeOperatorParserRuleCall_1_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MultiplicativeExpression__RightExprAssignment_1_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMultiplicativeExpressionAccess().getRightExprUnaryExpressionParserRuleCall_1_2_0()); }
		ruleUnaryExpression
		{ after(grammarAccess.getMultiplicativeExpressionAccess().getRightExprUnaryExpressionParserRuleCall_1_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__UnaryExpression__ExprAssignment_0_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getUnaryExpressionAccess().getExprPrimaryExpressionParserRuleCall_0_2_0()); }
		rulePrimaryExpression
		{ after(grammarAccess.getUnaryExpressionAccess().getExprPrimaryExpressionParserRuleCall_0_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__LiteralReal__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLiteralRealAccess().getValueRealSpecificationParserRuleCall_0()); }
		ruleRealSpecification
		{ after(grammarAccess.getLiteralRealAccess().getValueRealSpecificationParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__RealSpecification__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getRealSpecificationAccess().getValueEDoubleObjectParserRuleCall_0()); }
		ruleEDoubleObject
		{ after(grammarAccess.getRealSpecificationAccess().getValueEDoubleObjectParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__LiteralInteger__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLiteralIntegerAccess().getValueIntegerSpecificationParserRuleCall_0()); }
		ruleIntegerSpecification
		{ after(grammarAccess.getLiteralIntegerAccess().getValueIntegerSpecificationParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__IntegerSpecification__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getIntegerSpecificationAccess().getValueEIntegerObjectParserRuleCall_0()); }
		ruleEIntegerObject
		{ after(grammarAccess.getIntegerSpecificationAccess().getValueEIntegerObjectParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__LiteralString__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLiteralStringAccess().getValueStringSpecificationParserRuleCall_0()); }
		ruleStringSpecification
		{ after(grammarAccess.getLiteralStringAccess().getValueStringSpecificationParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__StringSpecification__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getStringSpecificationAccess().getValueSTRINGTerminalRuleCall_0()); }
		RULE_STRING
		{ after(grammarAccess.getStringSpecificationAccess().getValueSTRINGTerminalRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__LiteralBoolean__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLiteralBooleanAccess().getValueBooleanSpecificationParserRuleCall_0()); }
		ruleBooleanSpecification
		{ after(grammarAccess.getLiteralBooleanAccess().getValueBooleanSpecificationParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__BooleanSpecification__ValueAssignment_1_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getBooleanSpecificationAccess().getValueTrueKeyword_1_0_0()); }
		(
			{ before(grammarAccess.getBooleanSpecificationAccess().getValueTrueKeyword_1_0_0()); }
			'true'
			{ after(grammarAccess.getBooleanSpecificationAccess().getValueTrueKeyword_1_0_0()); }
		)
		{ after(grammarAccess.getBooleanSpecificationAccess().getValueTrueKeyword_1_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__LiteralNull__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLiteralNullAccess().getValueNullSpecificationParserRuleCall_0()); }
		ruleNullSpecification
		{ after(grammarAccess.getLiteralNullAccess().getValueNullSpecificationParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__PropertyAccess__IdentifierAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getPropertyAccessAccess().getIdentifierIdentifierParserRuleCall_1_0()); }
		ruleIdentifier
		{ after(grammarAccess.getPropertyAccessAccess().getIdentifierIdentifierParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Identifier__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getIdentifierAccess().getNameQualifiedNameParserRuleCall_1_0()); }
		ruleQualifiedName
		{ after(grammarAccess.getIdentifierAccess().getNameQualifiedNameParserRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Identifier__IndexAssignment_2_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getIdentifierAccess().getIndexSignedIntParserRuleCall_2_1_0()); }
		ruleSignedInt
		{ after(grammarAccess.getIdentifierAccess().getIndexSignedIntParserRuleCall_2_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__LiteralEnum__ValueAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getLiteralEnumAccess().getValueEnumSpecificationParserRuleCall_0()); }
		ruleEnumSpecification
		{ after(grammarAccess.getLiteralEnumAccess().getValueEnumSpecificationParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__EnumSpecification__NameAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getEnumSpecificationAccess().getNameEnumQualifiedNameParserRuleCall_0()); }
		ruleEnumQualifiedName
		{ after(grammarAccess.getEnumSpecificationAccess().getNameEnumQualifiedNameParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
