#

bin.includes = lemma.adapted.data.metamodel.edit.jar,\
               icons/,\
               META-INF/,\
               plugin.xml,\
               plugin.properties
jars.compile.order = lemma.adapted.data.metamodel.edit.jar
source.lemma.adapted.data.metamodel.edit.jar = src-gen/
output.lemma.adapted.data.metamodel.edit.jar = bin/
