/*
 * generated by Xtext 2.43.0
 */
package dact.dsl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class ExprDslProposalProvider extends AbstractExprDslProposalProvider {
}
