#

pluginName = lemma.adapted.technology.metamodel Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Technology_type = Technology
_UI_TechnologyImport_type = Import
_UI_Protocol_type = Protocol
_UI_DataFormat_type = Data Format
_UI_TechnologySpecificPrimitiveType_type = Specific Primitive Type
_UI_TechnologySpecificCollectionType_type = Specific Collection Type
_UI_TechnologySpecificDataStructure_type = Specific Data Structure
_UI_CompatibilityMatrixEntry_type = Compatibility Matrix Entry
_UI_PossiblyImportedTechnologySpecificType_type = Possibly Imported Technology Specific Type
_UI_OperationTechnology_type = Operation Technology
_UI_OperationEnvironment_type = Operation Environment
_UI_TechnologySpecificProperty_type = Specific Property
_UI_TechnologySpecificPropertyValueAssignment_type = Specific Property Value Assignment
_UI_DeploymentTechnology_type = Deployment Technology
_UI_InfrastructureTechnology_type = Infrastructure Technology
_UI_TechnologyAspect_type = Aspect
_UI_ServiceAspect_type = Service Aspect
_UI_ServiceAspectPointcut_type = Service Aspect Pointcut
_UI_ServiceAspectPointcutSelector_type = Service Aspect Pointcut Selector
_UI_OperationAspect_type = Operation Aspect
_UI_OperationAspectPointcut_type = Operation Aspect Pointcut
_UI_OperationAspectPointcutSelector_type = Operation Aspect Pointcut Selector
_UI_EAttribute_type = EAttribute
_UI_EAnnotation_type = EAnnotation
_UI_EClass_type = EClass
_UI_EClassifier_type = EClassifier
_UI_EDataType_type = EData Type
_UI_EEnum_type = EEnum
_UI_EEnumLiteral_type = EEnum Literal
_UI_EFactory_type = EFactory
_UI_EModelElement_type = EModel Element
_UI_ENamedElement_type = ENamed Element
_UI_EObject_type = EObject
_UI_EOperation_type = EOperation
_UI_EPackage_type = EPackage
_UI_EParameter_type = EParameter
_UI_EReference_type = EReference
_UI_EStructuralFeature_type = EStructural Feature
_UI_ETypedElement_type = ETyped Element
_UI_EStringToStringMapEntry_type = EString To String Map Entry
_UI_EGenericType_type = EGeneric Type
_UI_ETypeParameter_type = EType Parameter
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Technology_name_feature = Name
_UI_Technology_imports_feature = Imports
_UI_Technology_primitiveTypes_feature = Primitive Types
_UI_Technology_collectionTypes_feature = Collection Types
_UI_Technology_dataStructures_feature = Data Structures
_UI_Technology_compatibilityEntries_feature = Compatibility Entries
_UI_Technology_protocols_feature = Protocols
_UI_Technology_serviceAspects_feature = Service Aspects
_UI_Technology_deploymentTechnologies_feature = Deployment Technologies
_UI_Technology_infrastructureTechnologies_feature = Infrastructure Technologies
_UI_Technology_operationAspects_feature = Operation Aspects
_UI_TechnologyImport_name_feature = Name
_UI_TechnologyImport_importURI_feature = Import URI
_UI_TechnologyImport_technology_feature = Technology
_UI_Protocol_name_feature = Name
_UI_Protocol_communicationType_feature = Communication Type
_UI_Protocol_default_feature = Default
_UI_Protocol_defaultFormat_feature = Default Format
_UI_Protocol_dataFormats_feature = Data Formats
_UI_Protocol_technology_feature = Technology
_UI_DataFormat_formatName_feature = Format Name
_UI_DataFormat_protocol_feature = Protocol
_UI_TechnologySpecificPrimitiveType_name_feature = Name
_UI_TechnologySpecificPrimitiveType_default_feature = Default
_UI_TechnologySpecificPrimitiveType_technology_feature = Technology
_UI_TechnologySpecificPrimitiveType_basicBuiltinPrimitiveTypes_feature = Basic Builtin Primitive Types
_UI_TechnologySpecificCollectionType_technology_feature = Technology
_UI_TechnologySpecificDataStructure_technology_feature = Technology
_UI_CompatibilityMatrixEntry_direction_feature = Direction
_UI_CompatibilityMatrixEntry_mappingType_feature = Mapping Type
_UI_CompatibilityMatrixEntry_compatibleTypes_feature = Compatible Types
_UI_CompatibilityMatrixEntry_technology_feature = Technology
_UI_PossiblyImportedTechnologySpecificType_import_feature = Import
_UI_PossiblyImportedTechnologySpecificType_type_feature = Type
_UI_PossiblyImportedTechnologySpecificType_mappingEntry_feature = Mapping Entry
_UI_PossiblyImportedTechnologySpecificType_compatibleEntry_feature = Compatible Entry
_UI_OperationTechnology_name_feature = Name
_UI_OperationTechnology_operationEnvironments_feature = Operation Environments
_UI_OperationTechnology_serviceProperties_feature = Service Properties
_UI_OperationEnvironment_environmentName_feature = Environment Name
_UI_OperationEnvironment_default_feature = Default
_UI_OperationEnvironment_operationTechnology_feature = Operation Technology
_UI_TechnologySpecificProperty_name_feature = Name
_UI_TechnologySpecificProperty_type_feature = Type
_UI_TechnologySpecificProperty_defaultValue_feature = Default Value
_UI_TechnologySpecificProperty_features_feature = Features
_UI_TechnologySpecificProperty_operationTechnology_feature = Operation Technology
_UI_TechnologySpecificProperty_technologyAspect_feature = Technology Aspect
_UI_TechnologySpecificProperty_isMandatory_feature = Is Mandatory
_UI_TechnologySpecificPropertyValueAssignment_property_feature = Property
_UI_TechnologySpecificPropertyValueAssignment_value_feature = Value
_UI_DeploymentTechnology_technology_feature = Technology
_UI_InfrastructureTechnology_technology_feature = Technology
_UI_TechnologyAspect_name_feature = Name
_UI_TechnologyAspect_features_feature = Features
_UI_TechnologyAspect_joinPoints_feature = Join Points
_UI_TechnologyAspect_properties_feature = Properties
_UI_TechnologyAspect_isSingleValued_feature = Is Single Valued
_UI_ServiceAspect_pointcutSelectors_feature = Pointcut Selectors
_UI_ServiceAspect_technology_feature = Technology
_UI_ServiceAspectPointcut_forExchangePattern_feature = For Exchange Pattern
_UI_ServiceAspectPointcut_forCommunicationType_feature = For Communication Type
_UI_ServiceAspectPointcut_forProtocol_feature = For Protocol
_UI_ServiceAspectPointcut_forDataFormat_feature = For Data Format
_UI_ServiceAspectPointcut_exchangePattern_feature = Exchange Pattern
_UI_ServiceAspectPointcut_communicationType_feature = Communication Type
_UI_ServiceAspectPointcut_protocol_feature = Protocol
_UI_ServiceAspectPointcut_dataFormat_feature = Data Format
_UI_ServiceAspectPointcut_selector_feature = Selector
_UI_ServiceAspectPointcut_effectiveType_feature = Effective Type
_UI_ServiceAspectPointcut_effectiveSelectorName_feature = Effective Selector Name
_UI_ServiceAspectPointcut_effectiveValue_feature = Effective Value
_UI_ServiceAspectPointcut_printableEffectiveValue_feature = Printable Effective Value
_UI_ServiceAspectPointcut_orderedPointcutTypes_feature = Ordered Pointcut Types
_UI_ServiceAspectPointcutSelector_pointcuts_feature = Pointcuts
_UI_ServiceAspectPointcutSelector_serviceAspect_feature = Service Aspect
_UI_ServiceAspectPointcutSelector_selectorString_feature = Selector String
_UI_OperationAspect_pointcutSelectors_feature = Pointcut Selectors
_UI_OperationAspect_technology_feature = Technology
_UI_OperationAspectPointcut_forTechnology_feature = For Technology
_UI_OperationAspectPointcut_technology_feature = Technology
_UI_OperationAspectPointcut_selector_feature = Selector
_UI_OperationAspectPointcut_effectiveType_feature = Effective Type
_UI_OperationAspectPointcut_effectiveSelectorName_feature = Effective Selector Name
_UI_OperationAspectPointcut_effectiveValue_feature = Effective Value
_UI_OperationAspectPointcut_printableEffectiveValue_feature = Printable Effective Value
_UI_OperationAspectPointcut_orderedPointcutTypes_feature = Ordered Pointcut Types
_UI_OperationAspectPointcutSelector_pointcuts_feature = Pointcuts
_UI_OperationAspectPointcutSelector_operationAspect_feature = Operation Aspect
_UI_OperationAspectPointcutSelector_selectorString_feature = Selector String
_UI_EAttribute_iD_feature = ID
_UI_EAttribute_iD_description = Whether the value of this attribute uniquely identifies an object within its containing resource
_UI_EAttribute_eAttributeType_feature = EAttribute Type
_UI_EAttribute_eAttributeType_description = The data type of this attribute
_UI_EAnnotation_source_feature = Source
_UI_EAnnotation_source_description = An identifier, typically an absolute URI, that uniquely identifies this kind of annotation
_UI_EAnnotation_details_feature = Details
_UI_EAnnotation_eModelElement_feature = EModel Element
_UI_EAnnotation_contents_feature = Contents
_UI_EAnnotation_references_feature = References
_UI_EAnnotation_references_description = Objects referenced by this annotation
_UI_EClass_abstract_feature = Abstract
_UI_EClass_abstract_description = Whether instances of this class can be created
_UI_EClass_interface_feature = Interface
_UI_EClass_interface_description = Whether no corresponding implementation will be generated for this class
_UI_EClass_eSuperTypes_feature = ESuper Types
_UI_EClass_eSuperTypes_description = The immediate super types of this class
_UI_EClass_eOperations_feature = EOperations
_UI_EClass_eOperations_description = The operations defined by this class
_UI_EClass_eAllAttributes_feature = EAll Attributes
_UI_EClass_eAllReferences_feature = EAll References
_UI_EClass_eReferences_feature = EReferences
_UI_EClass_eAttributes_feature = EAttributes
_UI_EClass_eAllContainments_feature = EAll Containments
_UI_EClass_eAllOperations_feature = EAll Operations
_UI_EClass_eAllStructuralFeatures_feature = EAll Structural Features
_UI_EClass_eAllSuperTypes_feature = EAll Super Types
_UI_EClass_eIDAttribute_feature = EID Attribute
_UI_EClass_eStructuralFeatures_feature = EStructural Features
_UI_EClass_eGenericSuperTypes_feature = EGeneric Super Types
_UI_EClass_eAllGenericSuperTypes_feature = EAll Generic Super Types
_UI_EClassifier_instanceClassName_feature = Instance Class Name
_UI_EClassifier_instanceClassName_description = The erased instance class name denoted by this classifier
_UI_EClassifier_instanceClass_feature = Instance Class
_UI_EClassifier_defaultValue_feature = Default Value
_UI_EClassifier_defaultValue_description = The default value for features of this type
_UI_EClassifier_instanceTypeName_feature = Instance Type Name
_UI_EClassifier_instanceTypeName_description = The full instance type name denoted by this classifier
_UI_EClassifier_ePackage_feature = EPackage
_UI_EClassifier_eTypeParameters_feature = EType Parameters
_UI_EDataType_serializable_feature = Serializable
_UI_EDataType_serializable_description = Whether a value of this data type can be serialized using the factory
_UI_EEnum_eLiterals_feature = ELiterals
_UI_EEnumLiteral_value_feature = Value
_UI_EEnumLiteral_value_description = The integer value associated with this enumerator
_UI_EEnumLiteral_instance_feature = Instance
_UI_EEnumLiteral_literal_feature = Literal
_UI_EEnumLiteral_literal_description = The literal value associated with this enumerator
_UI_EEnumLiteral_eEnum_feature = EEnum
_UI_EFactory_ePackage_feature = EPackage
_UI_EFactory_ePackage_description = The package corresponding to this factory
_UI_EModelElement_eAnnotations_feature = EAnnotations
_UI_ENamedElement_name_feature = Name
_UI_ENamedElement_name_description = The name of this model element
_UI_EOperation_eContainingClass_feature = EContaining Class
_UI_EOperation_eTypeParameters_feature = EType Parameters
_UI_EOperation_eParameters_feature = EParameters
_UI_EOperation_eExceptions_feature = EExceptions
_UI_EOperation_eExceptions_description = The exceptions thrown by this operation
_UI_EOperation_eGenericExceptions_feature = EGeneric Exceptions
_UI_EPackage_nsURI_feature = Ns URI
_UI_EPackage_nsURI_description = The universally unique namespace identifier, typically an absolute URI, for this package
_UI_EPackage_nsPrefix_feature = Ns Prefix
_UI_EPackage_nsPrefix_description = The namespace prefix used by default when serializing instances of the package's classes
_UI_EPackage_eFactoryInstance_feature = EFactory Instance
_UI_EPackage_eFactoryInstance_description = The factory corresponding to this package
_UI_EPackage_eClassifiers_feature = EClassifiers
_UI_EPackage_eSubpackages_feature = ESubpackages
_UI_EPackage_eSuperPackage_feature = ESuper Package
_UI_EParameter_eOperation_feature = EOperation
_UI_EReference_containment_feature = Containment
_UI_EReference_containment_description = Whether this reference represents a composite relationship
_UI_EReference_container_feature = Container
_UI_EReference_container_description = Whether this reference has as its opposite a containment reference
_UI_EReference_resolveProxies_feature = Resolve Proxies
_UI_EReference_resolveProxies_description = Whether this reference resolves proxies automatically
_UI_EReference_eOpposite_feature = EOpposite
_UI_EReference_eOpposite_description = The reference that represents the bidirectional opposite of this reference
_UI_EReference_eReferenceType_feature = EReference Type
_UI_EReference_eReferenceType_description = The target class of the reference
_UI_EReference_eKeys_feature = EKeys
_UI_EReference_eKeys_description = The attributes of the referenced class that uniquely identify a referenced instance
_UI_EStructuralFeature_changeable_feature = Changeable
_UI_EStructuralFeature_changeable_description = Whether the value of this feature can be changed
_UI_EStructuralFeature_volatile_feature = Volatile
_UI_EStructuralFeature_volatile_description = Whether no field will be generated for this feature
_UI_EStructuralFeature_transient_feature = Transient
_UI_EStructuralFeature_transient_description = Whether the value of this feature will be serialized
_UI_EStructuralFeature_defaultValueLiteral_feature = Default Value Literal
_UI_EStructuralFeature_defaultValueLiteral_description = The literal representation of the default value for this feature
_UI_EStructuralFeature_defaultValue_feature = Default Value
_UI_EStructuralFeature_defaultValue_description = The default value for this feature
_UI_EStructuralFeature_unsettable_feature = Unsettable
_UI_EStructuralFeature_unsettable_description = Whether the value space for this feature includes the state of not being set
_UI_EStructuralFeature_derived_feature = Derived
_UI_EStructuralFeature_derived_description = Whether the value of this feature is derived from the values of other features
_UI_EStructuralFeature_eContainingClass_feature = EContaining Class
_UI_EStructuralFeature_eContainingClass_description = The class that defines this feature
_UI_ETypedElement_ordered_feature = Ordered
_UI_ETypedElement_ordered_description = Whether the order in which values occur is meaningful
_UI_ETypedElement_unique_feature = Unique
_UI_ETypedElement_unique_description = Whether the same value may occur more than once
_UI_ETypedElement_lowerBound_feature = Lower Bound
_UI_ETypedElement_lowerBound_description = The minimum number of values that must occur
_UI_ETypedElement_upperBound_feature = Upper Bound
_UI_ETypedElement_upperBound_description = The maximum number of values that may occur; -1 represents unbounded and -2 represents unspecified
_UI_ETypedElement_many_feature = Many
_UI_ETypedElement_many_description = Whether more than one value may occur
_UI_ETypedElement_required_feature = Required
_UI_ETypedElement_required_description = Whether at least one value must occur
_UI_ETypedElement_eType_feature = EType
_UI_ETypedElement_eType_description = The type of this element
_UI_ETypedElement_eGenericType_feature = EGeneric Type
_UI_EStringToStringMapEntry_key_feature = Key
_UI_EStringToStringMapEntry_key_description = The key of this map entry
_UI_EStringToStringMapEntry_value_feature = Value
_UI_EStringToStringMapEntry_value_description = The value of this map entry
_UI_EGenericType_eUpperBound_feature = EUpper Bound
_UI_EGenericType_eTypeArguments_feature = EType Arguments
_UI_EGenericType_eRawType_feature = ERaw Type
_UI_EGenericType_eRawType_description = The erased type denoted by this generic type
_UI_EGenericType_eLowerBound_feature = ELower Bound
_UI_EGenericType_eTypeParameter_feature = EType Parameter
_UI_EGenericType_eTypeParameter_description = The type parameter denoted by this generic type
_UI_EGenericType_eClassifier_feature = EClassifier
_UI_EGenericType_eClassifier_description = The classifier denoted by this generic type
_UI_ETypeParameter_eBounds_feature = EBounds
_UI_Unknown_feature = Unspecified

_UI_ExchangePattern_IN_literal = IN
_UI_ExchangePattern_OUT_literal = OUT
_UI_ExchangePattern_INOUT_literal = INOUT
_UI_CommunicationType_SYNCHRONOUS_literal = SYNCHRONOUS
_UI_CommunicationType_ASYNCHRONOUS_literal = ASYNCHRONOUS
_UI_CompatibilityDirection_MAPPING_TO_COMPATIBLE_TYPES_literal = MAPPING_TO_COMPATIBLE_TYPES
_UI_CompatibilityDirection_COMPATIBLE_TYPES_TO_MAPPING_literal = COMPATIBLE_TYPES_TO_MAPPING
_UI_CompatibilityDirection_BIDIRECTIONAL_literal = BIDIRECTIONAL
_UI_PropertyFeature_MANDATORY_literal = MANDATORY
_UI_PropertyFeature_SINGLE_VALUED_literal = SINGLE_VALUED
_UI_JoinPointType_DATA_OPERATIONS_literal = DATA_OPERATIONS
_UI_JoinPointType_DATA_OPERATION_PARAMETERS_literal = DATA_OPERATION_PARAMETERS
_UI_JoinPointType_MICROSERVICES_literal = MICROSERVICES
_UI_JoinPointType_INTERFACES_literal = INTERFACES
_UI_JoinPointType_OPERATIONS_literal = OPERATIONS
_UI_JoinPointType_PARAMETERS_literal = PARAMETERS
_UI_JoinPointType_COMPLEX_TYPES_literal = COMPLEX_TYPES
_UI_JoinPointType_DATA_FIELDS_literal = DATA_FIELDS
_UI_JoinPointType_CONTAINERS_literal = CONTAINERS
_UI_JoinPointType_INFRASTRUCTURE_NODES_literal = INFRASTRUCTURE_NODES
_UI_PointcutType_EXCHANGE_PATTERN_literal = EXCHANGE_PATTERN
_UI_PointcutType_COMMUNICATION_TYPE_literal = COMMUNICATION_TYPE
_UI_PointcutType_PROTOCOL_literal = PROTOCOL
_UI_PointcutType_DATA_FORMAT_literal = DATA_FORMAT
_UI_PointcutType_TECHNOLOGY_literal = TECHNOLOGY
_UI_AspectFeature_SINGLE_VALUED_literal = SINGLE_VALUED
