/**
 *
 * $Id$
 */
package dact.validation;

import dact.ActivityGroup;
import dact.ActivityNode;

/**
 * A sample validator interface for {@link dact.ActivityEdge}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityEdgeValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateEdgeName(String value);

	boolean validateTName(String value);

	boolean validateEName(String value);

	boolean validateSource(ActivityNode value);
	boolean validateTarget(ActivityNode value);
	boolean validateGroup(ActivityGroup value);
}
