/**
 *
 * $Id$
 */
package dact.validation;

import dact.DomainElement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dact.BoundedContext}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BoundedContextValidator {
	boolean validate();

	boolean validateIsExternal(Boolean value);

	boolean validate_(Object value);

	boolean validateOwnedElements(EList<DomainElement> value);
}
