/**
 *
 * $Id$
 */
package dact.validation;

import dact.DomainNode;
import dact.Operation;

/**
 * A sample validator interface for {@link dact.DomainNodeOperationMapping}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DomainNodeOperationMappingValidator {
	boolean validate();

	boolean validateUsedByExternalContext(Boolean value);
	boolean validateDomainNode(DomainNode value);
	boolean validateOperation(Operation value);
}
