/**
 *
 * $Id$
 */
package dact.validation;

import dact.Type;


/**
 * A sample validator interface for {@link dact.Expression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExpressionValidator {
	boolean validate();

	boolean validateEvaluatedType(Type value);

	boolean validateLowerBound(Integer value);

	boolean validateUpperBound(Integer value);

}
