/**
 *
 * $Id$
 */
package dact.validation;


/**
 * A sample validator interface for {@link dact.LiteralBoolean}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LiteralBooleanValidator {
	boolean validate();

	boolean validateValue(boolean value);

	boolean validateValue(Boolean value);
}
