/**
 *
 * $Id$
 */
package dact.validation;

import dact.Behavior;
import dact.DomainObject;
import dact.Interface;
import dact.OperationType;
import dact.Parameter;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dact.Operation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperationValidator {
	boolean validate();

	boolean validateToExpose(Boolean value);

	boolean validateType(OperationType value);
	boolean validateClosure(Boolean value);
	boolean validateSideEffectFree(Boolean value);
	boolean validateBehavior(Behavior value);
	boolean validateOwnedParameters(EList<Parameter> value);
	boolean validateInterface(Interface value);
	boolean validateDomainObject(DomainObject value);
}
