/**
 *
 * $Id$
 */
package dact.validation;

import dact.ActivityModel;
import dact.DddModel;
import dact.PrimitiveType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dact.Root}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RootValidator {
	boolean validate();

	boolean validateDdd(Object value);

	boolean validateActivity(Object value);

	boolean validateDdd(DddModel value);
	boolean validateActivity(ActivityModel value);
	boolean validatePrimitivesTypes(EList<PrimitiveType> value);
}
