/**
 *
 * $Id$
 */
package dact.validation;

import dact.ActivityGroup;
import dact.DomainObject;
import dact.Scope;
import dact.Variable;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dact.Scope}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ScopeValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateTName(String value);

	boolean validateEName(String value);

	boolean validateParent(Scope value);
	boolean validateChildren(EList<Scope> value);
	boolean validateInheritedVariables(EList<Variable> value);
	boolean validateOwnedVariables(EList<Variable> value);
	boolean validateGroup(ActivityGroup value);

	boolean validateDomainObject(DomainObject value);
}
