/**
 *
 * $Id$
 */
package dact.validation;

import dact.Expression;
import dact.SpecOperation;

/**
 * A sample validator interface for {@link dact.SpecRule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SpecRuleValidator {
	boolean validate();

	boolean validateRawString(String value);
	boolean validateExpr(Expression value);

	boolean validateOperation(SpecOperation value);
}
