/**
 *
 * $Id$
 */
package dact.validation;

import dact.ActivityGroup;
import dact.Expression;

/**
 * A sample validator interface for {@link dact.StructuredActivityNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StructuredActivityNodeValidator {
	boolean validate();

	boolean validateTest(Expression value);
	boolean validateBody(ActivityGroup value);
}
