/**
 */
package lemma.adapted.xcore.data.provider;

import java.util.ArrayList;
import java.util.Collection;

import lemma.adapted.xcore.data.util.DataAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DataItemProviderAdapterFactory extends DataAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DataItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.DataModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataModelItemProvider dataModelItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.DataModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataModelAdapter() {
		if (dataModelItemProvider == null) {
			dataModelItemProvider = new DataModelItemProvider(this);
		}

		return dataModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.ComplexTypeImport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComplexTypeImportItemProvider complexTypeImportItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.ComplexTypeImport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComplexTypeImportAdapter() {
		if (complexTypeImportItemProvider == null) {
			complexTypeImportItemProvider = new ComplexTypeImportItemProvider(this);
		}

		return complexTypeImportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.Version} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VersionItemProvider versionItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.Version}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVersionAdapter() {
		if (versionItemProvider == null) {
			versionItemProvider = new VersionItemProvider(this);
		}

		return versionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.Context} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContextItemProvider contextItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.Context}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContextAdapter() {
		if (contextItemProvider == null) {
			contextItemProvider = new ContextItemProvider(this);
		}

		return contextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.PrimitiveBoolean} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveBooleanItemProvider primitiveBooleanItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.PrimitiveBoolean}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveBooleanAdapter() {
		if (primitiveBooleanItemProvider == null) {
			primitiveBooleanItemProvider = new PrimitiveBooleanItemProvider(this);
		}

		return primitiveBooleanItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.PrimitiveByte} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveByteItemProvider primitiveByteItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.PrimitiveByte}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveByteAdapter() {
		if (primitiveByteItemProvider == null) {
			primitiveByteItemProvider = new PrimitiveByteItemProvider(this);
		}

		return primitiveByteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.PrimitiveCharacter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveCharacterItemProvider primitiveCharacterItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.PrimitiveCharacter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveCharacterAdapter() {
		if (primitiveCharacterItemProvider == null) {
			primitiveCharacterItemProvider = new PrimitiveCharacterItemProvider(this);
		}

		return primitiveCharacterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.PrimitiveDate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveDateItemProvider primitiveDateItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.PrimitiveDate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveDateAdapter() {
		if (primitiveDateItemProvider == null) {
			primitiveDateItemProvider = new PrimitiveDateItemProvider(this);
		}

		return primitiveDateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.PrimitiveDouble} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveDoubleItemProvider primitiveDoubleItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.PrimitiveDouble}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveDoubleAdapter() {
		if (primitiveDoubleItemProvider == null) {
			primitiveDoubleItemProvider = new PrimitiveDoubleItemProvider(this);
		}

		return primitiveDoubleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.PrimitiveFloat} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveFloatItemProvider primitiveFloatItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.PrimitiveFloat}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveFloatAdapter() {
		if (primitiveFloatItemProvider == null) {
			primitiveFloatItemProvider = new PrimitiveFloatItemProvider(this);
		}

		return primitiveFloatItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.PrimitiveInteger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveIntegerItemProvider primitiveIntegerItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.PrimitiveInteger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveIntegerAdapter() {
		if (primitiveIntegerItemProvider == null) {
			primitiveIntegerItemProvider = new PrimitiveIntegerItemProvider(this);
		}

		return primitiveIntegerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.PrimitiveLong} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveLongItemProvider primitiveLongItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.PrimitiveLong}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveLongAdapter() {
		if (primitiveLongItemProvider == null) {
			primitiveLongItemProvider = new PrimitiveLongItemProvider(this);
		}

		return primitiveLongItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.PrimitiveShort} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveShortItemProvider primitiveShortItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.PrimitiveShort}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveShortAdapter() {
		if (primitiveShortItemProvider == null) {
			primitiveShortItemProvider = new PrimitiveShortItemProvider(this);
		}

		return primitiveShortItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.PrimitiveString} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveStringItemProvider primitiveStringItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.PrimitiveString}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveStringAdapter() {
		if (primitiveStringItemProvider == null) {
			primitiveStringItemProvider = new PrimitiveStringItemProvider(this);
		}

		return primitiveStringItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.PrimitiveUnspecified} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveUnspecifiedItemProvider primitiveUnspecifiedItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.PrimitiveUnspecified}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveUnspecifiedAdapter() {
		if (primitiveUnspecifiedItemProvider == null) {
			primitiveUnspecifiedItemProvider = new PrimitiveUnspecifiedItemProvider(this);
		}

		return primitiveUnspecifiedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.ImportedComplexType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportedComplexTypeItemProvider importedComplexTypeItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.ImportedComplexType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportedComplexTypeAdapter() {
		if (importedComplexTypeItemProvider == null) {
			importedComplexTypeItemProvider = new ImportedComplexTypeItemProvider(this);
		}

		return importedComplexTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.DataStructure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataStructureItemProvider dataStructureItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.DataStructure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataStructureAdapter() {
		if (dataStructureItemProvider == null) {
			dataStructureItemProvider = new DataStructureItemProvider(this);
		}

		return dataStructureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.DataOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataOperationItemProvider dataOperationItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.DataOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataOperationAdapter() {
		if (dataOperationItemProvider == null) {
			dataOperationItemProvider = new DataOperationItemProvider(this);
		}

		return dataOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.DataOperationParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataOperationParameterItemProvider dataOperationParameterItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.DataOperationParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataOperationParameterAdapter() {
		if (dataOperationParameterItemProvider == null) {
			dataOperationParameterItemProvider = new DataOperationParameterItemProvider(this);
		}

		return dataOperationParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.CollectionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CollectionTypeItemProvider collectionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.CollectionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCollectionTypeAdapter() {
		if (collectionTypeItemProvider == null) {
			collectionTypeItemProvider = new CollectionTypeItemProvider(this);
		}

		return collectionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.DataField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataFieldItemProvider dataFieldItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.DataField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataFieldAdapter() {
		if (dataFieldItemProvider == null) {
			dataFieldItemProvider = new DataFieldItemProvider(this);
		}

		return dataFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.Enumeration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumerationItemProvider enumerationItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.Enumeration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumerationAdapter() {
		if (enumerationItemProvider == null) {
			enumerationItemProvider = new EnumerationItemProvider(this);
		}

		return enumerationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.EnumerationField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumerationFieldItemProvider enumerationFieldItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.EnumerationField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumerationFieldAdapter() {
		if (enumerationFieldItemProvider == null) {
			enumerationFieldItemProvider = new EnumerationFieldItemProvider(this);
		}

		return enumerationFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.data.PrimitiveValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrimitiveValueItemProvider primitiveValueItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.data.PrimitiveValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrimitiveValueAdapter() {
		if (primitiveValueItemProvider == null) {
			primitiveValueItemProvider = new PrimitiveValueItemProvider(this);
		}

		return primitiveValueItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (dataModelItemProvider != null) dataModelItemProvider.dispose();
		if (complexTypeImportItemProvider != null) complexTypeImportItemProvider.dispose();
		if (versionItemProvider != null) versionItemProvider.dispose();
		if (contextItemProvider != null) contextItemProvider.dispose();
		if (primitiveBooleanItemProvider != null) primitiveBooleanItemProvider.dispose();
		if (primitiveByteItemProvider != null) primitiveByteItemProvider.dispose();
		if (primitiveCharacterItemProvider != null) primitiveCharacterItemProvider.dispose();
		if (primitiveDateItemProvider != null) primitiveDateItemProvider.dispose();
		if (primitiveDoubleItemProvider != null) primitiveDoubleItemProvider.dispose();
		if (primitiveFloatItemProvider != null) primitiveFloatItemProvider.dispose();
		if (primitiveIntegerItemProvider != null) primitiveIntegerItemProvider.dispose();
		if (primitiveLongItemProvider != null) primitiveLongItemProvider.dispose();
		if (primitiveShortItemProvider != null) primitiveShortItemProvider.dispose();
		if (primitiveStringItemProvider != null) primitiveStringItemProvider.dispose();
		if (primitiveUnspecifiedItemProvider != null) primitiveUnspecifiedItemProvider.dispose();
		if (importedComplexTypeItemProvider != null) importedComplexTypeItemProvider.dispose();
		if (dataStructureItemProvider != null) dataStructureItemProvider.dispose();
		if (dataOperationItemProvider != null) dataOperationItemProvider.dispose();
		if (dataOperationParameterItemProvider != null) dataOperationParameterItemProvider.dispose();
		if (collectionTypeItemProvider != null) collectionTypeItemProvider.dispose();
		if (dataFieldItemProvider != null) dataFieldItemProvider.dispose();
		if (enumerationItemProvider != null) enumerationItemProvider.dispose();
		if (enumerationFieldItemProvider != null) enumerationFieldItemProvider.dispose();
		if (primitiveValueItemProvider != null) primitiveValueItemProvider.dispose();
	}

}
