/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.service.ApiOperationComment;
import lemma.adapted.xcore.service.Parameter;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.ApiParameterComment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ApiParameterCommentValidator {
	boolean validate();

	boolean validateComment(String value);
	boolean validateRequired(boolean value);
	boolean validateReturned(boolean value);
	boolean validateParameter(Parameter value);
	boolean validateOperationComment(ApiOperationComment value);
}
