/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.service.Endpoint;
import lemma.adapted.xcore.service.Import;
import lemma.adapted.xcore.service.ProtocolSpecification;

import lemma.adapted.xcore.technology.DataFormat;
import lemma.adapted.xcore.technology.Protocol;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.ImportedProtocolAndDataFormat}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImportedProtocolAndDataFormatValidator {
	boolean validate();

	boolean validateImport(Import value);
	boolean validateImportedProtocol(Protocol value);
	boolean validateDataFormat(DataFormat value);
	boolean validateSpecification(ProtocolSpecification value);
	boolean validateEndpoint(Endpoint value);
}
