/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.service.Import;
import lemma.adapted.xcore.service.ImportedServiceAspect;
import lemma.adapted.xcore.service.ImportedType;
import lemma.adapted.xcore.service.MappedDataOperation;
import lemma.adapted.xcore.service.MappedField;
import lemma.adapted.xcore.service.ServiceModel;
import lemma.adapted.xcore.service.TechnologyReference;

import lemma.adapted.xcore.technology.Technology;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.MappedComplexType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MappedComplexTypeValidator {
	boolean validate();

	boolean validateT_sourceModelUri(String value);
	boolean validateT_mappingModelUri(String value);
	boolean validateT_typeDefinitionTechnologyImport(Import value);
	boolean validateT_typeDefinitionTechnology(Technology value);
	boolean validateTechnologyReferences(EList<TechnologyReference> value);
	boolean validateType(ImportedType value);
	boolean validateMappedFields(EList<MappedField> value);
	boolean validateMappedOperations(EList<MappedDataOperation> value);
	boolean validateAspects(EList<ImportedServiceAspect> value);
	boolean validateServiceModel(ServiceModel value);
}
