/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.data.DataOperation;

import lemma.adapted.xcore.service.ImportedServiceAspect;
import lemma.adapted.xcore.service.MappedComplexType;
import lemma.adapted.xcore.service.MappedDataOperationParameter;
import lemma.adapted.xcore.service.MappedDataOperationReturnType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.MappedDataOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MappedDataOperationValidator {
	boolean validate();

	boolean validateDataOperation(DataOperation value);
	boolean validateAspects(EList<ImportedServiceAspect> value);
	boolean validateMappedReturnType(MappedDataOperationReturnType value);
	boolean validateMappedParameters(EList<MappedDataOperationParameter> value);
	boolean validateMappedComplexType(MappedComplexType value);
}
