/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.data.DataOperationParameter;

import lemma.adapted.xcore.service.ImportedServiceAspect;
import lemma.adapted.xcore.service.ImportedType;
import lemma.adapted.xcore.service.MappedDataOperation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.MappedDataOperationParameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MappedDataOperationParameterValidator {
	boolean validate();

	boolean validateParameter(DataOperationParameter value);
	boolean validateMappedType(ImportedType value);
	boolean validateAspects(EList<ImportedServiceAspect> value);
	boolean validateMappedOperation(MappedDataOperation value);
}
