/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.service.ApiOperationComment;
import lemma.adapted.xcore.service.Endpoint;
import lemma.adapted.xcore.service.ImportedServiceAspect;
import lemma.adapted.xcore.service.Interface;
import lemma.adapted.xcore.service.OperationType;
import lemma.adapted.xcore.service.Parameter;
import lemma.adapted.xcore.service.ProtocolSpecification;
import lemma.adapted.xcore.service.Visibility;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.Operation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperationValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateToExpose(boolean value);

	boolean validateNotImplemented(boolean value);
	boolean validateVisibility(Visibility value);
	boolean validateOperationType(OperationType value);
	boolean validateApiOperationComment(ApiOperationComment value);
	boolean validateEndpoints(EList<Endpoint> value);
	boolean validateProtocols(EList<ProtocolSpecification> value);
	boolean validateParameters(EList<Parameter> value);
	boolean validateAspects(EList<ImportedServiceAspect> value);
	boolean validateInterface(Interface value);
	boolean validateNotImplementedByContainer(boolean value);
	boolean validateEffectivelyNotImplemented(boolean value);
	boolean validateEffectiveVisibility(Visibility value);
	boolean validateEffectivelyInternal(boolean value);
}
