/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.service.ImportedProtocolAndDataFormat;

import lemma.adapted.xcore.technology.CommunicationType;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.ProtocolSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProtocolSpecificationValidator {
	boolean validate();

	boolean validateCommunicationType(CommunicationType value);
	boolean validateProtocol(ImportedProtocolAndDataFormat value);
}
