/**
 *
 * $Id$
 */
package lemma.adapted.xcore.data.validation;

import lemma.adapted.xcore.data.ComplexTypeFeature;
import lemma.adapted.xcore.data.Context;
import lemma.adapted.xcore.data.DataModel;
import lemma.adapted.xcore.data.Version;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.data.ComplexType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComplexTypeValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateFeatures(EList<ComplexTypeFeature> value);
	boolean validateDataModel(DataModel value);
	boolean validateVersion(Version value);
	boolean validateContext(Context value);
	boolean validateIsStructure(boolean value);
	boolean validateIsPrimitiveCollection(boolean value);
	boolean validateIsStructuredCollection(boolean value);
	boolean validateIsEnumeration(boolean value);
}
