/**
 *
 * $Id$
 */
package lemma.adapted.xcore.data.validation;

import lemma.adapted.xcore.data.CollectionType;
import lemma.adapted.xcore.data.ComplexType;
import lemma.adapted.xcore.data.DataFieldFeature;
import lemma.adapted.xcore.data.DataStructure;
import lemma.adapted.xcore.data.ImportedComplexType;
import lemma.adapted.xcore.data.PrimitiveType;
import lemma.adapted.xcore.data.PrimitiveValue;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.data.DataField}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataFieldValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateHidden(boolean value);
	boolean validateImmutable(boolean value);
	boolean validateLowerBound(Integer value);
	boolean validateUpperBound(Integer value);
	boolean validateComplexType(ComplexType value);
	boolean validateImportedComplexType(ImportedComplexType value);
	boolean validatePrimitiveType(PrimitiveType value);
	boolean validateInitializationValue(PrimitiveValue value);
	boolean validateFeatures(EList<DataFieldFeature> value);
	boolean validateDataStructure(DataStructure value);
	boolean validateCollectionType(CollectionType value);
}
