/**
 *
 * $Id$
 */
package lemma.adapted.xcore.behavior.validation;

import lemma.adapted.xcore.behavior.ActivityGroup;
import lemma.adapted.xcore.behavior.ParameterMapping;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.behavior.Activity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityValidator {
	boolean validate();

	boolean validateToTransform(Boolean value);
	boolean validateOwnedParameters(EList<Object> value);
	boolean validateParameterMappings(EList<ParameterMapping> value);
	boolean validateRoot(ActivityGroup value);
}
