/**
 *
 * $Id$
 */
package lemma.adapted.xcore.behavior.validation;

import lemma.adapted.xcore.behavior.Activity;
import lemma.adapted.xcore.behavior.ActivityEdge;
import lemma.adapted.xcore.behavior.ActivityNode;
import lemma.adapted.xcore.behavior.ConditionalNode;
import lemma.adapted.xcore.behavior.Scope;
import lemma.adapted.xcore.behavior.StructuredActivityNode;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.behavior.ActivityGroup}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityGroupValidator {
	boolean validate();

	boolean validateOwnedNodes(EList<ActivityNode> value);
	boolean validateOwnedEdges(EList<ActivityEdge> value);
	boolean validateScope(Scope value);
	boolean validateActivity(Activity value);
	boolean validateStructuredActivityNode(StructuredActivityNode value);
	boolean validateConditionalNode(ConditionalNode value);
}
