/**
 *
 * $Id$
 */
package lemma.adapted.xcore.behavior.validation;

import lemma.adapted.xcore.data.DataOperationParameter;


/**
 * A sample validator interface for {@link lemma.adapted.xcore.behavior.ImportedDataParameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImportedDataParameterValidator {
	boolean validate();

	boolean validateParameter(DataOperationParameter value);

	boolean validateParameter(Object value);
}
