/**
 *
 * $Id$
 */
package lemma.adapted.xcore.behavior.validation;

import lemma.adapted.xcore.behavior.ActivityGroup;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.behavior.LoopNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LoopNodeValidator {
	boolean validate();

	boolean validateSetup(ActivityGroup value);
}
