/**
 *
 * $Id$
 */
package lemma.adapted.xcore.behavior.validation;

import lemma.adapted.xcore.behavior.Activity;
import lemma.adapted.xcore.behavior.CallOperationAction;
import lemma.adapted.xcore.behavior.Identifier;
import lemma.adapted.xcore.behavior.ImportedParameter;
import lemma.adapted.xcore.behavior.ParameterMappingType;
import lemma.adapted.xcore.behavior.Variable;
import lemma.adapted.xcore.data.ValueSpecification;
import lemma.adapted.xcore.service.Parameter;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.behavior.ParameterMapping}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParameterMappingValidator {
	boolean validate();

	boolean validateType(ParameterMappingType value);
	boolean validateOperationParameter(ImportedParameter value);
	boolean validateIdentifier(Identifier value);
	boolean validateVariable(Variable value);
	boolean validateActivityParameter(Parameter value);

	boolean validateValue(ValueSpecification value);

	boolean validateActivityParameter(Object value);
	boolean validateValue(Object value);
	boolean validateAction(CallOperationAction value);
	boolean validateActivity(Activity value);
}
