/**
 *
 * $Id$
 */
package lemma.adapted.xcore.behavior.validation;

import lemma.adapted.xcore.data.ValueSpecification;
import lemma.adapted.xcore.service.ImportedType;


/**
 * A sample validator interface for {@link lemma.adapted.xcore.behavior.TypedMultiplicityElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TypedMultiplicityElementValidator {
	boolean validate();

	boolean validateDefault(ValueSpecification value);

	boolean validateType(ImportedType value);

	boolean validateDefault(Object value);
	boolean validateType(Object value);
	boolean validateUpperBound(Integer value);
	boolean validateLowerBound(Integer value);
}
