/**
 *
 * $Id$
 */
package lemma.adapted.xcore.behavior.validation;

import lemma.adapted.xcore.behavior.VariableAssignment;
import lemma.adapted.xcore.data.PrimitiveType;
import lemma.adapted.xcore.service.ImportedType;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.behavior.VariableDeclarationAction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VariableDeclarationActionValidator {
	boolean validate();

	boolean validateLowerBound(Integer value);
	boolean validateUpperBound(Integer value);
	boolean validateImportedType(ImportedType value);

	boolean validatePrimitiveType(PrimitiveType value);

	boolean validateImportedType(Object value);
	boolean validatePrimitiveType(Object value);
	boolean validateDeclaration(VariableAssignment value);
}
