/*
 * generated by Xtext 2.43.0
 */
package dact.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ExprDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.Expression");
		private final RuleCall cAssignmentExpressionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//// Root entry point
		//Expression returns dact::Expression:
		//    AssignmentExpression;
		@Override public ParserRule getRule() { return rule; }
		
		//AssignmentExpression
		public RuleCall getAssignmentExpressionParserRuleCall() { return cAssignmentExpressionParserRuleCall; }
	}
	public class AssignmentExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.AssignmentExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cVariableAssignmentAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cIdentifierAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cIdentifierIdentifierParserRuleCall_0_1_0 = (RuleCall)cIdentifierAssignment_0_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cExprAssignment_0_3 = (Assignment)cGroup_0.eContents().get(3);
		private final RuleCall cExprAssignmentExpressionParserRuleCall_0_3_0 = (RuleCall)cExprAssignment_0_3.eContents().get(0);
		private final RuleCall cOrExpressionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//// -----------------------------------------------------------
		//// Operator Precedence Cascade
		//// -----------------------------------------------------------
		//AssignmentExpression returns dact::Expression:
		//    {dact::VariableAssignment} identifier=Identifier '=' expr=AssignmentExpression
		//  | OrExpression;
		@Override public ParserRule getRule() { return rule; }
		
		//  {dact::VariableAssignment} identifier=Identifier '=' expr=AssignmentExpression
		//| OrExpression
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{dact::VariableAssignment} identifier=Identifier '=' expr=AssignmentExpression
		public Group getGroup_0() { return cGroup_0; }
		
		//{dact::VariableAssignment}
		public Action getVariableAssignmentAction_0_0() { return cVariableAssignmentAction_0_0; }
		
		//identifier=Identifier
		public Assignment getIdentifierAssignment_0_1() { return cIdentifierAssignment_0_1; }
		
		//Identifier
		public RuleCall getIdentifierIdentifierParserRuleCall_0_1_0() { return cIdentifierIdentifierParserRuleCall_0_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_0_2() { return cEqualsSignKeyword_0_2; }
		
		//expr=AssignmentExpression
		public Assignment getExprAssignment_0_3() { return cExprAssignment_0_3; }
		
		//AssignmentExpression
		public RuleCall getExprAssignmentExpressionParserRuleCall_0_3_0() { return cExprAssignmentExpressionParserRuleCall_0_3_0; }
		
		//OrExpression
		public RuleCall getOrExpressionParserRuleCall_1() { return cOrExpressionParserRuleCall_1; }
	}
	public class OrExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.OrExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAndExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryExpressionLeftExprAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorOrOperatorParserRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightExprAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightExprAndExpressionParserRuleCall_1_2_0 = (RuleCall)cRightExprAssignment_1_2.eContents().get(0);
		
		//OrExpression returns dact::Expression:
		//    AndExpression (
		//        {dact::BinaryExpression.leftExpr=current}
		//        operator=OrOperator
		//        rightExpr=AndExpression
		//    )*;
		@Override public ParserRule getRule() { return rule; }
		
		//AndExpression (
		//    {dact::BinaryExpression.leftExpr=current}
		//    operator=OrOperator
		//    rightExpr=AndExpression
		//)*
		public Group getGroup() { return cGroup; }
		
		//AndExpression
		public RuleCall getAndExpressionParserRuleCall_0() { return cAndExpressionParserRuleCall_0; }
		
		//(
		//       {dact::BinaryExpression.leftExpr=current}
		//       operator=OrOperator
		//       rightExpr=AndExpression
		//   )*
		public Group getGroup_1() { return cGroup_1; }
		
		//{dact::BinaryExpression.leftExpr=current}
		public Action getBinaryExpressionLeftExprAction_1_0() { return cBinaryExpressionLeftExprAction_1_0; }
		
		//operator=OrOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }
		
		//OrOperator
		public RuleCall getOperatorOrOperatorParserRuleCall_1_1_0() { return cOperatorOrOperatorParserRuleCall_1_1_0; }
		
		//rightExpr=AndExpression
		public Assignment getRightExprAssignment_1_2() { return cRightExprAssignment_1_2; }
		
		//AndExpression
		public RuleCall getRightExprAndExpressionParserRuleCall_1_2_0() { return cRightExprAndExpressionParserRuleCall_1_2_0; }
	}
	public class OrOperatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.OrOperator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOrAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cVerticalLineVerticalLineKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cORKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Keyword cOrKeyword_1_2 = (Keyword)cAlternatives_1.eContents().get(2);
		
		//OrOperator returns dact::Operator:
		//    {dact::Or} ('||' | 'OR' | 'or');
		@Override public ParserRule getRule() { return rule; }
		
		//{dact::Or} ('||' | 'OR' | 'or')
		public Group getGroup() { return cGroup; }
		
		//{dact::Or}
		public Action getOrAction_0() { return cOrAction_0; }
		
		//('||' | 'OR' | 'or')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'||'
		public Keyword getVerticalLineVerticalLineKeyword_1_0() { return cVerticalLineVerticalLineKeyword_1_0; }
		
		//'OR'
		public Keyword getORKeyword_1_1() { return cORKeyword_1_1; }
		
		//'or'
		public Keyword getOrKeyword_1_2() { return cOrKeyword_1_2; }
	}
	public class AndExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.AndExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cComparisonExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryExpressionLeftExprAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorAndOperatorParserRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightExprAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightExprComparisonExpressionParserRuleCall_1_2_0 = (RuleCall)cRightExprAssignment_1_2.eContents().get(0);
		
		//AndExpression returns dact::Expression:
		//    ComparisonExpression (
		//        {dact::BinaryExpression.leftExpr=current}
		//        operator=AndOperator
		//        rightExpr=ComparisonExpression
		//    )*;
		@Override public ParserRule getRule() { return rule; }
		
		//ComparisonExpression (
		//    {dact::BinaryExpression.leftExpr=current}
		//    operator=AndOperator
		//    rightExpr=ComparisonExpression
		//)*
		public Group getGroup() { return cGroup; }
		
		//ComparisonExpression
		public RuleCall getComparisonExpressionParserRuleCall_0() { return cComparisonExpressionParserRuleCall_0; }
		
		//(
		//       {dact::BinaryExpression.leftExpr=current}
		//       operator=AndOperator
		//       rightExpr=ComparisonExpression
		//   )*
		public Group getGroup_1() { return cGroup_1; }
		
		//{dact::BinaryExpression.leftExpr=current}
		public Action getBinaryExpressionLeftExprAction_1_0() { return cBinaryExpressionLeftExprAction_1_0; }
		
		//operator=AndOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }
		
		//AndOperator
		public RuleCall getOperatorAndOperatorParserRuleCall_1_1_0() { return cOperatorAndOperatorParserRuleCall_1_1_0; }
		
		//rightExpr=ComparisonExpression
		public Assignment getRightExprAssignment_1_2() { return cRightExprAssignment_1_2; }
		
		//ComparisonExpression
		public RuleCall getRightExprComparisonExpressionParserRuleCall_1_2_0() { return cRightExprComparisonExpressionParserRuleCall_1_2_0; }
	}
	public class AndOperatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.AndOperator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAndAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cAmpersandAmpersandKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cANDKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Keyword cAndKeyword_1_2 = (Keyword)cAlternatives_1.eContents().get(2);
		
		//AndOperator returns dact::Operator:
		//    {dact::And} ('&&' | 'AND' | 'and');
		@Override public ParserRule getRule() { return rule; }
		
		//{dact::And} ('&&' | 'AND' | 'and')
		public Group getGroup() { return cGroup; }
		
		//{dact::And}
		public Action getAndAction_0() { return cAndAction_0; }
		
		//('&&' | 'AND' | 'and')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'&&'
		public Keyword getAmpersandAmpersandKeyword_1_0() { return cAmpersandAmpersandKeyword_1_0; }
		
		//'AND'
		public Keyword getANDKeyword_1_1() { return cANDKeyword_1_1; }
		
		//'and'
		public Keyword getAndKeyword_1_2() { return cAndKeyword_1_2; }
	}
	public class ComparisonExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.ComparisonExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAdditiveExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryExpressionLeftExprAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorComparisonOperatorParserRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightExprAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightExprAdditiveExpressionParserRuleCall_1_2_0 = (RuleCall)cRightExprAssignment_1_2.eContents().get(0);
		
		//ComparisonExpression returns dact::Expression:
		//    AdditiveExpression (
		//        {dact::BinaryExpression.leftExpr=current}
		//        operator=ComparisonOperator
		//        rightExpr=AdditiveExpression
		//    )*;
		@Override public ParserRule getRule() { return rule; }
		
		//AdditiveExpression (
		//    {dact::BinaryExpression.leftExpr=current}
		//    operator=ComparisonOperator
		//    rightExpr=AdditiveExpression
		//)*
		public Group getGroup() { return cGroup; }
		
		//AdditiveExpression
		public RuleCall getAdditiveExpressionParserRuleCall_0() { return cAdditiveExpressionParserRuleCall_0; }
		
		//(
		//       {dact::BinaryExpression.leftExpr=current}
		//       operator=ComparisonOperator
		//       rightExpr=AdditiveExpression
		//   )*
		public Group getGroup_1() { return cGroup_1; }
		
		//{dact::BinaryExpression.leftExpr=current}
		public Action getBinaryExpressionLeftExprAction_1_0() { return cBinaryExpressionLeftExprAction_1_0; }
		
		//operator=ComparisonOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }
		
		//ComparisonOperator
		public RuleCall getOperatorComparisonOperatorParserRuleCall_1_1_0() { return cOperatorComparisonOperatorParserRuleCall_1_1_0; }
		
		//rightExpr=AdditiveExpression
		public Assignment getRightExprAssignment_1_2() { return cRightExprAssignment_1_2; }
		
		//AdditiveExpression
		public RuleCall getRightExprAdditiveExpressionParserRuleCall_1_2_0() { return cRightExprAdditiveExpressionParserRuleCall_1_2_0; }
	}
	public class ComparisonOperatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.ComparisonOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cGtAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cGeAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cGreaterThanSignEqualsSignKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cLtAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Keyword cLessThanSignKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cLeAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Keyword cLessThanSignEqualsSignKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Action cEqAction_4_0 = (Action)cGroup_4.eContents().get(0);
		private final Keyword cEqualsSignEqualsSignKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Action cNeAction_5_0 = (Action)cGroup_5.eContents().get(0);
		private final Keyword cExclamationMarkEqualsSignKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		
		//ComparisonOperator returns dact::Operator:
		//    {dact::Gt} '>'  |
		//    {dact::Ge} '>=' |
		//    {dact::Lt} '<'  |
		//    {dact::Le} '<=' |
		//    {dact::Eq} '==' |
		//    {dact::Ne} '!=';
		@Override public ParserRule getRule() { return rule; }
		
		//{dact::Gt} '>'  |
		//{dact::Ge} '>=' |
		//{dact::Lt} '<'  |
		//{dact::Le} '<=' |
		//{dact::Eq} '==' |
		//{dact::Ne} '!='
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{dact::Gt} '>'
		public Group getGroup_0() { return cGroup_0; }
		
		//{dact::Gt}
		public Action getGtAction_0_0() { return cGtAction_0_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_0_1() { return cGreaterThanSignKeyword_0_1; }
		
		//{dact::Ge} '>='
		public Group getGroup_1() { return cGroup_1; }
		
		//{dact::Ge}
		public Action getGeAction_1_0() { return cGeAction_1_0; }
		
		//'>='
		public Keyword getGreaterThanSignEqualsSignKeyword_1_1() { return cGreaterThanSignEqualsSignKeyword_1_1; }
		
		//{dact::Lt} '<'
		public Group getGroup_2() { return cGroup_2; }
		
		//{dact::Lt}
		public Action getLtAction_2_0() { return cLtAction_2_0; }
		
		//'<'
		public Keyword getLessThanSignKeyword_2_1() { return cLessThanSignKeyword_2_1; }
		
		//{dact::Le} '<='
		public Group getGroup_3() { return cGroup_3; }
		
		//{dact::Le}
		public Action getLeAction_3_0() { return cLeAction_3_0; }
		
		//'<='
		public Keyword getLessThanSignEqualsSignKeyword_3_1() { return cLessThanSignEqualsSignKeyword_3_1; }
		
		//{dact::Eq} '=='
		public Group getGroup_4() { return cGroup_4; }
		
		//{dact::Eq}
		public Action getEqAction_4_0() { return cEqAction_4_0; }
		
		//'=='
		public Keyword getEqualsSignEqualsSignKeyword_4_1() { return cEqualsSignEqualsSignKeyword_4_1; }
		
		//{dact::Ne} '!='
		public Group getGroup_5() { return cGroup_5; }
		
		//{dact::Ne}
		public Action getNeAction_5_0() { return cNeAction_5_0; }
		
		//'!='
		public Keyword getExclamationMarkEqualsSignKeyword_5_1() { return cExclamationMarkEqualsSignKeyword_5_1; }
	}
	public class AdditiveExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.AdditiveExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cInExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryExpressionLeftExprAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorAdditiveOperatorParserRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightExprAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightExprInExpressionParserRuleCall_1_2_0 = (RuleCall)cRightExprAssignment_1_2.eContents().get(0);
		
		//AdditiveExpression returns dact::Expression:
		//    InExpression (
		//        {dact::BinaryExpression.leftExpr=current}
		//        operator=AdditiveOperator
		//        rightExpr=InExpression
		//    )*;
		@Override public ParserRule getRule() { return rule; }
		
		//InExpression (
		//    {dact::BinaryExpression.leftExpr=current}
		//    operator=AdditiveOperator
		//    rightExpr=InExpression
		//)*
		public Group getGroup() { return cGroup; }
		
		//InExpression
		public RuleCall getInExpressionParserRuleCall_0() { return cInExpressionParserRuleCall_0; }
		
		//(
		//       {dact::BinaryExpression.leftExpr=current}
		//       operator=AdditiveOperator
		//       rightExpr=InExpression
		//   )*
		public Group getGroup_1() { return cGroup_1; }
		
		//{dact::BinaryExpression.leftExpr=current}
		public Action getBinaryExpressionLeftExprAction_1_0() { return cBinaryExpressionLeftExprAction_1_0; }
		
		//operator=AdditiveOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }
		
		//AdditiveOperator
		public RuleCall getOperatorAdditiveOperatorParserRuleCall_1_1_0() { return cOperatorAdditiveOperatorParserRuleCall_1_1_0; }
		
		//rightExpr=InExpression
		public Assignment getRightExprAssignment_1_2() { return cRightExprAssignment_1_2; }
		
		//InExpression
		public RuleCall getRightExprInExpressionParserRuleCall_1_2_0() { return cRightExprInExpressionParserRuleCall_1_2_0; }
	}
	public class AdditiveOperatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.AdditiveOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cPlusAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cPlusSignKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cMinusAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//AdditiveOperator returns dact::Operator:
		//    {dact::Plus} '+' |
		//    {dact::Minus} '-';
		@Override public ParserRule getRule() { return rule; }
		
		//{dact::Plus} '+' |
		//{dact::Minus} '-'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{dact::Plus} '+'
		public Group getGroup_0() { return cGroup_0; }
		
		//{dact::Plus}
		public Action getPlusAction_0_0() { return cPlusAction_0_0; }
		
		//'+'
		public Keyword getPlusSignKeyword_0_1() { return cPlusSignKeyword_0_1; }
		
		//{dact::Minus} '-'
		public Group getGroup_1() { return cGroup_1; }
		
		//{dact::Minus}
		public Action getMinusAction_1_0() { return cMinusAction_1_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1_1() { return cHyphenMinusKeyword_1_1; }
	}
	public class InExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.InExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cMultiplicativeExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryExpressionLeftExprAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorInOperatorParserRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightExprAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightExprMultiplicativeExpressionParserRuleCall_1_2_0 = (RuleCall)cRightExprAssignment_1_2.eContents().get(0);
		
		//InExpression returns dact::Expression:
		//    MultiplicativeExpression (
		//        {dact::BinaryExpression.leftExpr=current}
		//        operator=InOperator
		//        rightExpr=MultiplicativeExpression
		//    )*;
		@Override public ParserRule getRule() { return rule; }
		
		//MultiplicativeExpression (
		//    {dact::BinaryExpression.leftExpr=current}
		//    operator=InOperator
		//    rightExpr=MultiplicativeExpression
		//)*
		public Group getGroup() { return cGroup; }
		
		//MultiplicativeExpression
		public RuleCall getMultiplicativeExpressionParserRuleCall_0() { return cMultiplicativeExpressionParserRuleCall_0; }
		
		//(
		//       {dact::BinaryExpression.leftExpr=current}
		//       operator=InOperator
		//       rightExpr=MultiplicativeExpression
		//   )*
		public Group getGroup_1() { return cGroup_1; }
		
		//{dact::BinaryExpression.leftExpr=current}
		public Action getBinaryExpressionLeftExprAction_1_0() { return cBinaryExpressionLeftExprAction_1_0; }
		
		//operator=InOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }
		
		//InOperator
		public RuleCall getOperatorInOperatorParserRuleCall_1_1_0() { return cOperatorInOperatorParserRuleCall_1_1_0; }
		
		//rightExpr=MultiplicativeExpression
		public Assignment getRightExprAssignment_1_2() { return cRightExprAssignment_1_2; }
		
		//MultiplicativeExpression
		public RuleCall getRightExprMultiplicativeExpressionParserRuleCall_1_2_0() { return cRightExprMultiplicativeExpressionParserRuleCall_1_2_0; }
	}
	public class InOperatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.InOperator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cINKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cInKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Keyword cInKeyword_1_2 = (Keyword)cAlternatives_1.eContents().get(2);
		
		//InOperator returns dact::Operator:
		//    {dact::In} ('IN' | 'in' | 'In');
		@Override public ParserRule getRule() { return rule; }
		
		//{dact::In} ('IN' | 'in' | 'In')
		public Group getGroup() { return cGroup; }
		
		//{dact::In}
		public Action getInAction_0() { return cInAction_0; }
		
		//('IN' | 'in' | 'In')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'IN'
		public Keyword getINKeyword_1_0() { return cINKeyword_1_0; }
		
		//'in'
		public Keyword getInKeyword_1_1() { return cInKeyword_1_1; }
		
		//'In'
		public Keyword getInKeyword_1_2() { return cInKeyword_1_2; }
	}
	public class MultiplicativeExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.MultiplicativeExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cUnaryExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cBinaryExpressionLeftExprAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cOperatorMultiplicativeOperatorParserRuleCall_1_1_0 = (RuleCall)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cRightExprAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightExprUnaryExpressionParserRuleCall_1_2_0 = (RuleCall)cRightExprAssignment_1_2.eContents().get(0);
		
		//MultiplicativeExpression returns dact::Expression:
		//    UnaryExpression (
		//        {dact::BinaryExpression.leftExpr=current}
		//        operator=MultiplicativeOperator
		//        rightExpr=UnaryExpression
		//    )*;
		@Override public ParserRule getRule() { return rule; }
		
		//UnaryExpression (
		//    {dact::BinaryExpression.leftExpr=current}
		//    operator=MultiplicativeOperator
		//    rightExpr=UnaryExpression
		//)*
		public Group getGroup() { return cGroup; }
		
		//UnaryExpression
		public RuleCall getUnaryExpressionParserRuleCall_0() { return cUnaryExpressionParserRuleCall_0; }
		
		//(
		//       {dact::BinaryExpression.leftExpr=current}
		//       operator=MultiplicativeOperator
		//       rightExpr=UnaryExpression
		//   )*
		public Group getGroup_1() { return cGroup_1; }
		
		//{dact::BinaryExpression.leftExpr=current}
		public Action getBinaryExpressionLeftExprAction_1_0() { return cBinaryExpressionLeftExprAction_1_0; }
		
		//operator=MultiplicativeOperator
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }
		
		//MultiplicativeOperator
		public RuleCall getOperatorMultiplicativeOperatorParserRuleCall_1_1_0() { return cOperatorMultiplicativeOperatorParserRuleCall_1_1_0; }
		
		//rightExpr=UnaryExpression
		public Assignment getRightExprAssignment_1_2() { return cRightExprAssignment_1_2; }
		
		//UnaryExpression
		public RuleCall getRightExprUnaryExpressionParserRuleCall_1_2_0() { return cRightExprUnaryExpressionParserRuleCall_1_2_0; }
	}
	public class MultiplicativeOperatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.MultiplicativeOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cTimesAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cAsteriskKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cDivideAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cSolidusKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//MultiplicativeOperator returns dact::Operator:
		//    {dact::Times} '*' |
		//    {dact::Divide} '/';
		@Override public ParserRule getRule() { return rule; }
		
		//{dact::Times} '*' |
		//{dact::Divide} '/'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{dact::Times} '*'
		public Group getGroup_0() { return cGroup_0; }
		
		//{dact::Times}
		public Action getTimesAction_0_0() { return cTimesAction_0_0; }
		
		//'*'
		public Keyword getAsteriskKeyword_0_1() { return cAsteriskKeyword_0_1; }
		
		//{dact::Divide} '/'
		public Group getGroup_1() { return cGroup_1; }
		
		//{dact::Divide}
		public Action getDivideAction_1_0() { return cDivideAction_1_0; }
		
		//'/'
		public Keyword getSolidusKeyword_1_1() { return cSolidusKeyword_1_1; }
	}
	public class UnaryExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.UnaryExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cNotExpressionAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Alternatives cAlternatives_0_1 = (Alternatives)cGroup_0.eContents().get(1);
		private final Keyword cExclamationMarkKeyword_0_1_0 = (Keyword)cAlternatives_0_1.eContents().get(0);
		private final Keyword cNOTKeyword_0_1_1 = (Keyword)cAlternatives_0_1.eContents().get(1);
		private final Keyword cNotKeyword_0_1_2 = (Keyword)cAlternatives_0_1.eContents().get(2);
		private final Assignment cExprAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cExprPrimaryExpressionParserRuleCall_0_2_0 = (RuleCall)cExprAssignment_0_2.eContents().get(0);
		private final RuleCall cPrimaryExpressionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//UnaryExpression returns dact::Expression:
		//    {dact::NotExpression} ( '!' | 'NOT' | 'not') expr=PrimaryExpression
		//  | PrimaryExpression;
		@Override public ParserRule getRule() { return rule; }
		
		//  {dact::NotExpression} ( '!' | 'NOT' | 'not') expr=PrimaryExpression
		//| PrimaryExpression
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{dact::NotExpression} ( '!' | 'NOT' | 'not') expr=PrimaryExpression
		public Group getGroup_0() { return cGroup_0; }
		
		//{dact::NotExpression}
		public Action getNotExpressionAction_0_0() { return cNotExpressionAction_0_0; }
		
		//( '!' | 'NOT' | 'not')
		public Alternatives getAlternatives_0_1() { return cAlternatives_0_1; }
		
		//'!'
		public Keyword getExclamationMarkKeyword_0_1_0() { return cExclamationMarkKeyword_0_1_0; }
		
		//'NOT'
		public Keyword getNOTKeyword_0_1_1() { return cNOTKeyword_0_1_1; }
		
		//'not'
		public Keyword getNotKeyword_0_1_2() { return cNotKeyword_0_1_2; }
		
		//expr=PrimaryExpression
		public Assignment getExprAssignment_0_2() { return cExprAssignment_0_2; }
		
		//PrimaryExpression
		public RuleCall getExprPrimaryExpressionParserRuleCall_0_2_0() { return cExprPrimaryExpressionParserRuleCall_0_2_0; }
		
		//PrimaryExpression
		public RuleCall getPrimaryExpressionParserRuleCall_1() { return cPrimaryExpressionParserRuleCall_1; }
	}
	public class PrimaryExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.PrimaryExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLiteralRealParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLiteralIntegerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cLiteralStringParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cLiteralBooleanParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cLiteralNullParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cLiteralEnumParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cPropertyAccessParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final Group cGroup_7 = (Group)cAlternatives.eContents().get(7);
		private final Keyword cLeftParenthesisKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final RuleCall cAssignmentExpressionParserRuleCall_7_1 = (RuleCall)cGroup_7.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_7_2 = (Keyword)cGroup_7.eContents().get(2);
		
		//// Level 7: Primary Expressions & Literals
		//PrimaryExpression returns dact::Expression:
		//    LiteralReal      // Must come before LiteralInteger so floats like 3.14 don't stop at '3'
		//  | LiteralInteger
		//  | LiteralString
		//  | LiteralBoolean
		//  | LiteralNull
		//  | LiteralEnum
		//  | PropertyAccess
		//  | '(' AssignmentExpression ')'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//  LiteralReal      // Must come before LiteralInteger so floats like 3.14 don't stop at '3'
		//| LiteralInteger
		//| LiteralString
		//| LiteralBoolean
		//| LiteralNull
		//| LiteralEnum
		//| PropertyAccess
		//| '(' AssignmentExpression ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//LiteralReal
		public RuleCall getLiteralRealParserRuleCall_0() { return cLiteralRealParserRuleCall_0; }
		
		//LiteralInteger
		public RuleCall getLiteralIntegerParserRuleCall_1() { return cLiteralIntegerParserRuleCall_1; }
		
		//LiteralString
		public RuleCall getLiteralStringParserRuleCall_2() { return cLiteralStringParserRuleCall_2; }
		
		//LiteralBoolean
		public RuleCall getLiteralBooleanParserRuleCall_3() { return cLiteralBooleanParserRuleCall_3; }
		
		//LiteralNull
		public RuleCall getLiteralNullParserRuleCall_4() { return cLiteralNullParserRuleCall_4; }
		
		//LiteralEnum
		public RuleCall getLiteralEnumParserRuleCall_5() { return cLiteralEnumParserRuleCall_5; }
		
		//PropertyAccess
		public RuleCall getPropertyAccessParserRuleCall_6() { return cPropertyAccessParserRuleCall_6; }
		
		//'(' AssignmentExpression ')'
		public Group getGroup_7() { return cGroup_7; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_7_0() { return cLeftParenthesisKeyword_7_0; }
		
		//AssignmentExpression
		public RuleCall getAssignmentExpressionParserRuleCall_7_1() { return cAssignmentExpressionParserRuleCall_7_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7_2() { return cRightParenthesisKeyword_7_2; }
	}
	public class LiteralRealElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.LiteralReal");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueRealSpecificationParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//// -----------------------------------------------------------
		//// Leaf Terminals & Literals
		//// -----------------------------------------------------------
		//// REAL / FLOAT LITERAL (e.g., 3.14, -0.05, 10.0)
		//LiteralReal returns dact::UnaryExpression:
		//    value=RealSpecification;
		@Override public ParserRule getRule() { return rule; }
		
		//value=RealSpecification
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//RealSpecification
		public RuleCall getValueRealSpecificationParserRuleCall_0() { return cValueRealSpecificationParserRuleCall_0; }
	}
	public class RealSpecificationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.RealSpecification");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueEDoubleObjectParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//RealSpecification returns dact::LiteralReal:
		//    value=EDoubleObject;
		@Override public ParserRule getRule() { return rule; }
		
		//value=EDoubleObject
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//EDoubleObject
		public RuleCall getValueEDoubleObjectParserRuleCall_0() { return cValueEDoubleObjectParserRuleCall_0; }
	}
	public class EDoubleObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.EDoubleObject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//EDoubleObject returns ecore::EDoubleObject:
		//    '-'? INT '.' INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT '.' INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
	}
	public class LiteralIntegerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.LiteralInteger");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueIntegerSpecificationParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//// INTEGER LITERAL (e.g., 42, -7)
		//LiteralInteger returns dact::UnaryExpression:
		//    value=IntegerSpecification;
		@Override public ParserRule getRule() { return rule; }
		
		//value=IntegerSpecification
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//IntegerSpecification
		public RuleCall getValueIntegerSpecificationParserRuleCall_0() { return cValueIntegerSpecificationParserRuleCall_0; }
	}
	public class IntegerSpecificationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.IntegerSpecification");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueEIntegerObjectParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//IntegerSpecification returns dact::LiteralInteger:
		//    value=EIntegerObject;
		@Override public ParserRule getRule() { return rule; }
		
		//value=EIntegerObject
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//EIntegerObject
		public RuleCall getValueEIntegerObjectParserRuleCall_0() { return cValueEIntegerObjectParserRuleCall_0; }
	}
	public class EIntegerObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.EIntegerObject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EIntegerObject returns ecore::EIntegerObject:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class LiteralStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.LiteralString");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueStringSpecificationParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//// STRING LITERAL (e.g., "hello world", 'test')
		//LiteralString returns dact::UnaryExpression:
		//    value=StringSpecification;
		@Override public ParserRule getRule() { return rule; }
		
		//value=StringSpecification
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//StringSpecification
		public RuleCall getValueStringSpecificationParserRuleCall_0() { return cValueStringSpecificationParserRuleCall_0; }
	}
	public class StringSpecificationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.StringSpecification");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//StringSpecification returns dact::LiteralString:
		//    value=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//value=STRING
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_0() { return cValueSTRINGTerminalRuleCall_0; }
	}
	public class LiteralBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.LiteralBoolean");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueBooleanSpecificationParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//// BOOLEAN LITERAL (e.g., true, false)
		//LiteralBoolean returns dact::UnaryExpression:
		//    value=BooleanSpecification;
		@Override public ParserRule getRule() { return rule; }
		
		//value=BooleanSpecification
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//BooleanSpecification
		public RuleCall getValueBooleanSpecificationParserRuleCall_0() { return cValueBooleanSpecificationParserRuleCall_0; }
	}
	public class BooleanSpecificationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.BooleanSpecification");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLiteralBooleanAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final Keyword cValueTrueKeyword_1_0_0 = (Keyword)cValueAssignment_1_0.eContents().get(0);
		private final Keyword cFalseKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		
		//BooleanSpecification returns dact::LiteralBoolean:
		//    {dact::LiteralBoolean} (value?='true' | 'false');
		@Override public ParserRule getRule() { return rule; }
		
		//{dact::LiteralBoolean} (value?='true' | 'false')
		public Group getGroup() { return cGroup; }
		
		//{dact::LiteralBoolean}
		public Action getLiteralBooleanAction_0() { return cLiteralBooleanAction_0; }
		
		//(value?='true' | 'false')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//value?='true'
		public Assignment getValueAssignment_1_0() { return cValueAssignment_1_0; }
		
		//'true'
		public Keyword getValueTrueKeyword_1_0_0() { return cValueTrueKeyword_1_0_0; }
		
		//'false'
		public Keyword getFalseKeyword_1_1() { return cFalseKeyword_1_1; }
	}
	public class LiteralNullElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.LiteralNull");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueNullSpecificationParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//// NULL LITERAL (e.g., null, NULL)
		//LiteralNull returns dact::UnaryExpression:
		//    value=NullSpecification;
		@Override public ParserRule getRule() { return rule; }
		
		//value=NullSpecification
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//NullSpecification
		public RuleCall getValueNullSpecificationParserRuleCall_0() { return cValueNullSpecificationParserRuleCall_0; }
	}
	public class NullSpecificationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.NullSpecification");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLiteralNullAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cNullKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cNULLKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		
		//NullSpecification returns dact::LiteralNull:
		//    {dact::LiteralNull} ('null' | 'NULL');
		@Override public ParserRule getRule() { return rule; }
		
		//{dact::LiteralNull} ('null' | 'NULL')
		public Group getGroup() { return cGroup; }
		
		//{dact::LiteralNull}
		public Action getLiteralNullAction_0() { return cLiteralNullAction_0; }
		
		//('null' | 'NULL')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'null'
		public Keyword getNullKeyword_1_0() { return cNullKeyword_1_0; }
		
		//'NULL'
		public Keyword getNULLKeyword_1_1() { return cNULLKeyword_1_1; }
	}
	public class PropertyAccessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.PropertyAccess");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUnaryExpressionAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cIdentifierAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdentifierIdentifierParserRuleCall_1_0 = (RuleCall)cIdentifierAssignment_1.eContents().get(0);
		
		//// PROPERTY / VARIABLE ACCESS
		//PropertyAccess returns dact::UnaryExpression:
		//    {dact::UnaryExpression} identifier=Identifier;
		@Override public ParserRule getRule() { return rule; }
		
		//{dact::UnaryExpression} identifier=Identifier
		public Group getGroup() { return cGroup; }
		
		//{dact::UnaryExpression}
		public Action getUnaryExpressionAction_0() { return cUnaryExpressionAction_0; }
		
		//identifier=Identifier
		public Assignment getIdentifierAssignment_1() { return cIdentifierAssignment_1; }
		
		//Identifier
		public RuleCall getIdentifierIdentifierParserRuleCall_1_0() { return cIdentifierIdentifierParserRuleCall_1_0; }
	}
	public class IdentifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.Identifier");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIdentifierAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftSquareBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIndexAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIndexSignedIntParserRuleCall_2_1_0 = (RuleCall)cIndexAssignment_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		
		//Identifier returns dact::Identifier:
		//    {dact::Identifier} name=QualifiedName ('[' index=SignedInt ']')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{dact::Identifier} name=QualifiedName ('[' index=SignedInt ']')?
		public Group getGroup() { return cGroup; }
		
		//{dact::Identifier}
		public Action getIdentifierAction_0() { return cIdentifierAction_0; }
		
		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }
		
		//('[' index=SignedInt ']')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_2_0() { return cLeftSquareBracketKeyword_2_0; }
		
		//index=SignedInt
		public Assignment getIndexAssignment_2_1() { return cIndexAssignment_2_1; }
		
		//SignedInt
		public RuleCall getIndexSignedIntParserRuleCall_2_1_0() { return cIndexSignedIntParserRuleCall_2_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_2_2() { return cRightSquareBracketKeyword_2_2; }
	}
	public class SignedIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.SignedInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//SignedInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//    ID ('.' ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	public class LiteralEnumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.LiteralEnum");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueEnumSpecificationParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//// ENUM
		//LiteralEnum returns dact::UnaryExpression:
		//    value=EnumSpecification;
		@Override public ParserRule getRule() { return rule; }
		
		//value=EnumSpecification
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//EnumSpecification
		public RuleCall getValueEnumSpecificationParserRuleCall_0() { return cValueEnumSpecificationParserRuleCall_0; }
	}
	public class EnumSpecificationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.EnumSpecification");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameEnumQualifiedNameParserRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//EnumSpecification returns dact::EnumerationLiteral:
		//    // Matches expressions like 'Status::ACTIVE'
		//    name=EnumQualifiedName;
		@Override public ParserRule getRule() { return rule; }
		
		//// Matches expressions like 'Status::ACTIVE'
		//name=EnumQualifiedName
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//EnumQualifiedName
		public RuleCall getNameEnumQualifiedNameParserRuleCall_0() { return cNameEnumQualifiedNameParserRuleCall_0; }
	}
	public class EnumQualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "dact.dsl.ExprDsl.EnumQualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cColonColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//EnumQualifiedName:
		//    ID ('::') ID;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('::') ID
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('::')
		public Keyword getColonColonKeyword_1() { return cColonColonKeyword_1; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_2() { return cIDTerminalRuleCall_2; }
	}
	
	
	private final ExpressionElements pExpression;
	private final AssignmentExpressionElements pAssignmentExpression;
	private final OrExpressionElements pOrExpression;
	private final OrOperatorElements pOrOperator;
	private final AndExpressionElements pAndExpression;
	private final AndOperatorElements pAndOperator;
	private final ComparisonExpressionElements pComparisonExpression;
	private final ComparisonOperatorElements pComparisonOperator;
	private final AdditiveExpressionElements pAdditiveExpression;
	private final AdditiveOperatorElements pAdditiveOperator;
	private final InExpressionElements pInExpression;
	private final InOperatorElements pInOperator;
	private final MultiplicativeExpressionElements pMultiplicativeExpression;
	private final MultiplicativeOperatorElements pMultiplicativeOperator;
	private final UnaryExpressionElements pUnaryExpression;
	private final PrimaryExpressionElements pPrimaryExpression;
	private final LiteralRealElements pLiteralReal;
	private final RealSpecificationElements pRealSpecification;
	private final EDoubleObjectElements pEDoubleObject;
	private final LiteralIntegerElements pLiteralInteger;
	private final IntegerSpecificationElements pIntegerSpecification;
	private final EIntegerObjectElements pEIntegerObject;
	private final LiteralStringElements pLiteralString;
	private final StringSpecificationElements pStringSpecification;
	private final LiteralBooleanElements pLiteralBoolean;
	private final BooleanSpecificationElements pBooleanSpecification;
	private final LiteralNullElements pLiteralNull;
	private final NullSpecificationElements pNullSpecification;
	private final PropertyAccessElements pPropertyAccess;
	private final IdentifierElements pIdentifier;
	private final SignedIntElements pSignedInt;
	private final QualifiedNameElements pQualifiedName;
	private final LiteralEnumElements pLiteralEnum;
	private final EnumSpecificationElements pEnumSpecification;
	private final EnumQualifiedNameElements pEnumQualifiedName;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ExprDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pExpression = new ExpressionElements();
		this.pAssignmentExpression = new AssignmentExpressionElements();
		this.pOrExpression = new OrExpressionElements();
		this.pOrOperator = new OrOperatorElements();
		this.pAndExpression = new AndExpressionElements();
		this.pAndOperator = new AndOperatorElements();
		this.pComparisonExpression = new ComparisonExpressionElements();
		this.pComparisonOperator = new ComparisonOperatorElements();
		this.pAdditiveExpression = new AdditiveExpressionElements();
		this.pAdditiveOperator = new AdditiveOperatorElements();
		this.pInExpression = new InExpressionElements();
		this.pInOperator = new InOperatorElements();
		this.pMultiplicativeExpression = new MultiplicativeExpressionElements();
		this.pMultiplicativeOperator = new MultiplicativeOperatorElements();
		this.pUnaryExpression = new UnaryExpressionElements();
		this.pPrimaryExpression = new PrimaryExpressionElements();
		this.pLiteralReal = new LiteralRealElements();
		this.pRealSpecification = new RealSpecificationElements();
		this.pEDoubleObject = new EDoubleObjectElements();
		this.pLiteralInteger = new LiteralIntegerElements();
		this.pIntegerSpecification = new IntegerSpecificationElements();
		this.pEIntegerObject = new EIntegerObjectElements();
		this.pLiteralString = new LiteralStringElements();
		this.pStringSpecification = new StringSpecificationElements();
		this.pLiteralBoolean = new LiteralBooleanElements();
		this.pBooleanSpecification = new BooleanSpecificationElements();
		this.pLiteralNull = new LiteralNullElements();
		this.pNullSpecification = new NullSpecificationElements();
		this.pPropertyAccess = new PropertyAccessElements();
		this.pIdentifier = new IdentifierElements();
		this.pSignedInt = new SignedIntElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pLiteralEnum = new LiteralEnumElements();
		this.pEnumSpecification = new EnumSpecificationElements();
		this.pEnumQualifiedName = new EnumQualifiedNameElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("dact.dsl.ExprDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//// Root entry point
	//Expression returns dact::Expression:
	//    AssignmentExpression;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//// -----------------------------------------------------------
	//// Operator Precedence Cascade
	//// -----------------------------------------------------------
	//AssignmentExpression returns dact::Expression:
	//    {dact::VariableAssignment} identifier=Identifier '=' expr=AssignmentExpression
	//  | OrExpression;
	public AssignmentExpressionElements getAssignmentExpressionAccess() {
		return pAssignmentExpression;
	}
	
	public ParserRule getAssignmentExpressionRule() {
		return getAssignmentExpressionAccess().getRule();
	}
	
	//OrExpression returns dact::Expression:
	//    AndExpression (
	//        {dact::BinaryExpression.leftExpr=current}
	//        operator=OrOperator
	//        rightExpr=AndExpression
	//    )*;
	public OrExpressionElements getOrExpressionAccess() {
		return pOrExpression;
	}
	
	public ParserRule getOrExpressionRule() {
		return getOrExpressionAccess().getRule();
	}
	
	//OrOperator returns dact::Operator:
	//    {dact::Or} ('||' | 'OR' | 'or');
	public OrOperatorElements getOrOperatorAccess() {
		return pOrOperator;
	}
	
	public ParserRule getOrOperatorRule() {
		return getOrOperatorAccess().getRule();
	}
	
	//AndExpression returns dact::Expression:
	//    ComparisonExpression (
	//        {dact::BinaryExpression.leftExpr=current}
	//        operator=AndOperator
	//        rightExpr=ComparisonExpression
	//    )*;
	public AndExpressionElements getAndExpressionAccess() {
		return pAndExpression;
	}
	
	public ParserRule getAndExpressionRule() {
		return getAndExpressionAccess().getRule();
	}
	
	//AndOperator returns dact::Operator:
	//    {dact::And} ('&&' | 'AND' | 'and');
	public AndOperatorElements getAndOperatorAccess() {
		return pAndOperator;
	}
	
	public ParserRule getAndOperatorRule() {
		return getAndOperatorAccess().getRule();
	}
	
	//ComparisonExpression returns dact::Expression:
	//    AdditiveExpression (
	//        {dact::BinaryExpression.leftExpr=current}
	//        operator=ComparisonOperator
	//        rightExpr=AdditiveExpression
	//    )*;
	public ComparisonExpressionElements getComparisonExpressionAccess() {
		return pComparisonExpression;
	}
	
	public ParserRule getComparisonExpressionRule() {
		return getComparisonExpressionAccess().getRule();
	}
	
	//ComparisonOperator returns dact::Operator:
	//    {dact::Gt} '>'  |
	//    {dact::Ge} '>=' |
	//    {dact::Lt} '<'  |
	//    {dact::Le} '<=' |
	//    {dact::Eq} '==' |
	//    {dact::Ne} '!=';
	public ComparisonOperatorElements getComparisonOperatorAccess() {
		return pComparisonOperator;
	}
	
	public ParserRule getComparisonOperatorRule() {
		return getComparisonOperatorAccess().getRule();
	}
	
	//AdditiveExpression returns dact::Expression:
	//    InExpression (
	//        {dact::BinaryExpression.leftExpr=current}
	//        operator=AdditiveOperator
	//        rightExpr=InExpression
	//    )*;
	public AdditiveExpressionElements getAdditiveExpressionAccess() {
		return pAdditiveExpression;
	}
	
	public ParserRule getAdditiveExpressionRule() {
		return getAdditiveExpressionAccess().getRule();
	}
	
	//AdditiveOperator returns dact::Operator:
	//    {dact::Plus} '+' |
	//    {dact::Minus} '-';
	public AdditiveOperatorElements getAdditiveOperatorAccess() {
		return pAdditiveOperator;
	}
	
	public ParserRule getAdditiveOperatorRule() {
		return getAdditiveOperatorAccess().getRule();
	}
	
	//InExpression returns dact::Expression:
	//    MultiplicativeExpression (
	//        {dact::BinaryExpression.leftExpr=current}
	//        operator=InOperator
	//        rightExpr=MultiplicativeExpression
	//    )*;
	public InExpressionElements getInExpressionAccess() {
		return pInExpression;
	}
	
	public ParserRule getInExpressionRule() {
		return getInExpressionAccess().getRule();
	}
	
	//InOperator returns dact::Operator:
	//    {dact::In} ('IN' | 'in' | 'In');
	public InOperatorElements getInOperatorAccess() {
		return pInOperator;
	}
	
	public ParserRule getInOperatorRule() {
		return getInOperatorAccess().getRule();
	}
	
	//MultiplicativeExpression returns dact::Expression:
	//    UnaryExpression (
	//        {dact::BinaryExpression.leftExpr=current}
	//        operator=MultiplicativeOperator
	//        rightExpr=UnaryExpression
	//    )*;
	public MultiplicativeExpressionElements getMultiplicativeExpressionAccess() {
		return pMultiplicativeExpression;
	}
	
	public ParserRule getMultiplicativeExpressionRule() {
		return getMultiplicativeExpressionAccess().getRule();
	}
	
	//MultiplicativeOperator returns dact::Operator:
	//    {dact::Times} '*' |
	//    {dact::Divide} '/';
	public MultiplicativeOperatorElements getMultiplicativeOperatorAccess() {
		return pMultiplicativeOperator;
	}
	
	public ParserRule getMultiplicativeOperatorRule() {
		return getMultiplicativeOperatorAccess().getRule();
	}
	
	//UnaryExpression returns dact::Expression:
	//    {dact::NotExpression} ( '!' | 'NOT' | 'not') expr=PrimaryExpression
	//  | PrimaryExpression;
	public UnaryExpressionElements getUnaryExpressionAccess() {
		return pUnaryExpression;
	}
	
	public ParserRule getUnaryExpressionRule() {
		return getUnaryExpressionAccess().getRule();
	}
	
	//// Level 7: Primary Expressions & Literals
	//PrimaryExpression returns dact::Expression:
	//    LiteralReal      // Must come before LiteralInteger so floats like 3.14 don't stop at '3'
	//  | LiteralInteger
	//  | LiteralString
	//  | LiteralBoolean
	//  | LiteralNull
	//  | LiteralEnum
	//  | PropertyAccess
	//  | '(' AssignmentExpression ')'
	//;
	public PrimaryExpressionElements getPrimaryExpressionAccess() {
		return pPrimaryExpression;
	}
	
	public ParserRule getPrimaryExpressionRule() {
		return getPrimaryExpressionAccess().getRule();
	}
	
	//// -----------------------------------------------------------
	//// Leaf Terminals & Literals
	//// -----------------------------------------------------------
	//// REAL / FLOAT LITERAL (e.g., 3.14, -0.05, 10.0)
	//LiteralReal returns dact::UnaryExpression:
	//    value=RealSpecification;
	public LiteralRealElements getLiteralRealAccess() {
		return pLiteralReal;
	}
	
	public ParserRule getLiteralRealRule() {
		return getLiteralRealAccess().getRule();
	}
	
	//RealSpecification returns dact::LiteralReal:
	//    value=EDoubleObject;
	public RealSpecificationElements getRealSpecificationAccess() {
		return pRealSpecification;
	}
	
	public ParserRule getRealSpecificationRule() {
		return getRealSpecificationAccess().getRule();
	}
	
	//EDoubleObject returns ecore::EDoubleObject:
	//    '-'? INT '.' INT;
	public EDoubleObjectElements getEDoubleObjectAccess() {
		return pEDoubleObject;
	}
	
	public ParserRule getEDoubleObjectRule() {
		return getEDoubleObjectAccess().getRule();
	}
	
	//// INTEGER LITERAL (e.g., 42, -7)
	//LiteralInteger returns dact::UnaryExpression:
	//    value=IntegerSpecification;
	public LiteralIntegerElements getLiteralIntegerAccess() {
		return pLiteralInteger;
	}
	
	public ParserRule getLiteralIntegerRule() {
		return getLiteralIntegerAccess().getRule();
	}
	
	//IntegerSpecification returns dact::LiteralInteger:
	//    value=EIntegerObject;
	public IntegerSpecificationElements getIntegerSpecificationAccess() {
		return pIntegerSpecification;
	}
	
	public ParserRule getIntegerSpecificationRule() {
		return getIntegerSpecificationAccess().getRule();
	}
	
	//EIntegerObject returns ecore::EIntegerObject:
	//    '-'? INT;
	public EIntegerObjectElements getEIntegerObjectAccess() {
		return pEIntegerObject;
	}
	
	public ParserRule getEIntegerObjectRule() {
		return getEIntegerObjectAccess().getRule();
	}
	
	//// STRING LITERAL (e.g., "hello world", 'test')
	//LiteralString returns dact::UnaryExpression:
	//    value=StringSpecification;
	public LiteralStringElements getLiteralStringAccess() {
		return pLiteralString;
	}
	
	public ParserRule getLiteralStringRule() {
		return getLiteralStringAccess().getRule();
	}
	
	//StringSpecification returns dact::LiteralString:
	//    value=STRING;
	public StringSpecificationElements getStringSpecificationAccess() {
		return pStringSpecification;
	}
	
	public ParserRule getStringSpecificationRule() {
		return getStringSpecificationAccess().getRule();
	}
	
	//// BOOLEAN LITERAL (e.g., true, false)
	//LiteralBoolean returns dact::UnaryExpression:
	//    value=BooleanSpecification;
	public LiteralBooleanElements getLiteralBooleanAccess() {
		return pLiteralBoolean;
	}
	
	public ParserRule getLiteralBooleanRule() {
		return getLiteralBooleanAccess().getRule();
	}
	
	//BooleanSpecification returns dact::LiteralBoolean:
	//    {dact::LiteralBoolean} (value?='true' | 'false');
	public BooleanSpecificationElements getBooleanSpecificationAccess() {
		return pBooleanSpecification;
	}
	
	public ParserRule getBooleanSpecificationRule() {
		return getBooleanSpecificationAccess().getRule();
	}
	
	//// NULL LITERAL (e.g., null, NULL)
	//LiteralNull returns dact::UnaryExpression:
	//    value=NullSpecification;
	public LiteralNullElements getLiteralNullAccess() {
		return pLiteralNull;
	}
	
	public ParserRule getLiteralNullRule() {
		return getLiteralNullAccess().getRule();
	}
	
	//NullSpecification returns dact::LiteralNull:
	//    {dact::LiteralNull} ('null' | 'NULL');
	public NullSpecificationElements getNullSpecificationAccess() {
		return pNullSpecification;
	}
	
	public ParserRule getNullSpecificationRule() {
		return getNullSpecificationAccess().getRule();
	}
	
	//// PROPERTY / VARIABLE ACCESS
	//PropertyAccess returns dact::UnaryExpression:
	//    {dact::UnaryExpression} identifier=Identifier;
	public PropertyAccessElements getPropertyAccessAccess() {
		return pPropertyAccess;
	}
	
	public ParserRule getPropertyAccessRule() {
		return getPropertyAccessAccess().getRule();
	}
	
	//Identifier returns dact::Identifier:
	//    {dact::Identifier} name=QualifiedName ('[' index=SignedInt ']')?;
	public IdentifierElements getIdentifierAccess() {
		return pIdentifier;
	}
	
	public ParserRule getIdentifierRule() {
		return getIdentifierAccess().getRule();
	}
	
	//SignedInt returns ecore::EInt:
	//    '-'? INT;
	public SignedIntElements getSignedIntAccess() {
		return pSignedInt;
	}
	
	public ParserRule getSignedIntRule() {
		return getSignedIntAccess().getRule();
	}
	
	//QualifiedName:
	//    ID ('.' ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//// ENUM
	//LiteralEnum returns dact::UnaryExpression:
	//    value=EnumSpecification;
	public LiteralEnumElements getLiteralEnumAccess() {
		return pLiteralEnum;
	}
	
	public ParserRule getLiteralEnumRule() {
		return getLiteralEnumAccess().getRule();
	}
	
	//EnumSpecification returns dact::EnumerationLiteral:
	//    // Matches expressions like 'Status::ACTIVE'
	//    name=EnumQualifiedName;
	public EnumSpecificationElements getEnumSpecificationAccess() {
		return pEnumSpecification;
	}
	
	public ParserRule getEnumSpecificationRule() {
		return getEnumSpecificationAccess().getRule();
	}
	
	//EnumQualifiedName:
	//    ID ('::') ID;
	public EnumQualifiedNameElements getEnumQualifiedNameAccess() {
		return pEnumQualifiedName;
	}
	
	public ParserRule getEnumQualifiedNameRule() {
		return getEnumQualifiedNameAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
