/*
 * generated by Xtext 2.43.0
 */
package dact.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ExprDslUiModule extends AbstractExprDslUiModule {

	public ExprDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
