/*
 * generated by Xtext 2.43.0
 */
package dact.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ExprDslStandaloneSetup extends ExprDslStandaloneSetupGenerated {

	public static void doSetup() {
		new ExprDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
