package com.example.customer.payload;

//Autogenerated code for Payload: ExistsByCustomerIdResponse
import com.example.customer.domain.*;
  
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import jakarta.validation.constraints.NotNull;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class ExistsByCustomerIdResponse {
  @NotNull(message="'result' cannot be null")
  public Boolean result;
}
