/*
 * generated by Xtext 2.43.0
 */
package dact.dsl.parser.antlr;

import com.google.inject.Inject;
import dact.dsl.parser.antlr.internal.InternalExprDslParser;
import dact.dsl.services.ExprDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ExprDslParser extends AbstractAntlrParser {

	@Inject
	private ExprDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalExprDslParser createParser(XtextTokenStream stream) {
		return new InternalExprDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Expression";
	}

	public ExprDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ExprDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
