/*
 * generated by Xtext 2.43.0
 */
package dact.dsl.formatting2

import com.google.inject.Inject
import dact.BinaryExpression
import dact.NotExpression
import dact.dsl.services.ExprDslGrammarAccess
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument

class ExprDslFormatter extends AbstractFormatter2 {
	
	@Inject extension ExprDslGrammarAccess

	def dispatch void format(BinaryExpression binaryExpression, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		binaryExpression.operator.format
		binaryExpression.rightExpr.format
		binaryExpression.leftExpr.format
	}

	def dispatch void format(NotExpression notExpression, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		notExpression.expr.format
	}
	
	// TODO: implement for UnaryExpression
}
