/**
 */
package lemma.adapted.xcore.technology.provider;

import java.util.ArrayList;
import java.util.Collection;

import lemma.adapted.xcore.technology.util.TechnologyAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class TechnologyItemProviderAdapterFactory extends TechnologyAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public TechnologyItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.Technology} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologyItemProvider technologyItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.Technology}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologyAdapter() {
		if (technologyItemProvider == null) {
			technologyItemProvider = new TechnologyItemProvider(this);
		}

		return technologyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.TechnologyImport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologyImportItemProvider technologyImportItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.TechnologyImport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologyImportAdapter() {
		if (technologyImportItemProvider == null) {
			technologyImportItemProvider = new TechnologyImportItemProvider(this);
		}

		return technologyImportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.Protocol} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProtocolItemProvider protocolItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.Protocol}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProtocolAdapter() {
		if (protocolItemProvider == null) {
			protocolItemProvider = new ProtocolItemProvider(this);
		}

		return protocolItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.DataFormat} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataFormatItemProvider dataFormatItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.DataFormat}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataFormatAdapter() {
		if (dataFormatItemProvider == null) {
			dataFormatItemProvider = new DataFormatItemProvider(this);
		}

		return dataFormatItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.TechnologySpecificPrimitiveType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologySpecificPrimitiveTypeItemProvider technologySpecificPrimitiveTypeItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.TechnologySpecificPrimitiveType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologySpecificPrimitiveTypeAdapter() {
		if (technologySpecificPrimitiveTypeItemProvider == null) {
			technologySpecificPrimitiveTypeItemProvider = new TechnologySpecificPrimitiveTypeItemProvider(this);
		}

		return technologySpecificPrimitiveTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.TechnologySpecificCollectionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologySpecificCollectionTypeItemProvider technologySpecificCollectionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.TechnologySpecificCollectionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologySpecificCollectionTypeAdapter() {
		if (technologySpecificCollectionTypeItemProvider == null) {
			technologySpecificCollectionTypeItemProvider = new TechnologySpecificCollectionTypeItemProvider(this);
		}

		return technologySpecificCollectionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.TechnologySpecificDataStructure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologySpecificDataStructureItemProvider technologySpecificDataStructureItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.TechnologySpecificDataStructure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologySpecificDataStructureAdapter() {
		if (technologySpecificDataStructureItemProvider == null) {
			technologySpecificDataStructureItemProvider = new TechnologySpecificDataStructureItemProvider(this);
		}

		return technologySpecificDataStructureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.CompatibilityMatrixEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompatibilityMatrixEntryItemProvider compatibilityMatrixEntryItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.CompatibilityMatrixEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompatibilityMatrixEntryAdapter() {
		if (compatibilityMatrixEntryItemProvider == null) {
			compatibilityMatrixEntryItemProvider = new CompatibilityMatrixEntryItemProvider(this);
		}

		return compatibilityMatrixEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.PossiblyImportedTechnologySpecificType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PossiblyImportedTechnologySpecificTypeItemProvider possiblyImportedTechnologySpecificTypeItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.PossiblyImportedTechnologySpecificType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPossiblyImportedTechnologySpecificTypeAdapter() {
		if (possiblyImportedTechnologySpecificTypeItemProvider == null) {
			possiblyImportedTechnologySpecificTypeItemProvider = new PossiblyImportedTechnologySpecificTypeItemProvider(this);
		}

		return possiblyImportedTechnologySpecificTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.OperationEnvironment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationEnvironmentItemProvider operationEnvironmentItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.OperationEnvironment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationEnvironmentAdapter() {
		if (operationEnvironmentItemProvider == null) {
			operationEnvironmentItemProvider = new OperationEnvironmentItemProvider(this);
		}

		return operationEnvironmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.TechnologySpecificProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologySpecificPropertyItemProvider technologySpecificPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.TechnologySpecificProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologySpecificPropertyAdapter() {
		if (technologySpecificPropertyItemProvider == null) {
			technologySpecificPropertyItemProvider = new TechnologySpecificPropertyItemProvider(this);
		}

		return technologySpecificPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.TechnologySpecificPropertyValueAssignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologySpecificPropertyValueAssignmentItemProvider technologySpecificPropertyValueAssignmentItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.TechnologySpecificPropertyValueAssignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologySpecificPropertyValueAssignmentAdapter() {
		if (technologySpecificPropertyValueAssignmentItemProvider == null) {
			technologySpecificPropertyValueAssignmentItemProvider = new TechnologySpecificPropertyValueAssignmentItemProvider(this);
		}

		return technologySpecificPropertyValueAssignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.DeploymentTechnology} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeploymentTechnologyItemProvider deploymentTechnologyItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.DeploymentTechnology}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeploymentTechnologyAdapter() {
		if (deploymentTechnologyItemProvider == null) {
			deploymentTechnologyItemProvider = new DeploymentTechnologyItemProvider(this);
		}

		return deploymentTechnologyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.InfrastructureTechnology} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InfrastructureTechnologyItemProvider infrastructureTechnologyItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.InfrastructureTechnology}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInfrastructureTechnologyAdapter() {
		if (infrastructureTechnologyItemProvider == null) {
			infrastructureTechnologyItemProvider = new InfrastructureTechnologyItemProvider(this);
		}

		return infrastructureTechnologyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.ServiceAspect} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceAspectItemProvider serviceAspectItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.ServiceAspect}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceAspectAdapter() {
		if (serviceAspectItemProvider == null) {
			serviceAspectItemProvider = new ServiceAspectItemProvider(this);
		}

		return serviceAspectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.ServiceAspectPointcut} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceAspectPointcutItemProvider serviceAspectPointcutItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.ServiceAspectPointcut}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceAspectPointcutAdapter() {
		if (serviceAspectPointcutItemProvider == null) {
			serviceAspectPointcutItemProvider = new ServiceAspectPointcutItemProvider(this);
		}

		return serviceAspectPointcutItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.ServiceAspectPointcutSelector} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceAspectPointcutSelectorItemProvider serviceAspectPointcutSelectorItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.ServiceAspectPointcutSelector}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceAspectPointcutSelectorAdapter() {
		if (serviceAspectPointcutSelectorItemProvider == null) {
			serviceAspectPointcutSelectorItemProvider = new ServiceAspectPointcutSelectorItemProvider(this);
		}

		return serviceAspectPointcutSelectorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.OperationAspect} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationAspectItemProvider operationAspectItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.OperationAspect}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationAspectAdapter() {
		if (operationAspectItemProvider == null) {
			operationAspectItemProvider = new OperationAspectItemProvider(this);
		}

		return operationAspectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.OperationAspectPointcut} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationAspectPointcutItemProvider operationAspectPointcutItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.OperationAspectPointcut}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationAspectPointcutAdapter() {
		if (operationAspectPointcutItemProvider == null) {
			operationAspectPointcutItemProvider = new OperationAspectPointcutItemProvider(this);
		}

		return operationAspectPointcutItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.technology.OperationAspectPointcutSelector} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationAspectPointcutSelectorItemProvider operationAspectPointcutSelectorItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.technology.OperationAspectPointcutSelector}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationAspectPointcutSelectorAdapter() {
		if (operationAspectPointcutSelectorItemProvider == null) {
			operationAspectPointcutSelectorItemProvider = new OperationAspectPointcutSelectorItemProvider(this);
		}

		return operationAspectPointcutSelectorItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (technologyItemProvider != null) technologyItemProvider.dispose();
		if (technologyImportItemProvider != null) technologyImportItemProvider.dispose();
		if (protocolItemProvider != null) protocolItemProvider.dispose();
		if (dataFormatItemProvider != null) dataFormatItemProvider.dispose();
		if (technologySpecificPrimitiveTypeItemProvider != null) technologySpecificPrimitiveTypeItemProvider.dispose();
		if (technologySpecificCollectionTypeItemProvider != null) technologySpecificCollectionTypeItemProvider.dispose();
		if (technologySpecificDataStructureItemProvider != null) technologySpecificDataStructureItemProvider.dispose();
		if (compatibilityMatrixEntryItemProvider != null) compatibilityMatrixEntryItemProvider.dispose();
		if (possiblyImportedTechnologySpecificTypeItemProvider != null) possiblyImportedTechnologySpecificTypeItemProvider.dispose();
		if (operationEnvironmentItemProvider != null) operationEnvironmentItemProvider.dispose();
		if (technologySpecificPropertyItemProvider != null) technologySpecificPropertyItemProvider.dispose();
		if (technologySpecificPropertyValueAssignmentItemProvider != null) technologySpecificPropertyValueAssignmentItemProvider.dispose();
		if (deploymentTechnologyItemProvider != null) deploymentTechnologyItemProvider.dispose();
		if (infrastructureTechnologyItemProvider != null) infrastructureTechnologyItemProvider.dispose();
		if (serviceAspectItemProvider != null) serviceAspectItemProvider.dispose();
		if (serviceAspectPointcutItemProvider != null) serviceAspectPointcutItemProvider.dispose();
		if (serviceAspectPointcutSelectorItemProvider != null) serviceAspectPointcutSelectorItemProvider.dispose();
		if (operationAspectItemProvider != null) operationAspectItemProvider.dispose();
		if (operationAspectPointcutItemProvider != null) operationAspectPointcutItemProvider.dispose();
		if (operationAspectPointcutSelectorItemProvider != null) operationAspectPointcutSelectorItemProvider.dispose();
	}

}
