package com.example.customer.service;
//Autogenerated code for Service: CustomerService

import com.example.customer.domain.*;
import com.example.customer.payload.*;
import com.example.customer.exception.*;

import com.example.customer.repository.CustomerRepository;


import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import jakarta.transaction.Transactional;

@Service
@Slf4j
@RequiredArgsConstructor
public class CustomerService {
    
   private final CustomerRepository customerRepository;
    
    @Transactional
    public Boolean existsByCustomerId(Integer customerId){
    // Activity: existsByCustomerIdDomainService      
    // InitialNode: existsByCustomerIdDomainService-InitNode
    // CallOperationAction: existsByCustomerId 
    // Boolean true
    Boolean result = customerRepository.existsByCustomerId(customerId);
    
    return result;
   };
 
}
