/*
 * generated by Xtext 2.43.0
 */
package dact.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractExprDslScopeProvider extends DelegatingScopeProvider {
}
