/**
 *
 * $Id$
 */
package lemma.adapted.xcore.behavior.validation;

import lemma.adapted.xcore.behavior.ActivityModel;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.behavior.BehaviorModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BehaviorModelValidator {
	boolean validate();

	boolean validateT_modelUri(String value);
	boolean validateImports(EList<Object> value);
	boolean validateActivityModel(ActivityModel value);
}
