/**
 *
 * $Id$
 */
package lemma.adapted.xcore.behavior.validation;

import lemma.adapted.xcore.service.Import;


/**
 * A sample validator interface for {@link lemma.adapted.xcore.behavior.ImportedParameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImportedParameterValidator {
	boolean validate();

	boolean validateImport(Import value);

	boolean validateImport(Object value);
}
