/**
 *
 * $Id$
 */
package lemma.adapted.xcore.behavior.validation;

import lemma.adapted.xcore.behavior.Identifier;
import lemma.adapted.xcore.data.ValueSpecification;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.behavior.UnaryExpression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UnaryExpressionValidator {
	boolean validate();

	boolean validateValue(ValueSpecification value);

	boolean validateValue(Object value);
	boolean validateIdentifier(Identifier value);
}
