/**
 *
 * $Id$
 */
package lemma.adapted.xcore.behavior.validation;

import lemma.adapted.xcore.behavior.Scope;

import lemma.adapted.xcore.data.PrimitiveType;
import lemma.adapted.xcore.service.ImportedType;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.behavior.Variable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VariableValidator {
	boolean validate();

	boolean validateImportedType(ImportedType value);

	boolean validatePrimitiveType(PrimitiveType value);

	boolean validateImportedType(Object value);
	boolean validatePrimitiveType(Object value);
	boolean validateUpperBound(Integer value);
	boolean validateLowerBound(Integer value);
	boolean validateAccessibleScopes(EList<Scope> value);
	boolean validateScope(Scope value);
}
