#

bin.includes = lemma.adapted.data.metamodel.editor.jar,\
               icons/,\
               META-INF/,\
               plugin.xml,\
               plugin.properties
jars.compile.order = lemma.adapted.data.metamodel.editor.jar
source.lemma.adapted.data.metamodel.editor.jar = src-gen/
output.lemma.adapted.data.metamodel.editor.jar = bin
