/*
 * generated by Xtext 2.43.0
 */
package dact.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dact.dsl.ExprDslRuntimeModule;
import dact.dsl.ExprDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ExprDslIdeSetup extends ExprDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ExprDslRuntimeModule(), new ExprDslIdeModule()));
	}
	
}
