package com.example.cargo.outboundAdapter;
//Autogenerated code for OutboundAdapter: CustomerOutboundAdapter

import com.example.cargo.payload.*;
import com.example.cargo.domain.*;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.client.HttpClientErrorException;

@Component
@Slf4j
public class CustomerOutboundAdapter {
    
    private final RestTemplate restTemplate = new RestTemplate();
    @Value("${services.customer.url}") private String customerUrl;
    
    public Boolean CheckCustomerExistence(Integer customerId){
      // Activity: CheckCustomerExistenceOutboundAdapter      
      try {
        // InitialNode: CheckCustomerExistenceOutboundAdapter-InitNode
        // CallOperationAction: CheckCustomerExistence 
        org.springframework.web.util.UriComponentsBuilder builder = org.springframework.web.util.UriComponentsBuilder
            .fromUriString(this.customerUrl)
            .path("/{customerId}/exists");
        
        
        java.net.URI targetUri = builder.buildAndExpand(customerId).toUri();
        
        ExistsByCustomerIdResponse responseParam = restTemplate.getForObject(
            targetUri,
            ExistsByCustomerIdResponse.class
        );
        log.info("Result retrieved successfully from 'Customer' service: {}", responseParam);
        
        // Declaration: result=responseParam.result 
        Boolean result = responseParam.result
        ;
        return result;
      }catch (HttpClientErrorException ex) {
      log.error("'customer' service returned HTTP error {}: {}", ex.getStatusCode(), ex.getResponseBodyAsString());
      
      // Re-throw the exact same HttpClientErrorException with identical status and response body
      throw HttpClientErrorException.create(
          ex.getStatusCode(),
          ex.getStatusText(),
          ex.getResponseHeaders(),
          ex.getResponseBodyAsByteArray(),
          null
      );
  }
   };
}
