package com.example.cargo.service;
//Autogenerated code for Service: CargoService

import com.example.cargo.domain.*;
import com.example.cargo.payload.*;
import com.example.cargo.exception.*;

import com.example.cargo.repository.CargoRepository;
import com.example.cargo.outboundAdapter.LocationOutboundAdapter;
import com.example.cargo.outboundAdapter.LocationOutboundAdapter;
import com.example.cargo.outboundAdapter.CustomerOutboundAdapter;


import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import jakarta.transaction.Transactional;

@Service
@Slf4j
@RequiredArgsConstructor
public class CargoService {
    
   private final CargoRepository cargoRepository;
   private final LocationOutboundAdapter locationOutboundAdapter;
   private final CustomerOutboundAdapter customerOutboundAdapter;
    
    @Transactional
    public Cargo bookACargo(Integer srcPort, Integer destPort, Integer deadline, Integer customerId){
    // Activity: Scenario US2-S1 – A cargo is booked      
    // InitialNode: InitialNode1
    // Declaration: New Cargo Declaration 
    Cargo newCargo = new Cargo();
    // CallOperationAction: CheckCustomerExistence 
    // Boolean true
    Boolean customerExists = customerOutboundAdapter.CheckCustomerExistence(customerId);
    
    // ConditionalNode: CustomerExistsCondition
    if (customerExists) {
        // CallOperationAction: SourceLocationExists 
        // Boolean true
        Boolean srcLocationExists = locationOutboundAdapter.SourceLocationExists(srcPort);
        
        // ConditionalNode: SourceLocationExists
        if (!(srcLocationExists)) {
            // RaiseExceptionAction: LocationNotFound
            throw new LocationNotFound();
        } else {
          }
        
        // CallOperationAction: DestinationLocationExists 
        // Boolean true
        Boolean destLocationExists = locationOutboundAdapter.DestinationLocationExists(destPort);
        
        // ConditionalNode: SourceLocationExists
        if (!(destLocationExists)) {
            // RaiseExceptionAction: LocationNotFound
            throw new LocationNotFound();
        } else {
          }
        
        // Assignment: newCargo.role.customerId = customerId
        if (newCargo.getRole() == null) {
            newCargo.setRole(new SharedCustomer());
        }
        if (newCargo.getRole() == null) {
            newCargo.setRole(new SharedCustomer());
        }
        newCargo.getRole().setCustomerId(customerId);
        ;
        
        // Assignment: newCargo.goal.destination.portCode = destPort
        if (newCargo.getGoal() == null) {
            newCargo.setGoal(new DeliverySpecification());
        }
        if (newCargo.getGoal().getDestination() == null) {
            newCargo.getGoal().setDestination(new SharedLocation());
        }
        newCargo.getGoal().getDestination().setPortCode(destPort);
        ;
        
        // Assignment: newCargo.goal.source.portCode = srcPort
        if (newCargo.getGoal() == null) {
            newCargo.setGoal(new DeliverySpecification());
        }
        if (newCargo.getGoal().getSource() == null) {
            newCargo.getGoal().setSource(new SharedLocation());
        }
        newCargo.getGoal().getSource().setPortCode(srcPort);
        ;
        
        // Assignment: newCargo.goal.deadline = deadline
        if (newCargo.getGoal() == null) {
            newCargo.setGoal(new DeliverySpecification());
        }
        if (newCargo.getGoal() == null) {
            newCargo.setGoal(new DeliverySpecification());
        }
        newCargo.getGoal().setDeadline(deadline);
        ;
        
        // CallOperationAction: DomainCreateAction26 
        // Cargo false
         newCargo = cargoRepository.save(newCargo);
        
    } else {
          // RaiseExceptionAction: CustomerNotFound
          throw new CustomerNotFound();
      }
    
    return newCargo;
   };
 
}
