/*
 * generated by Xtext 2.43.0
 */
package dact.dsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import dact.dsl.ide.contentassist.antlr.internal.InternalExprDslParser;
import dact.dsl.services.ExprDslGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ExprDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ExprDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ExprDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getAssignmentExpressionAccess().getAlternatives(), "rule__AssignmentExpression__Alternatives");
			builder.put(grammarAccess.getOrOperatorAccess().getAlternatives_1(), "rule__OrOperator__Alternatives_1");
			builder.put(grammarAccess.getAndOperatorAccess().getAlternatives_1(), "rule__AndOperator__Alternatives_1");
			builder.put(grammarAccess.getComparisonOperatorAccess().getAlternatives(), "rule__ComparisonOperator__Alternatives");
			builder.put(grammarAccess.getAdditiveOperatorAccess().getAlternatives(), "rule__AdditiveOperator__Alternatives");
			builder.put(grammarAccess.getMultiplicativeOperatorAccess().getAlternatives(), "rule__MultiplicativeOperator__Alternatives");
			builder.put(grammarAccess.getUnaryExpressionAccess().getAlternatives(), "rule__UnaryExpression__Alternatives");
			builder.put(grammarAccess.getUnaryExpressionAccess().getAlternatives_0_1(), "rule__UnaryExpression__Alternatives_0_1");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getAlternatives(), "rule__PrimaryExpression__Alternatives");
			builder.put(grammarAccess.getBooleanSpecificationAccess().getAlternatives_1(), "rule__BooleanSpecification__Alternatives_1");
			builder.put(grammarAccess.getNullSpecificationAccess().getAlternatives_1(), "rule__NullSpecification__Alternatives_1");
			builder.put(grammarAccess.getAssignmentExpressionAccess().getGroup_0(), "rule__AssignmentExpression__Group_0__0");
			builder.put(grammarAccess.getOrExpressionAccess().getGroup(), "rule__OrExpression__Group__0");
			builder.put(grammarAccess.getOrExpressionAccess().getGroup_1(), "rule__OrExpression__Group_1__0");
			builder.put(grammarAccess.getOrOperatorAccess().getGroup(), "rule__OrOperator__Group__0");
			builder.put(grammarAccess.getAndExpressionAccess().getGroup(), "rule__AndExpression__Group__0");
			builder.put(grammarAccess.getAndExpressionAccess().getGroup_1(), "rule__AndExpression__Group_1__0");
			builder.put(grammarAccess.getAndOperatorAccess().getGroup(), "rule__AndOperator__Group__0");
			builder.put(grammarAccess.getComparisonExpressionAccess().getGroup(), "rule__ComparisonExpression__Group__0");
			builder.put(grammarAccess.getComparisonExpressionAccess().getGroup_1(), "rule__ComparisonExpression__Group_1__0");
			builder.put(grammarAccess.getComparisonOperatorAccess().getGroup_0(), "rule__ComparisonOperator__Group_0__0");
			builder.put(grammarAccess.getComparisonOperatorAccess().getGroup_1(), "rule__ComparisonOperator__Group_1__0");
			builder.put(grammarAccess.getComparisonOperatorAccess().getGroup_2(), "rule__ComparisonOperator__Group_2__0");
			builder.put(grammarAccess.getComparisonOperatorAccess().getGroup_3(), "rule__ComparisonOperator__Group_3__0");
			builder.put(grammarAccess.getComparisonOperatorAccess().getGroup_4(), "rule__ComparisonOperator__Group_4__0");
			builder.put(grammarAccess.getComparisonOperatorAccess().getGroup_5(), "rule__ComparisonOperator__Group_5__0");
			builder.put(grammarAccess.getAdditiveExpressionAccess().getGroup(), "rule__AdditiveExpression__Group__0");
			builder.put(grammarAccess.getAdditiveExpressionAccess().getGroup_1(), "rule__AdditiveExpression__Group_1__0");
			builder.put(grammarAccess.getAdditiveOperatorAccess().getGroup_0(), "rule__AdditiveOperator__Group_0__0");
			builder.put(grammarAccess.getAdditiveOperatorAccess().getGroup_1(), "rule__AdditiveOperator__Group_1__0");
			builder.put(grammarAccess.getMultiplicativeExpressionAccess().getGroup(), "rule__MultiplicativeExpression__Group__0");
			builder.put(grammarAccess.getMultiplicativeExpressionAccess().getGroup_1(), "rule__MultiplicativeExpression__Group_1__0");
			builder.put(grammarAccess.getMultiplicativeOperatorAccess().getGroup_0(), "rule__MultiplicativeOperator__Group_0__0");
			builder.put(grammarAccess.getMultiplicativeOperatorAccess().getGroup_1(), "rule__MultiplicativeOperator__Group_1__0");
			builder.put(grammarAccess.getUnaryExpressionAccess().getGroup_0(), "rule__UnaryExpression__Group_0__0");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getGroup_6(), "rule__PrimaryExpression__Group_6__0");
			builder.put(grammarAccess.getEDoubleObjectAccess().getGroup(), "rule__EDoubleObject__Group__0");
			builder.put(grammarAccess.getEIntegerObjectAccess().getGroup(), "rule__EIntegerObject__Group__0");
			builder.put(grammarAccess.getBooleanSpecificationAccess().getGroup(), "rule__BooleanSpecification__Group__0");
			builder.put(grammarAccess.getNullSpecificationAccess().getGroup(), "rule__NullSpecification__Group__0");
			builder.put(grammarAccess.getPropertyAccessAccess().getGroup(), "rule__PropertyAccess__Group__0");
			builder.put(grammarAccess.getIdentifierAccess().getGroup(), "rule__Identifier__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getAssignmentExpressionAccess().getIdentifierAssignment_0_1(), "rule__AssignmentExpression__IdentifierAssignment_0_1");
			builder.put(grammarAccess.getAssignmentExpressionAccess().getExprAssignment_0_3(), "rule__AssignmentExpression__ExprAssignment_0_3");
			builder.put(grammarAccess.getOrExpressionAccess().getOperatorAssignment_1_1(), "rule__OrExpression__OperatorAssignment_1_1");
			builder.put(grammarAccess.getOrExpressionAccess().getRightExprAssignment_1_2(), "rule__OrExpression__RightExprAssignment_1_2");
			builder.put(grammarAccess.getAndExpressionAccess().getOperatorAssignment_1_1(), "rule__AndExpression__OperatorAssignment_1_1");
			builder.put(grammarAccess.getAndExpressionAccess().getRightExprAssignment_1_2(), "rule__AndExpression__RightExprAssignment_1_2");
			builder.put(grammarAccess.getComparisonExpressionAccess().getOperatorAssignment_1_1(), "rule__ComparisonExpression__OperatorAssignment_1_1");
			builder.put(grammarAccess.getComparisonExpressionAccess().getRightExprAssignment_1_2(), "rule__ComparisonExpression__RightExprAssignment_1_2");
			builder.put(grammarAccess.getAdditiveExpressionAccess().getOperatorAssignment_1_1(), "rule__AdditiveExpression__OperatorAssignment_1_1");
			builder.put(grammarAccess.getAdditiveExpressionAccess().getRightExprAssignment_1_2(), "rule__AdditiveExpression__RightExprAssignment_1_2");
			builder.put(grammarAccess.getMultiplicativeExpressionAccess().getOperatorAssignment_1_1(), "rule__MultiplicativeExpression__OperatorAssignment_1_1");
			builder.put(grammarAccess.getMultiplicativeExpressionAccess().getRightExprAssignment_1_2(), "rule__MultiplicativeExpression__RightExprAssignment_1_2");
			builder.put(grammarAccess.getUnaryExpressionAccess().getExprAssignment_0_2(), "rule__UnaryExpression__ExprAssignment_0_2");
			builder.put(grammarAccess.getLiteralRealAccess().getValueAssignment(), "rule__LiteralReal__ValueAssignment");
			builder.put(grammarAccess.getRealSpecificationAccess().getValueAssignment(), "rule__RealSpecification__ValueAssignment");
			builder.put(grammarAccess.getLiteralIntegerAccess().getValueAssignment(), "rule__LiteralInteger__ValueAssignment");
			builder.put(grammarAccess.getIntegerSpecificationAccess().getValueAssignment(), "rule__IntegerSpecification__ValueAssignment");
			builder.put(grammarAccess.getLiteralStringAccess().getValueAssignment(), "rule__LiteralString__ValueAssignment");
			builder.put(grammarAccess.getStringSpecificationAccess().getValueAssignment(), "rule__StringSpecification__ValueAssignment");
			builder.put(grammarAccess.getLiteralBooleanAccess().getValueAssignment(), "rule__LiteralBoolean__ValueAssignment");
			builder.put(grammarAccess.getBooleanSpecificationAccess().getValueAssignment_1_0(), "rule__BooleanSpecification__ValueAssignment_1_0");
			builder.put(grammarAccess.getLiteralNullAccess().getValueAssignment(), "rule__LiteralNull__ValueAssignment");
			builder.put(grammarAccess.getPropertyAccessAccess().getIdentifierAssignment_1(), "rule__PropertyAccess__IdentifierAssignment_1");
			builder.put(grammarAccess.getIdentifierAccess().getNameAssignment_1(), "rule__Identifier__NameAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ExprDslGrammarAccess grammarAccess;

	@Override
	protected InternalExprDslParser createParser() {
		InternalExprDslParser result = new InternalExprDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ExprDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ExprDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
