<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dact" nsURI="http://www.example.org/xcore/dact" nsPrefix="dact">
  <eClassifiers xsi:type="ecore:EClass" name="TransformationOnly" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiagnosticSupported" abstract="true">
    <eOperations name="report" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="errName" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="message" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="warn" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="warningName" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="message" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root" eSuperTypes="#//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniquePrimitiveType"/>
    </eAnnotations>
    <eOperations name="UniquePrimitiveType" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ddd" eType="#//DddModel"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//ActivityModel"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primitivesTypes" upperBound="-1"
        eType="#//PrimitiveType" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedMultiplicityElement" abstract="true"
      eSuperTypes="#//NamedElement #//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NoDefaultForVariable"/>
    </eAnnotations>
    <eOperations name="NoDefaultForVariable" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="isSingle" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isCollection" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//ValueSpecification"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DddModel" eSuperTypes="#//Model #//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueBoundedContextNames UniqueSharedDomainObjectNames"/>
    </eAnnotations>
    <eOperations name="UniqueBoundedContextNames" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="UniqueSharedDomainObjectNames" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundedContexts" ordered="false"
        upperBound="-1" eType="#//BoundedContext" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sharedDomainObjects" ordered="false"
        upperBound="-1" eType="#//SharedDomainObject" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityModel" eSuperTypes="#//Model #//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueActivityNames"/>
    </eAnnotations>
    <eOperations name="UniqueActivityNames" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainNodeOperationMapping" eSuperTypes="#//TransformationOnly">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usedByExternalContext"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainNode" eType="#//DomainNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoundedContext" eSuperTypes="#//NamedElement #//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueDomainElementNames"/>
    </eAnnotations>
    <eOperations name="UniqueDomainElementNames" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isExternal" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElements" ordered="false"
        upperBound="-1" eType="#//DomainElement" containment="true" resolveProxies="false"
        eOpposite="#//DomainElement/context"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainElement" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//BoundedContext"
        eOpposite="#//BoundedContext/ownedElements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//InternalDomainObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" eType="#//Repository"
        eOpposite="#//Repository/entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueObject" eSuperTypes="#//InternalDomainObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="SharedValueObject" eSuperTypes="#//SharedDomainObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="AggregateRoot" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Repository" eSuperTypes="#//Interface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"
        eOpposite="#//Entity/repository"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//Interface"/>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//DefinesIdentityObject #//TypedMultiplicityElement #//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="MandatoryType CompositeRequiresEntity AggregateIsNotComposed PrimitivePropertyRequiresName SharedObjectTypeRestriction"/>
    </eAnnotations>
    <eOperations name="MandatoryType" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="CompositeRequiresEntity" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="AggregateIsNotComposed" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="PrimitivePropertyRequiresName" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="SharedObjectTypeRestriction" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isComposite" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainObject" eType="#//DomainObject"
        eOpposite="#//DomainObject/ownedProperties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//NamedElement #//DefinesIdentityObject #//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="MatchedDomainOperationType MatchedRepositoryOperationType MatchedServiceOperationType NoBehaviorSpecification ConstructorMatchesProperties"/>
    </eAnnotations>
    <eOperations name="MatchedDomainOperationType" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="MatchedRepositoryOperationType" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="MatchedServiceOperationType" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="NoBehaviorSpecification" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="ConstructorMatchesProperties" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toExpose" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" lowerBound="1"
        eType="#//OperationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" eType="#//Behavior"
        eOpposite="#//Behavior/specification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameters" ordered="false"
        upperBound="-1" eType="#//Parameter" containment="true" resolveProxies="false"
        eOpposite="#//Parameter/operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" eType="#//Interface"
        eOpposite="#//Interface/ownedOperations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainObject" eType="#//DomainObject"
        eOpposite="#//DomainObject/ownedOperations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecOperation" eSuperTypes="#//Operation #//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="BehaviorXorSpecification OwnedByDomainObjectOnly UniqueRuleNames SingleBoolOutParameter"/>
    </eAnnotations>
    <eOperations name="BehaviorXorSpecification" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="OwnedByDomainObjectOnly" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="UniqueRuleNames" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="SingleBoolOutParameter" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInvariant" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRules" upperBound="-1"
        eType="#//SpecRule" containment="true" resolveProxies="false" eOpposite="#//SpecRule/operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecRule" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rawString" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" ordered="false" eType="#//Expression"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//SpecOperation"
        eOpposite="#//SpecOperation/ownedRules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperationType">
    <eLiterals name="S0_DOMAIN_SERVICE"/>
    <eLiterals name="R0_REPOSITORY_CREATE"/>
    <eLiterals name="R1_REPOSITORY_READ"/>
    <eLiterals name="R2_REPOSITORY_UPDATE"/>
    <eLiterals name="R3_REPOSITORY_DELETE"/>
    <eLiterals name="R4_REPOSITORY_EXIST"/>
    <eLiterals name="D0_CONSTRUCTOR"/>
    <eLiterals name="D2_COMPOUND_MUTATOR"/>
    <eLiterals name="D4_COMPOUND_ACCESSOR"/>
    <eLiterals name="D5_SPECIFICATION"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalDomainObject" abstract="true"
      eSuperTypes="#//DomainObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" abstract="true" eSuperTypes="#//DomainElement #//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueOperationNames"/>
    </eAnnotations>
    <eOperations name="UniqueOperationNames" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperations" ordered="false"
        upperBound="-1" eType="#//Operation" containment="true" resolveProxies="false"
        eOpposite="#//Operation/interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefinesIdentityObject" abstract="true"
      eSuperTypes="#//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SingleValuedPrimitiveProperty"/>
    </eAnnotations>
    <eOperations name="SingleValuedPrimitiveProperty" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definesIdentity" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainObject" abstract="true" eSuperTypes="#//Type #//DomainElement #//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueOperationNames UniquePropertyNames SingleInvariantOperation"/>
    </eAnnotations>
    <eOperations name="UniqueOperationNames" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="UniquePropertyNames" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="SingleInvariantOperation" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedProperties" ordered="false"
        upperBound="-1" eType="#//Property" containment="true" resolveProxies="false"
        eOpposite="#//Property/domainObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperations" ordered="false"
        upperBound="-1" eType="#//Operation" containment="true" resolveProxies="false"
        eOpposite="#//Operation/domainObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" eType="#//Scope"
        containment="true" resolveProxies="false" eOpposite="#//Scope/domainObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SharedDomainObject" abstract="true"
      eSuperTypes="#//DomainObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractedRoot" eType="#//AggregateRoot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" abstract="true" eSuperTypes="#//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerType" eSuperTypes="#//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="RealType" eSuperTypes="#//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//DataType #//DomainElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLiterals" upperBound="-1"
        eType="#//EnumerationLiteral" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral" eSuperTypes="#//NamedElement #//ValueSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" eSuperTypes="#//ValueSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralNull" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralString" eSuperTypes="#//Literal">
    <eOperations name="contains" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="substring" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralInteger" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralBoolean" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralReal" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainEvent" eSuperTypes="#//NamedElement #//SharedDomainObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//NamedElement #//Behavior #//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="MappingsOnlyWithSpecification MatchedParameterMappingsCount EachParameterIsMapped"/>
    </eAnnotations>
    <eOperations name="MappingsOnlyWithSpecification" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="MatchedParameterMappingsCount" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="EachParameterIsMapped" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toTransform" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameters" ordered="false"
        upperBound="-1" eType="#//Parameter" containment="true" resolveProxies="false"
        eOpposite="#//Parameter/activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterMappings" ordered="false"
        upperBound="-1" eType="#//ParameterMapping" containment="true" resolveProxies="false"
        eOpposite="#//ParameterMapping/activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//ActivityGroup"
        containment="true" resolveProxies="false" eOpposite="#//ActivityGroup/activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDomainNodes" upperBound="-1"
        eType="#//DomainNode" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processedDomainNodeMappings"
        ordered="false" upperBound="-1" eType="#//DomainNodeOperationMapping" containment="true"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scope">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Scope"
        eOpposite="#//Scope/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" ordered="false"
        upperBound="-1" eType="#//Scope" eOpposite="#//Scope/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritedVariables" ordered="false"
        upperBound="-1" eType="#//Variable" eOpposite="#//Variable/accessibleScopes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedVariables" ordered="false"
        upperBound="-1" eType="#//Variable" containment="true" resolveProxies="false"
        eOpposite="#//Variable/scope"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//ActivityGroup"
        eOpposite="#//ActivityGroup/scope"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainObject" eType="#//DomainObject"
        eOpposite="#//DomainObject/scope"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifier" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityGroup" eSuperTypes="#//NamedElement #//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SingleInitialNode SingleFinalNode NonEmptyGroup"/>
    </eAnnotations>
    <eOperations name="SingleInitialNode" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="SingleFinalNode" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="NonEmptyGroup" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedNodes" ordered="false"
        upperBound="-1" eType="#//ActivityNode" containment="true" resolveProxies="false"
        eOpposite="#//ActivityNode/group"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEdges" ordered="false"
        upperBound="-1" eType="#//ActivityEdge" containment="true" resolveProxies="false"
        eOpposite="#//ActivityEdge/group"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" eType="#//Scope"
        containment="true" resolveProxies="false" eOpposite="#//Scope/group"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//Activity"
        eOpposite="#//Activity/root"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuredActivityNode"
        eType="#//StructuredActivityNode" eOpposite="#//StructuredActivityNode/body"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionalNode" eType="#//ConditionalNode"
        eOpposite="#//ConditionalNode/elseBody"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//TransformationOnly #//TypedMultiplicityElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessibleScopes" ordered="false"
        upperBound="-1" eType="#//Scope" eOpposite="#//Scope/inheritedVariables"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" eType="#//Scope"
        eOpposite="#//Scope/ownedVariables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceValue" eSuperTypes="#//ValueSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isInstanceOf" eType="#//DomainObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedProperties" ordered="false"
        upperBound="-1" eType="#//InstanceProperty" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceProperty" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isInstanceOf" eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        upperBound="-1" eType="#//ValueSpecification" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSpecification" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sEdge" eType="#//ActivityEdge"
        eOpposite="#//ActivityEdge/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tEdge" eType="#//ActivityEdge"
        eOpposite="#//ActivityEdge/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//ActivityGroup"
        eOpposite="#//ActivityGroup/ownedNodes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge" eSuperTypes="#//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NoSelfLoop NoEdgeIntoInitialNode NoEdgeOutOfFinalNode EndpointsInSameGroup"/>
    </eAnnotations>
    <eOperations name="NoSelfLoop" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="NoEdgeIntoInitialNode" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="NoEdgeOutOfFinalNode" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="EndpointsInSameGroup" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edgeName" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ActivityNode" eOpposite="#//ActivityNode/sEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ActivityNode" eOpposite="#//ActivityNode/tEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//ActivityGroup"
        eOpposite="#//ActivityGroup/ownedEdges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialNode" eSuperTypes="#//ControlNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tName" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlNode" abstract="true" eSuperTypes="#//ActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutableNode" abstract="true" eSuperTypes="#//ActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalNode" abstract="true" eSuperTypes="#//ControlNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variablesToReturn" upperBound="-1"
        eType="#//Identifier" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityFinalNode" eSuperTypes="#//FinalNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlowFinalNode" eSuperTypes="#//FinalNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="StructuredActivityNode" abstract="true"
      eSuperTypes="#//ControlNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="test" eType="#//Expression"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//ActivityGroup"
        containment="true" resolveProxies="false" eOpposite="#//ActivityGroup/structuredActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalNode" eSuperTypes="#//StructuredActivityNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseBody" eType="#//ActivityGroup"
        containment="true" resolveProxies="false" eOpposite="#//ActivityGroup/conditionalNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopNode" eSuperTypes="#//StructuredActivityNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="setup" eType="#//ActivityGroup"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behavior" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" eType="#//Operation"
        eOpposite="#//Operation/behavior"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CallOperationAction" eSuperTypes="#//ExecutableNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toDeclareResult" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterMappings" ordered="false"
        upperBound="-1" eType="#//ParameterMapping" containment="true" resolveProxies="false"
        eOpposite="#//ParameterMapping/action"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationAction" eSuperTypes="#//ExecutableNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" eType="#//VariableAssignment"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableAssignment" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifier" eType="#//Identifier"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expression"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RaiseExceptionAction" eSuperTypes="#//ExecutableNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RaiseEntityNotFoundExceptionAction"
      eSuperTypes="#//RaiseExceptionAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SendSignalAction" eSuperTypes="#//SignalAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReceiveSignalAction" eSuperTypes="#//SignalAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableAssignmentAction" eSuperTypes="#//ExecutableNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignment" eType="#//VariableAssignment"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelNode" eSuperTypes="#//ControlNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flows" ordered="false"
        upperBound="-1" eType="#//ParallelFlow" containment="true" resolveProxies="false"
        eOpposite="#//ParallelFlow/parallelNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelFlow" eSuperTypes="#//ActivityGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPrimary" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parallelNode" lowerBound="1"
        eType="#//ParallelNode" eOpposite="#//ParallelNode/flows"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainNode" abstract="true" eSuperTypes="#//ExecutableNode #//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="RequiresMainExpression SelfAnchoredBinaryExpression"/>
    </eAnnotations>
    <eOperations name="RequiresMainExpression" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="SelfAnchoredBinaryExpression" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregate" lowerBound="1"
        eType="#//AggregateRoot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//Identifier"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainExpr" upperBound="-1"
        eType="#//Expression" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyChain" upperBound="-1"
        eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainExistAction" eSuperTypes="#//DomainFindAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainFindAction" eSuperTypes="#//DomainNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainCreateAction" eSuperTypes="#//DomainNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainUpdateAction" eSuperTypes="#//DomainCreateAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="DomainDeleteAction" eSuperTypes="#//DomainNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="SignalAction" abstract="true" eSuperTypes="#//ExecutableNode #//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ExclusiveEventSource"/>
    </eAnnotations>
    <eOperations name="ExclusiveEventSource" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="#//DomainEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifier" eType="#//Identifier"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ValueSpecification"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//TypedMultiplicityElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" unique="false"
        eType="#//ParameterDirection" defaultValueLiteral="IN"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" unique="false" eType="#//ParameterRole"
        defaultValueLiteral="CORE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//Operation"
        eOpposite="#//Operation/ownedParameters"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//Activity"
        eOpposite="#//Activity/ownedParameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterDirection">
    <eLiterals name="IN"/>
    <eLiterals name="OUT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterRole">
    <eLiterals name="CORE"/>
    <eLiterals name="SUPPORTING"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterMapping" eSuperTypes="#//DiagnosticSupported">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ConformingActivityOperationParameter ExclusiveMappingSource ValueOnlyInAction"/>
    </eAnnotations>
    <eOperations name="ConformingActivityOperationParameter" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="ExclusiveMappingSource" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="ValueOnlyInAction" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" unique="false">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" eType="#//ParameterMappingType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationParameter" lowerBound="1"
        eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifier" eType="#//Identifier"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityParameter" eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ValueSpecification"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//CallOperationAction"
        eOpposite="#//CallOperationAction/parameterMappings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//Activity"
        eOpposite="#//Activity/parameterMappings"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterMappingType">
    <eLiterals name="ACTION_IN"/>
    <eLiterals name="ACTION_OUT"/>
    <eLiterals name="ACTIVITY_IN"/>
    <eLiterals name="ACTIVITY_OUT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//NamedElement #//TypedMultiplicityElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumValue" eType="#//EnumerationLiteral"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ValueSpecification"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifier" eType="#//Identifier"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" eType="#//Operator"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftExpr" eType="#//Expression"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightExpr" eType="#//Expression"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#//Expression"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operator" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerOperator" abstract="true" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Divide" eSuperTypes="#//IntegerOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Times" eSuperTypes="#//IntegerOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Plus" eSuperTypes="#//IntegerOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Minus" eSuperTypes="#//IntegerOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalOperator" abstract="true" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Gt" eSuperTypes="#//LogicalOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lt" eSuperTypes="#//LogicalOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ge" eSuperTypes="#//LogicalOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Le" eSuperTypes="#//LogicalOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eq" eSuperTypes="#//LogicalOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ne" eSuperTypes="#//LogicalOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//LogicalOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//LogicalOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="In" eSuperTypes="#//LogicalOperator"/>
</ecore:EPackage>
