/**
 *
 * $Id$
 */
package lemma.adapted.xcore.data.validation;

import lemma.adapted.xcore.data.DataModel;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.data.ComplexTypeImport}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComplexTypeImportValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateImportURI(String value);
	boolean validateDataModel(DataModel value);
}
