/**
 *
 * $Id$
 */
package lemma.adapted.xcore.data.validation;

import lemma.adapted.xcore.data.DataOperationFeature;
import lemma.adapted.xcore.data.DataOperationParameter;
import lemma.adapted.xcore.data.DataStructure;
import lemma.adapted.xcore.data.OperationType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.data.DataOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataOperationValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateHidden(boolean value);
	boolean validateHasNoReturnType(boolean value);
	boolean validateFeatures(EList<DataOperationFeature> value);
	boolean validateOperationType(OperationType value);
	boolean validateParameters(EList<DataOperationParameter> value);
	boolean validateDataStructure(DataStructure value);
	boolean validateInherited(boolean value);
}
