/**
 *
 * $Id$
 */
package lemma.adapted.xcore.data.validation;

import lemma.adapted.xcore.data.ComplexType;
import lemma.adapted.xcore.data.ComplexTypeImport;
import lemma.adapted.xcore.data.Context;
import lemma.adapted.xcore.data.Version;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.data.DataModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataModelValidator {
	boolean validate();

	boolean validateT_modelUri(String value);
	boolean validateComplexTypeImports(EList<ComplexTypeImport> value);
	boolean validateVersions(EList<Version> value);
	boolean validateContexts(EList<Context> value);
	boolean validateComplexTypes(EList<ComplexType> value);
}
