/**
 *
 * $Id$
 */
package lemma.adapted.xcore.data.validation;

import lemma.adapted.xcore.data.Enumeration;
import lemma.adapted.xcore.data.PrimitiveValue;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.data.EnumerationField}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EnumerationFieldValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateInitializationValue(PrimitiveValue value);
	boolean validateEnumeration(Enumeration value);
}
