/**
 *
 * $Id$
 */
package lemma.adapted.xcore.data.validation;

import lemma.adapted.xcore.data.ComplexTypeImport;
import lemma.adapted.xcore.data.DataField;
import lemma.adapted.xcore.data.DataOperationParameter;
import lemma.adapted.xcore.data.Type;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.data.ImportedComplexType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImportedComplexTypeValidator {
	boolean validate();

	boolean validateImport(ComplexTypeImport value);
	boolean validateImportedType(Type value);
	boolean validateDataField(DataField value);
	boolean validateParameter(DataOperationParameter value);
}
