/**
 * generated by Xtext 2.43.0
 */
package dact.dsl.formatting2;

import com.google.inject.Inject;
import dact.BinaryExpression;
import dact.Expression;
import dact.NotExpression;
import dact.Operator;
import dact.dsl.services.ExprDslGrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatter;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;

@SuppressWarnings("all")
public class ExprDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private ExprDslGrammarAccess _exprDslGrammarAccess;

  protected void _format(final NotExpression notExpression, @Extension final IFormattableDocument document) {
    document.<Expression>format(notExpression.getExpr());
  }

  protected void _format(final BinaryExpression expr, @Extension final IFormattableDocument document) {
    document.<Operator>format(expr.getOperator());
    document.<Expression>format(expr.getLeftExpr());
    document.<Expression>format(expr.getRightExpr());
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(document.prepend(this.textRegionExtensions.regionFor(expr).keyword("("), _function), _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(expr).keyword(")"), _function_2);
  }

  @XbaseGenerated
  public void format(final Object expr, final IFormattableDocument document) {
    if (expr instanceof BinaryExpression) {
      _format((BinaryExpression)expr, document);
      return;
    } else if (expr instanceof NotExpression) {
      _format((NotExpression)expr, document);
      return;
    } else if (expr instanceof XtextResource) {
      _format((XtextResource)expr, document);
      return;
    } else if (expr instanceof EObject) {
      _format((EObject)expr, document);
      return;
    } else if (expr == null) {
      _format((Void)null, document);
      return;
    } else if (expr != null) {
      _format(expr, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(expr, document).toString());
    }
  }
}
