/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.service.ApiParameterComment;
import lemma.adapted.xcore.service.Operation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.ApiOperationComment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ApiOperationCommentValidator {
	boolean validate();

	boolean validateComment(String value);
	boolean validateParameterComments(EList<ApiParameterComment> value);
	boolean validateOperation(Operation value);
}
