/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.service.ImportedProtocolAndDataFormat;
import lemma.adapted.xcore.service.Interface;
import lemma.adapted.xcore.service.Microservice;
import lemma.adapted.xcore.service.Operation;
import lemma.adapted.xcore.service.ReferredOperation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.Endpoint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EndpointValidator {
	boolean validate();

	boolean validateAddresses(EList<String> value);
	boolean validateProtocols(EList<ImportedProtocolAndDataFormat> value);
	boolean validateMicroservice(Microservice value);
	boolean validateInterface(Interface value);
	boolean validateOperation(Operation value);
	boolean validateReferredOperation(ReferredOperation value);
}
