/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.service.ImportType;
import lemma.adapted.xcore.service.ServiceModel;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.Import}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImportValidator {
	boolean validate();

	boolean validateT_relatedImportAlias(String value);
	boolean validateName(String value);
	boolean validateImportURI(String value);
	boolean validateImportType(ImportType value);
	boolean validateServiceModel(ServiceModel value);
}
