/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.data.PrimitiveValue;

import lemma.adapted.xcore.service.Import;
import lemma.adapted.xcore.service.Interface;
import lemma.adapted.xcore.service.MappedComplexType;
import lemma.adapted.xcore.service.MappedDataOperation;
import lemma.adapted.xcore.service.MappedDataOperationParameter;
import lemma.adapted.xcore.service.MappedDataOperationReturnType;
import lemma.adapted.xcore.service.MappedField;
import lemma.adapted.xcore.service.Microservice;
import lemma.adapted.xcore.service.Operation;
import lemma.adapted.xcore.service.Parameter;
import lemma.adapted.xcore.service.ReferredOperation;

import lemma.adapted.xcore.technology.ServiceAspect;
import lemma.adapted.xcore.technology.TechnologySpecificPropertyValueAssignment;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.ImportedServiceAspect}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImportedServiceAspectValidator {
	boolean validate();

	boolean validateImport(Import value);
	boolean validateImportedAspect(ServiceAspect value);
	boolean validateSinglePropertyValue(PrimitiveValue value);
	boolean validateValues(EList<TechnologySpecificPropertyValueAssignment> value);
	boolean validateMicroservice(Microservice value);
	boolean validateInterface(Interface value);
	boolean validateOperation(Operation value);
	boolean validateReferredOperation(ReferredOperation value);
	boolean validateParameter(Parameter value);
	boolean validateMappedComplexType(MappedComplexType value);
	boolean validateMappedField(MappedField value);
	boolean validateMappedDataOperation(MappedDataOperation value);
	boolean validateMappedDataOperationReturnType(MappedDataOperationReturnType value);
	boolean validateMappedDataOperationParameter(MappedDataOperationParameter value);
}
