/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.service.Endpoint;
import lemma.adapted.xcore.service.ImportedServiceAspect;
import lemma.adapted.xcore.service.InterfaceType;
import lemma.adapted.xcore.service.Microservice;
import lemma.adapted.xcore.service.Operation;
import lemma.adapted.xcore.service.ProtocolSpecification;
import lemma.adapted.xcore.service.ReferredOperation;
import lemma.adapted.xcore.service.Visibility;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.Interface}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InterfaceValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateVersion(String value);
	boolean validateNotImplemented(boolean value);
	boolean validateVisibility(Visibility value);
	boolean validateInterfaceType(InterfaceType value);
	boolean validateEndpoints(EList<Endpoint> value);
	boolean validateProtocols(EList<ProtocolSpecification> value);
	boolean validateOperations(EList<Operation> value);
	boolean validateReferredOperations(EList<ReferredOperation> value);
	boolean validateAspects(EList<ImportedServiceAspect> value);
	boolean validateMicroservice(Microservice value);
	boolean validateEffectiveVisibility(Visibility value);
	boolean validateEffectivelyImplemented(boolean value);
	boolean validateEffectivelyInternal(boolean value);
}
