/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.data.DataField;
import lemma.adapted.xcore.data.EnumerationField;

import lemma.adapted.xcore.service.ImportedServiceAspect;
import lemma.adapted.xcore.service.ImportedType;
import lemma.adapted.xcore.service.MappedComplexType;
import lemma.adapted.xcore.service.Parameter;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.MappedField}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MappedFieldValidator {
	boolean validate();

	boolean validateDataField(DataField value);
	boolean validateEnumerationField(EnumerationField value);
	boolean validateMappedType(ImportedType value);
	boolean validateAspects(EList<ImportedServiceAspect> value);
	boolean validateParameter(Parameter value);
	boolean validateMappedComplexType(MappedComplexType value);
	boolean validateName(String value);
}
