/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import java.util.Map;

import lemma.adapted.xcore.service.Endpoint;
import lemma.adapted.xcore.service.Import;
import lemma.adapted.xcore.service.ImportedServiceAspect;
import lemma.adapted.xcore.service.Interface;
import lemma.adapted.xcore.service.MicroserviceType;
import lemma.adapted.xcore.service.PossiblyImportedInterface;
import lemma.adapted.xcore.service.PossiblyImportedMicroservice;
import lemma.adapted.xcore.service.PossiblyImportedOperation;
import lemma.adapted.xcore.service.ProtocolSpecification;
import lemma.adapted.xcore.service.ServiceModel;
import lemma.adapted.xcore.service.TechnologyReference;
import lemma.adapted.xcore.service.Visibility;

import lemma.adapted.xcore.technology.CommunicationType;
import lemma.adapted.xcore.technology.Protocol;
import lemma.adapted.xcore.technology.Technology;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.xbase.lib.Pair;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.Microservice}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MicroserviceValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateVersion(String value);
	boolean validateType(MicroserviceType value);
	boolean validateVisibility(Visibility value);
	boolean validateT_defaultProtocols(Map<CommunicationType, Pair<Import, Protocol>> value);
	boolean validateT_sourceModelUri(String value);
	boolean validateT_mappingModelUri(String value);
	boolean validateTechnologyReferences(EList<TechnologyReference> value);
	boolean validateT_typeDefinitionTechnologyImport(Import value);
	boolean validateT_typeDefinitionTechnology(Technology value);
	boolean validateEndpoints(EList<Endpoint> value);
	boolean validateRequiredMicroservices(EList<PossiblyImportedMicroservice> value);
	boolean validateRequiredInterfaces(EList<PossiblyImportedInterface> value);
	boolean validateRequiredOperations(EList<PossiblyImportedOperation> value);
	boolean validateProtocols(EList<ProtocolSpecification> value);
	boolean validateInterfaces(EList<Interface> value);
	boolean validateAspects(EList<ImportedServiceAspect> value);
	boolean validateServiceModel(ServiceModel value);
	boolean validateEffectivelyImplemented(boolean value);
	boolean validateEffectiveVisibility(Visibility value);
	boolean validateEffectivelyInternal(boolean value);
}
