/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.data.PrimitiveType;
import lemma.adapted.xcore.data.PrimitiveValue;

import lemma.adapted.xcore.service.AdapterParameterType;
import lemma.adapted.xcore.service.ImportedServiceAspect;
import lemma.adapted.xcore.service.ImportedType;
import lemma.adapted.xcore.service.MappedField;
import lemma.adapted.xcore.service.Operation;
import lemma.adapted.xcore.service.PossiblyImportedOperation;

import lemma.adapted.xcore.technology.CommunicationType;
import lemma.adapted.xcore.technology.ExchangePattern;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.Parameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParameterValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateExchangePattern(ExchangePattern value);
	boolean validateCommunicationType(CommunicationType value);
	boolean validateCommunicatesFault(boolean value);
	boolean validateOptional(boolean value);
	boolean validateLowerBound(Integer value);
	boolean validateUpperBound(Integer value);
	boolean validateAdapterParameterType(AdapterParameterType value);
	boolean validateInitializationValue(PrimitiveValue value);
	boolean validateInitializedByOperation(PossiblyImportedOperation value);
	boolean validateImportedType(ImportedType value);
	boolean validatePrimitiveType(PrimitiveType value);
	boolean validateAspects(EList<ImportedServiceAspect> value);
	boolean validateMappedFields(EList<MappedField> value);
	boolean validateOriginalImportedType(ImportedType value);
	boolean validateOriginalPrimitiveType(PrimitiveType value);
	boolean validateOperation(Operation value);
}
