/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.service.Import;
import lemma.adapted.xcore.service.Microservice;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.PossiblyImportedMicroservice}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PossiblyImportedMicroserviceValidator {
	boolean validate();

	boolean validateImport(Import value);
	boolean validateMicroservice(Microservice value);
	boolean validateRequiringMicroservice(Microservice value);
}
