/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.service.Import;
import lemma.adapted.xcore.service.Microservice;
import lemma.adapted.xcore.service.Operation;
import lemma.adapted.xcore.service.Parameter;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.PossiblyImportedOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PossiblyImportedOperationValidator {
	boolean validate();

	boolean validateImport(Import value);
	boolean validateOperation(Operation value);
	boolean validateRequiringMicroservice(Microservice value);
	boolean validateInitializedParameter(Parameter value);
	boolean validateRequired(boolean value);
	boolean validateRequiredByInterface(boolean value);
	boolean validateRequiredByMicroservice(boolean value);
	boolean validateRequiredByContainer(boolean value);
}
