/**
 *
 * $Id$
 */
package lemma.adapted.xcore.service.validation;

import lemma.adapted.xcore.service.Endpoint;
import lemma.adapted.xcore.service.ImportedServiceAspect;
import lemma.adapted.xcore.service.Interface;
import lemma.adapted.xcore.service.Operation;
import lemma.adapted.xcore.service.ProtocolSpecification;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.service.ReferredOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReferredOperationValidator {
	boolean validate();

	boolean validateOperation(Operation value);
	boolean validateEndpoints(EList<Endpoint> value);
	boolean validateProtocols(EList<ProtocolSpecification> value);
	boolean validateAspects(EList<ImportedServiceAspect> value);
	boolean validateInterface(Interface value);
}
