package com.example.cargo.domain;
//Autogenerated code for Entity: Cargo

import jakarta.persistence.Entity;
import jakarta.persistence.Column;
import jakarta.persistence.Table;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.validation.constraints.Size;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.CollectionTable;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.EnumType;
import jakarta.persistence.Embedded;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.AttributeOverride;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Set;

@Entity
@Table(name = "Cargo")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Cargo {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(nullable = false)
  private Long trackingId;

  @ManyToOne(cascade = CascadeType.ALL)
  @JoinColumn(name = "deliveryHistoryId")
  private DeliveryHistory deliveryHistory;

  @Enumerated(EnumType.STRING)
  @Column(nullable = false)
  private CargoStatus status;

  @Embedded
  @AttributeOverrides({
      @AttributeOverride(name = "customerId", column = @Column(name = "role_customerId")),
  })
  private SharedCustomer role;

  @Embedded
  @AttributeOverrides({
      @AttributeOverride(name = "source", column = @Column(name = "goal_source")),
      @AttributeOverride(name = "destination", column = @Column(name = "goal_destination")),
      @AttributeOverride(name = "deadline", column = @Column(name = "goal_deadline")),
  })
  private DeliverySpecification goal;

  @ElementCollection(targetClass = CargoStatus.class)
  @CollectionTable(name = "Cargo_testStatusMulti", joinColumns = @JoinColumn(name = "trackingId"))
  @Column(name = "testStatusMulti")
  @Enumerated(EnumType.STRING)
  @Size(min = 1)
  private Set<CargoStatus> testStatusMulti;


@PreUpdate
@PrePersist
  public void validate(){
      if (this.goal != null) {
          this.goal.validate();
      }
  }
}
