package com.example.cargo.domain;
//Autogenerated code for DataObject: SharedCustomer
  
import jakarta.persistence.Embeddable;
import jakarta.persistence.Column;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;

@Embeddable
@Data
@NoArgsConstructor
@AllArgsConstructor
public class SharedCustomer {
  @Column(nullable = false)
  private Integer customerId;

  }
