/*
 * generated by Xtext 2.43.0
 */
package dact.dsl.serializer;

import com.google.inject.Inject;
import dact.And;
import dact.BinaryExpression;
import dact.DactPackage;
import dact.Divide;
import dact.EnumerationLiteral;
import dact.Eq;
import dact.Ge;
import dact.Gt;
import dact.Identifier;
import dact.In;
import dact.Le;
import dact.LiteralBoolean;
import dact.LiteralInteger;
import dact.LiteralNull;
import dact.LiteralReal;
import dact.LiteralString;
import dact.Lt;
import dact.Minus;
import dact.Ne;
import dact.NotExpression;
import dact.Or;
import dact.Plus;
import dact.Times;
import dact.UnaryExpression;
import dact.VariableAssignment;
import dact.dsl.services.ExprDslGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class ExprDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ExprDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == DactPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case DactPackage.AND:
				sequence_AndOperator(context, (And) semanticObject); 
				return; 
			case DactPackage.BINARY_EXPRESSION:
				sequence_AdditiveExpression_AndExpression_ComparisonExpression_InExpression_MultiplicativeExpression_OrExpression(context, (BinaryExpression) semanticObject); 
				return; 
			case DactPackage.DIVIDE:
				sequence_MultiplicativeOperator(context, (Divide) semanticObject); 
				return; 
			case DactPackage.ENUMERATION_LITERAL:
				sequence_EnumSpecification(context, (EnumerationLiteral) semanticObject); 
				return; 
			case DactPackage.EQ:
				sequence_ComparisonOperator(context, (Eq) semanticObject); 
				return; 
			case DactPackage.GE:
				sequence_ComparisonOperator(context, (Ge) semanticObject); 
				return; 
			case DactPackage.GT:
				sequence_ComparisonOperator(context, (Gt) semanticObject); 
				return; 
			case DactPackage.IDENTIFIER:
				sequence_Identifier(context, (Identifier) semanticObject); 
				return; 
			case DactPackage.IN:
				sequence_InOperator(context, (In) semanticObject); 
				return; 
			case DactPackage.LE:
				sequence_ComparisonOperator(context, (Le) semanticObject); 
				return; 
			case DactPackage.LITERAL_BOOLEAN:
				sequence_BooleanSpecification(context, (LiteralBoolean) semanticObject); 
				return; 
			case DactPackage.LITERAL_INTEGER:
				sequence_IntegerSpecification(context, (LiteralInteger) semanticObject); 
				return; 
			case DactPackage.LITERAL_NULL:
				sequence_NullSpecification(context, (LiteralNull) semanticObject); 
				return; 
			case DactPackage.LITERAL_REAL:
				sequence_RealSpecification(context, (LiteralReal) semanticObject); 
				return; 
			case DactPackage.LITERAL_STRING:
				sequence_StringSpecification(context, (LiteralString) semanticObject); 
				return; 
			case DactPackage.LT:
				sequence_ComparisonOperator(context, (Lt) semanticObject); 
				return; 
			case DactPackage.MINUS:
				sequence_AdditiveOperator(context, (Minus) semanticObject); 
				return; 
			case DactPackage.NE:
				sequence_ComparisonOperator(context, (Ne) semanticObject); 
				return; 
			case DactPackage.NOT_EXPRESSION:
				sequence_UnaryExpression(context, (NotExpression) semanticObject); 
				return; 
			case DactPackage.OR:
				sequence_OrOperator(context, (Or) semanticObject); 
				return; 
			case DactPackage.PLUS:
				sequence_AdditiveOperator(context, (Plus) semanticObject); 
				return; 
			case DactPackage.TIMES:
				sequence_MultiplicativeOperator(context, (Times) semanticObject); 
				return; 
			case DactPackage.UNARY_EXPRESSION:
				if (rule == grammarAccess.getExpressionRule()
						|| rule == grammarAccess.getAssignmentExpressionRule()
						|| rule == grammarAccess.getOrExpressionRule()
						|| action == grammarAccess.getOrExpressionAccess().getBinaryExpressionLeftExprAction_1_0()
						|| rule == grammarAccess.getAndExpressionRule()
						|| action == grammarAccess.getAndExpressionAccess().getBinaryExpressionLeftExprAction_1_0()
						|| rule == grammarAccess.getComparisonExpressionRule()
						|| action == grammarAccess.getComparisonExpressionAccess().getBinaryExpressionLeftExprAction_1_0()
						|| rule == grammarAccess.getAdditiveExpressionRule()
						|| action == grammarAccess.getAdditiveExpressionAccess().getBinaryExpressionLeftExprAction_1_0()
						|| rule == grammarAccess.getInExpressionRule()
						|| action == grammarAccess.getInExpressionAccess().getBinaryExpressionLeftExprAction_1_0()
						|| rule == grammarAccess.getMultiplicativeExpressionRule()
						|| action == grammarAccess.getMultiplicativeExpressionAccess().getBinaryExpressionLeftExprAction_1_0()
						|| rule == grammarAccess.getUnaryExpressionRule()
						|| rule == grammarAccess.getPrimaryExpressionRule()) {
					sequence_LiteralBoolean_LiteralEnum_LiteralInteger_LiteralNull_LiteralReal_LiteralString_PropertyAccess(context, (UnaryExpression) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getLiteralBooleanRule()) {
					sequence_LiteralBoolean(context, (UnaryExpression) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getLiteralEnumRule()) {
					sequence_LiteralEnum(context, (UnaryExpression) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getLiteralIntegerRule()) {
					sequence_LiteralInteger(context, (UnaryExpression) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getLiteralNullRule()) {
					sequence_LiteralNull(context, (UnaryExpression) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getLiteralRealRule()) {
					sequence_LiteralReal(context, (UnaryExpression) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getLiteralStringRule()) {
					sequence_LiteralString(context, (UnaryExpression) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getPropertyAccessRule()) {
					sequence_PropertyAccess(context, (UnaryExpression) semanticObject); 
					return; 
				}
				else break;
			case DactPackage.VARIABLE_ASSIGNMENT:
				sequence_AssignmentExpression(context, (VariableAssignment) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns BinaryExpression
	 *     AssignmentExpression returns BinaryExpression
	 *     OrExpression returns BinaryExpression
	 *     OrExpression.BinaryExpression_1_0 returns BinaryExpression
	 *     AndExpression returns BinaryExpression
	 *     AndExpression.BinaryExpression_1_0 returns BinaryExpression
	 *     ComparisonExpression returns BinaryExpression
	 *     ComparisonExpression.BinaryExpression_1_0 returns BinaryExpression
	 *     AdditiveExpression returns BinaryExpression
	 *     AdditiveExpression.BinaryExpression_1_0 returns BinaryExpression
	 *     InExpression returns BinaryExpression
	 *     InExpression.BinaryExpression_1_0 returns BinaryExpression
	 *     MultiplicativeExpression returns BinaryExpression
	 *     MultiplicativeExpression.BinaryExpression_1_0 returns BinaryExpression
	 *     UnaryExpression returns BinaryExpression
	 *     PrimaryExpression returns BinaryExpression
	 *
	 * Constraint:
	 *     (
	 *         (leftExpr=OrExpression_BinaryExpression_1_0 operator=OrOperator rightExpr=AndExpression) | 
	 *         (leftExpr=AndExpression_BinaryExpression_1_0 operator=AndOperator rightExpr=ComparisonExpression) | 
	 *         (leftExpr=ComparisonExpression_BinaryExpression_1_0 operator=ComparisonOperator rightExpr=AdditiveExpression) | 
	 *         (leftExpr=AdditiveExpression_BinaryExpression_1_0 operator=AdditiveOperator rightExpr=InExpression) | 
	 *         (leftExpr=InExpression_BinaryExpression_1_0 operator=InOperator rightExpr=MultiplicativeExpression) | 
	 *         (leftExpr=MultiplicativeExpression_BinaryExpression_1_0 operator=MultiplicativeOperator rightExpr=UnaryExpression)
	 *     )
	 * </pre>
	 */
	protected void sequence_AdditiveExpression_AndExpression_ComparisonExpression_InExpression_MultiplicativeExpression_OrExpression(ISerializationContext context, BinaryExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AdditiveOperator returns Minus
	 *
	 * Constraint:
	 *     {Minus}
	 * </pre>
	 */
	protected void sequence_AdditiveOperator(ISerializationContext context, Minus semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AdditiveOperator returns Plus
	 *
	 * Constraint:
	 *     {Plus}
	 * </pre>
	 */
	protected void sequence_AdditiveOperator(ISerializationContext context, Plus semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AndOperator returns And
	 *
	 * Constraint:
	 *     {And}
	 * </pre>
	 */
	protected void sequence_AndOperator(ISerializationContext context, And semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns VariableAssignment
	 *     AssignmentExpression returns VariableAssignment
	 *     OrExpression returns VariableAssignment
	 *     OrExpression.BinaryExpression_1_0 returns VariableAssignment
	 *     AndExpression returns VariableAssignment
	 *     AndExpression.BinaryExpression_1_0 returns VariableAssignment
	 *     ComparisonExpression returns VariableAssignment
	 *     ComparisonExpression.BinaryExpression_1_0 returns VariableAssignment
	 *     AdditiveExpression returns VariableAssignment
	 *     AdditiveExpression.BinaryExpression_1_0 returns VariableAssignment
	 *     InExpression returns VariableAssignment
	 *     InExpression.BinaryExpression_1_0 returns VariableAssignment
	 *     MultiplicativeExpression returns VariableAssignment
	 *     MultiplicativeExpression.BinaryExpression_1_0 returns VariableAssignment
	 *     UnaryExpression returns VariableAssignment
	 *     PrimaryExpression returns VariableAssignment
	 *
	 * Constraint:
	 *     (identifier=Identifier expr=AssignmentExpression)
	 * </pre>
	 */
	protected void sequence_AssignmentExpression(ISerializationContext context, VariableAssignment semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DactPackage.Literals.VARIABLE_ASSIGNMENT__IDENTIFIER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DactPackage.Literals.VARIABLE_ASSIGNMENT__IDENTIFIER));
			if (transientValues.isValueTransient(semanticObject, DactPackage.Literals.VARIABLE_ASSIGNMENT__EXPR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DactPackage.Literals.VARIABLE_ASSIGNMENT__EXPR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAssignmentExpressionAccess().getIdentifierIdentifierParserRuleCall_0_1_0(), semanticObject.getIdentifier());
		feeder.accept(grammarAccess.getAssignmentExpressionAccess().getExprAssignmentExpressionParserRuleCall_0_3_0(), semanticObject.getExpr());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     BooleanSpecification returns LiteralBoolean
	 *
	 * Constraint:
	 *     value?='true'?
	 * </pre>
	 */
	protected void sequence_BooleanSpecification(ISerializationContext context, LiteralBoolean semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ComparisonOperator returns Eq
	 *
	 * Constraint:
	 *     {Eq}
	 * </pre>
	 */
	protected void sequence_ComparisonOperator(ISerializationContext context, Eq semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ComparisonOperator returns Ge
	 *
	 * Constraint:
	 *     {Ge}
	 * </pre>
	 */
	protected void sequence_ComparisonOperator(ISerializationContext context, Ge semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ComparisonOperator returns Gt
	 *
	 * Constraint:
	 *     {Gt}
	 * </pre>
	 */
	protected void sequence_ComparisonOperator(ISerializationContext context, Gt semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ComparisonOperator returns Le
	 *
	 * Constraint:
	 *     {Le}
	 * </pre>
	 */
	protected void sequence_ComparisonOperator(ISerializationContext context, Le semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ComparisonOperator returns Lt
	 *
	 * Constraint:
	 *     {Lt}
	 * </pre>
	 */
	protected void sequence_ComparisonOperator(ISerializationContext context, Lt semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ComparisonOperator returns Ne
	 *
	 * Constraint:
	 *     {Ne}
	 * </pre>
	 */
	protected void sequence_ComparisonOperator(ISerializationContext context, Ne semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     EnumSpecification returns EnumerationLiteral
	 *
	 * Constraint:
	 *     name=EnumQualifiedName
	 * </pre>
	 */
	protected void sequence_EnumSpecification(ISerializationContext context, EnumerationLiteral semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DactPackage.Literals.NAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DactPackage.Literals.NAMED_ELEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEnumSpecificationAccess().getNameEnumQualifiedNameParserRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Identifier returns Identifier
	 *
	 * Constraint:
	 *     (name=QualifiedName index=SignedInt?)
	 * </pre>
	 */
	protected void sequence_Identifier(ISerializationContext context, Identifier semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     InOperator returns In
	 *
	 * Constraint:
	 *     {In}
	 * </pre>
	 */
	protected void sequence_InOperator(ISerializationContext context, In semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     IntegerSpecification returns LiteralInteger
	 *
	 * Constraint:
	 *     value=EIntegerObject
	 * </pre>
	 */
	protected void sequence_IntegerSpecification(ISerializationContext context, LiteralInteger semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DactPackage.Literals.LITERAL_INTEGER__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DactPackage.Literals.LITERAL_INTEGER__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIntegerSpecificationAccess().getValueEIntegerObjectParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns UnaryExpression
	 *     AssignmentExpression returns UnaryExpression
	 *     OrExpression returns UnaryExpression
	 *     OrExpression.BinaryExpression_1_0 returns UnaryExpression
	 *     AndExpression returns UnaryExpression
	 *     AndExpression.BinaryExpression_1_0 returns UnaryExpression
	 *     ComparisonExpression returns UnaryExpression
	 *     ComparisonExpression.BinaryExpression_1_0 returns UnaryExpression
	 *     AdditiveExpression returns UnaryExpression
	 *     AdditiveExpression.BinaryExpression_1_0 returns UnaryExpression
	 *     InExpression returns UnaryExpression
	 *     InExpression.BinaryExpression_1_0 returns UnaryExpression
	 *     MultiplicativeExpression returns UnaryExpression
	 *     MultiplicativeExpression.BinaryExpression_1_0 returns UnaryExpression
	 *     UnaryExpression returns UnaryExpression
	 *     PrimaryExpression returns UnaryExpression
	 *
	 * Constraint:
	 *     (
	 *         value=RealSpecification | 
	 *         value=IntegerSpecification | 
	 *         value=StringSpecification | 
	 *         value=BooleanSpecification | 
	 *         value=NullSpecification | 
	 *         identifier=Identifier | 
	 *         value=EnumSpecification
	 *     )
	 * </pre>
	 */
	protected void sequence_LiteralBoolean_LiteralEnum_LiteralInteger_LiteralNull_LiteralReal_LiteralString_PropertyAccess(ISerializationContext context, UnaryExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LiteralBoolean returns UnaryExpression
	 *
	 * Constraint:
	 *     value=BooleanSpecification
	 * </pre>
	 */
	protected void sequence_LiteralBoolean(ISerializationContext context, UnaryExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DactPackage.Literals.UNARY_EXPRESSION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DactPackage.Literals.UNARY_EXPRESSION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLiteralBooleanAccess().getValueBooleanSpecificationParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LiteralEnum returns UnaryExpression
	 *
	 * Constraint:
	 *     value=EnumSpecification
	 * </pre>
	 */
	protected void sequence_LiteralEnum(ISerializationContext context, UnaryExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DactPackage.Literals.UNARY_EXPRESSION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DactPackage.Literals.UNARY_EXPRESSION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLiteralEnumAccess().getValueEnumSpecificationParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LiteralInteger returns UnaryExpression
	 *
	 * Constraint:
	 *     value=IntegerSpecification
	 * </pre>
	 */
	protected void sequence_LiteralInteger(ISerializationContext context, UnaryExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DactPackage.Literals.UNARY_EXPRESSION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DactPackage.Literals.UNARY_EXPRESSION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLiteralIntegerAccess().getValueIntegerSpecificationParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LiteralNull returns UnaryExpression
	 *
	 * Constraint:
	 *     value=NullSpecification
	 * </pre>
	 */
	protected void sequence_LiteralNull(ISerializationContext context, UnaryExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DactPackage.Literals.UNARY_EXPRESSION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DactPackage.Literals.UNARY_EXPRESSION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLiteralNullAccess().getValueNullSpecificationParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LiteralReal returns UnaryExpression
	 *
	 * Constraint:
	 *     value=RealSpecification
	 * </pre>
	 */
	protected void sequence_LiteralReal(ISerializationContext context, UnaryExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DactPackage.Literals.UNARY_EXPRESSION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DactPackage.Literals.UNARY_EXPRESSION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLiteralRealAccess().getValueRealSpecificationParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LiteralString returns UnaryExpression
	 *
	 * Constraint:
	 *     value=StringSpecification
	 * </pre>
	 */
	protected void sequence_LiteralString(ISerializationContext context, UnaryExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DactPackage.Literals.UNARY_EXPRESSION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DactPackage.Literals.UNARY_EXPRESSION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLiteralStringAccess().getValueStringSpecificationParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     MultiplicativeOperator returns Divide
	 *
	 * Constraint:
	 *     {Divide}
	 * </pre>
	 */
	protected void sequence_MultiplicativeOperator(ISerializationContext context, Divide semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     MultiplicativeOperator returns Times
	 *
	 * Constraint:
	 *     {Times}
	 * </pre>
	 */
	protected void sequence_MultiplicativeOperator(ISerializationContext context, Times semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     NullSpecification returns LiteralNull
	 *
	 * Constraint:
	 *     {LiteralNull}
	 * </pre>
	 */
	protected void sequence_NullSpecification(ISerializationContext context, LiteralNull semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     OrOperator returns Or
	 *
	 * Constraint:
	 *     {Or}
	 * </pre>
	 */
	protected void sequence_OrOperator(ISerializationContext context, Or semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PropertyAccess returns UnaryExpression
	 *
	 * Constraint:
	 *     identifier=Identifier
	 * </pre>
	 */
	protected void sequence_PropertyAccess(ISerializationContext context, UnaryExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DactPackage.Literals.UNARY_EXPRESSION__IDENTIFIER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DactPackage.Literals.UNARY_EXPRESSION__IDENTIFIER));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPropertyAccessAccess().getIdentifierIdentifierParserRuleCall_1_0(), semanticObject.getIdentifier());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     RealSpecification returns LiteralReal
	 *
	 * Constraint:
	 *     value=EDoubleObject
	 * </pre>
	 */
	protected void sequence_RealSpecification(ISerializationContext context, LiteralReal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DactPackage.Literals.LITERAL_REAL__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DactPackage.Literals.LITERAL_REAL__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRealSpecificationAccess().getValueEDoubleObjectParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     StringSpecification returns LiteralString
	 *
	 * Constraint:
	 *     value=STRING
	 * </pre>
	 */
	protected void sequence_StringSpecification(ISerializationContext context, LiteralString semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DactPackage.Literals.LITERAL_STRING__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DactPackage.Literals.LITERAL_STRING__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStringSpecificationAccess().getValueSTRINGTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns NotExpression
	 *     AssignmentExpression returns NotExpression
	 *     OrExpression returns NotExpression
	 *     OrExpression.BinaryExpression_1_0 returns NotExpression
	 *     AndExpression returns NotExpression
	 *     AndExpression.BinaryExpression_1_0 returns NotExpression
	 *     ComparisonExpression returns NotExpression
	 *     ComparisonExpression.BinaryExpression_1_0 returns NotExpression
	 *     AdditiveExpression returns NotExpression
	 *     AdditiveExpression.BinaryExpression_1_0 returns NotExpression
	 *     InExpression returns NotExpression
	 *     InExpression.BinaryExpression_1_0 returns NotExpression
	 *     MultiplicativeExpression returns NotExpression
	 *     MultiplicativeExpression.BinaryExpression_1_0 returns NotExpression
	 *     UnaryExpression returns NotExpression
	 *     PrimaryExpression returns NotExpression
	 *
	 * Constraint:
	 *     expr=PrimaryExpression
	 * </pre>
	 */
	protected void sequence_UnaryExpression(ISerializationContext context, NotExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, DactPackage.Literals.NOT_EXPRESSION__EXPR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, DactPackage.Literals.NOT_EXPRESSION__EXPR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUnaryExpressionAccess().getExprPrimaryExpressionParserRuleCall_0_2_0(), semanticObject.getExpr());
		feeder.finish();
	}
	
	
}
