/**
 */
package lemma.adapted.xcore.service.provider;

import java.util.ArrayList;
import java.util.Collection;

import lemma.adapted.xcore.service.util.ServiceAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ServiceItemProviderAdapterFactory extends ServiceAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ServiceItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.ServiceModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceModelItemProvider serviceModelItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.ServiceModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceModelAdapter() {
		if (serviceModelItemProvider == null) {
			serviceModelItemProvider = new ServiceModelItemProvider(this);
		}

		return serviceModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.Import} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportItemProvider importItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.Import}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportAdapter() {
		if (importItemProvider == null) {
			importItemProvider = new ImportItemProvider(this);
		}

		return importItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.MappedComplexType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MappedComplexTypeItemProvider mappedComplexTypeItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.MappedComplexType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMappedComplexTypeAdapter() {
		if (mappedComplexTypeItemProvider == null) {
			mappedComplexTypeItemProvider = new MappedComplexTypeItemProvider(this);
		}

		return mappedComplexTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.MappedDataOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MappedDataOperationItemProvider mappedDataOperationItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.MappedDataOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMappedDataOperationAdapter() {
		if (mappedDataOperationItemProvider == null) {
			mappedDataOperationItemProvider = new MappedDataOperationItemProvider(this);
		}

		return mappedDataOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.MappedDataOperationReturnType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MappedDataOperationReturnTypeItemProvider mappedDataOperationReturnTypeItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.MappedDataOperationReturnType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMappedDataOperationReturnTypeAdapter() {
		if (mappedDataOperationReturnTypeItemProvider == null) {
			mappedDataOperationReturnTypeItemProvider = new MappedDataOperationReturnTypeItemProvider(this);
		}

		return mappedDataOperationReturnTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.MappedDataOperationParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MappedDataOperationParameterItemProvider mappedDataOperationParameterItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.MappedDataOperationParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMappedDataOperationParameterAdapter() {
		if (mappedDataOperationParameterItemProvider == null) {
			mappedDataOperationParameterItemProvider = new MappedDataOperationParameterItemProvider(this);
		}

		return mappedDataOperationParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.MappedField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MappedFieldItemProvider mappedFieldItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.MappedField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMappedFieldAdapter() {
		if (mappedFieldItemProvider == null) {
			mappedFieldItemProvider = new MappedFieldItemProvider(this);
		}

		return mappedFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.Microservice} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MicroserviceItemProvider microserviceItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.Microservice}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMicroserviceAdapter() {
		if (microserviceItemProvider == null) {
			microserviceItemProvider = new MicroserviceItemProvider(this);
		}

		return microserviceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.TechnologyReference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologyReferenceItemProvider technologyReferenceItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.TechnologyReference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologyReferenceAdapter() {
		if (technologyReferenceItemProvider == null) {
			technologyReferenceItemProvider = new TechnologyReferenceItemProvider(this);
		}

		return technologyReferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.Interface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfaceItemProvider interfaceItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.Interface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfaceAdapter() {
		if (interfaceItemProvider == null) {
			interfaceItemProvider = new InterfaceItemProvider(this);
		}

		return interfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.Operation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationItemProvider operationItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.Operation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationAdapter() {
		if (operationItemProvider == null) {
			operationItemProvider = new OperationItemProvider(this);
		}

		return operationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.ApiOperationComment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ApiOperationCommentItemProvider apiOperationCommentItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.ApiOperationComment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createApiOperationCommentAdapter() {
		if (apiOperationCommentItemProvider == null) {
			apiOperationCommentItemProvider = new ApiOperationCommentItemProvider(this);
		}

		return apiOperationCommentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.ApiParameterComment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ApiParameterCommentItemProvider apiParameterCommentItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.ApiParameterComment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createApiParameterCommentAdapter() {
		if (apiParameterCommentItemProvider == null) {
			apiParameterCommentItemProvider = new ApiParameterCommentItemProvider(this);
		}

		return apiParameterCommentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.ReferredOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferredOperationItemProvider referredOperationItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.ReferredOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReferredOperationAdapter() {
		if (referredOperationItemProvider == null) {
			referredOperationItemProvider = new ReferredOperationItemProvider(this);
		}

		return referredOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.Parameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParameterItemProvider parameterItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.Parameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParameterAdapter() {
		if (parameterItemProvider == null) {
			parameterItemProvider = new ParameterItemProvider(this);
		}

		return parameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.PossiblyImportedMicroservice} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PossiblyImportedMicroserviceItemProvider possiblyImportedMicroserviceItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.PossiblyImportedMicroservice}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPossiblyImportedMicroserviceAdapter() {
		if (possiblyImportedMicroserviceItemProvider == null) {
			possiblyImportedMicroserviceItemProvider = new PossiblyImportedMicroserviceItemProvider(this);
		}

		return possiblyImportedMicroserviceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.PossiblyImportedInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PossiblyImportedInterfaceItemProvider possiblyImportedInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.PossiblyImportedInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPossiblyImportedInterfaceAdapter() {
		if (possiblyImportedInterfaceItemProvider == null) {
			possiblyImportedInterfaceItemProvider = new PossiblyImportedInterfaceItemProvider(this);
		}

		return possiblyImportedInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.PossiblyImportedOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PossiblyImportedOperationItemProvider possiblyImportedOperationItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.PossiblyImportedOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPossiblyImportedOperationAdapter() {
		if (possiblyImportedOperationItemProvider == null) {
			possiblyImportedOperationItemProvider = new PossiblyImportedOperationItemProvider(this);
		}

		return possiblyImportedOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.ImportedType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportedTypeItemProvider importedTypeItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.ImportedType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportedTypeAdapter() {
		if (importedTypeItemProvider == null) {
			importedTypeItemProvider = new ImportedTypeItemProvider(this);
		}

		return importedTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.ImportedProtocolAndDataFormat} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportedProtocolAndDataFormatItemProvider importedProtocolAndDataFormatItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.ImportedProtocolAndDataFormat}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportedProtocolAndDataFormatAdapter() {
		if (importedProtocolAndDataFormatItemProvider == null) {
			importedProtocolAndDataFormatItemProvider = new ImportedProtocolAndDataFormatItemProvider(this);
		}

		return importedProtocolAndDataFormatItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.ProtocolSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProtocolSpecificationItemProvider protocolSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.ProtocolSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProtocolSpecificationAdapter() {
		if (protocolSpecificationItemProvider == null) {
			protocolSpecificationItemProvider = new ProtocolSpecificationItemProvider(this);
		}

		return protocolSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.Endpoint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EndpointItemProvider endpointItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.Endpoint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEndpointAdapter() {
		if (endpointItemProvider == null) {
			endpointItemProvider = new EndpointItemProvider(this);
		}

		return endpointItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link lemma.adapted.xcore.service.ImportedServiceAspect} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportedServiceAspectItemProvider importedServiceAspectItemProvider;

	/**
	 * This creates an adapter for a {@link lemma.adapted.xcore.service.ImportedServiceAspect}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImportedServiceAspectAdapter() {
		if (importedServiceAspectItemProvider == null) {
			importedServiceAspectItemProvider = new ImportedServiceAspectItemProvider(this);
		}

		return importedServiceAspectItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (serviceModelItemProvider != null) serviceModelItemProvider.dispose();
		if (importItemProvider != null) importItemProvider.dispose();
		if (mappedComplexTypeItemProvider != null) mappedComplexTypeItemProvider.dispose();
		if (mappedDataOperationItemProvider != null) mappedDataOperationItemProvider.dispose();
		if (mappedDataOperationReturnTypeItemProvider != null) mappedDataOperationReturnTypeItemProvider.dispose();
		if (mappedDataOperationParameterItemProvider != null) mappedDataOperationParameterItemProvider.dispose();
		if (mappedFieldItemProvider != null) mappedFieldItemProvider.dispose();
		if (microserviceItemProvider != null) microserviceItemProvider.dispose();
		if (technologyReferenceItemProvider != null) technologyReferenceItemProvider.dispose();
		if (interfaceItemProvider != null) interfaceItemProvider.dispose();
		if (operationItemProvider != null) operationItemProvider.dispose();
		if (apiOperationCommentItemProvider != null) apiOperationCommentItemProvider.dispose();
		if (apiParameterCommentItemProvider != null) apiParameterCommentItemProvider.dispose();
		if (referredOperationItemProvider != null) referredOperationItemProvider.dispose();
		if (parameterItemProvider != null) parameterItemProvider.dispose();
		if (possiblyImportedMicroserviceItemProvider != null) possiblyImportedMicroserviceItemProvider.dispose();
		if (possiblyImportedInterfaceItemProvider != null) possiblyImportedInterfaceItemProvider.dispose();
		if (possiblyImportedOperationItemProvider != null) possiblyImportedOperationItemProvider.dispose();
		if (importedTypeItemProvider != null) importedTypeItemProvider.dispose();
		if (importedProtocolAndDataFormatItemProvider != null) importedProtocolAndDataFormatItemProvider.dispose();
		if (protocolSpecificationItemProvider != null) protocolSpecificationItemProvider.dispose();
		if (endpointItemProvider != null) endpointItemProvider.dispose();
		if (importedServiceAspectItemProvider != null) importedServiceAspectItemProvider.dispose();
	}

}
