/*
 * generated by Xtext 2.43.0
 */
package dact.dsl.ui.tests;

import com.google.inject.Injector;
import dact.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ExprDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("dact.dsl.ExprDsl");
	}

}
