/**
 *
 * $Id$
 */
package lemma.adapted.xcore.technology.validation;

import lemma.adapted.xcore.technology.CompatibilityDirection;
import lemma.adapted.xcore.technology.PossiblyImportedTechnologySpecificType;
import lemma.adapted.xcore.technology.Technology;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.technology.CompatibilityMatrixEntry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CompatibilityMatrixEntryValidator {
	boolean validate();

	boolean validateDirection(CompatibilityDirection value);
	boolean validateMappingType(PossiblyImportedTechnologySpecificType value);
	boolean validateCompatibleTypes(EList<PossiblyImportedTechnologySpecificType> value);
	boolean validateTechnology(Technology value);
}
