/**
 *
 * $Id$
 */
package lemma.adapted.xcore.technology.validation;

import lemma.adapted.xcore.technology.OperationAspectPointcutSelector;
import lemma.adapted.xcore.technology.PointcutType;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.technology.OperationAspectPointcut}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperationAspectPointcutValidator {
	boolean validate();

	boolean validateForTechnology(boolean value);
	boolean validateTechnology(EObject value);
	boolean validateSelector(OperationAspectPointcutSelector value);
	boolean validateEffectiveType(PointcutType value);
	boolean validateEffectiveSelectorName(String value);
	boolean validateEffectiveValue(String value);
	boolean validatePrintableEffectiveValue(String value);
	boolean validateOrderedPointcutTypes(EList<PointcutType> value);
}
