/**
 *
 * $Id$
 */
package lemma.adapted.xcore.technology.validation;

import lemma.adapted.xcore.technology.OperationTechnology;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.technology.OperationEnvironment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperationEnvironmentValidator {
	boolean validate();

	boolean validateEnvironmentName(String value);
	boolean validateDefault(boolean value);
	boolean validateOperationTechnology(OperationTechnology value);
}
