/**
 *
 * $Id$
 */
package lemma.adapted.xcore.technology.validation;

import lemma.adapted.xcore.technology.CommunicationType;
import lemma.adapted.xcore.technology.DataFormat;
import lemma.adapted.xcore.technology.ExchangePattern;
import lemma.adapted.xcore.technology.PointcutType;
import lemma.adapted.xcore.technology.Protocol;
import lemma.adapted.xcore.technology.ServiceAspectPointcutSelector;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.technology.ServiceAspectPointcut}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServiceAspectPointcutValidator {
	boolean validate();

	boolean validateForExchangePattern(boolean value);
	boolean validateForCommunicationType(boolean value);
	boolean validateForProtocol(boolean value);
	boolean validateForDataFormat(boolean value);
	boolean validateExchangePattern(ExchangePattern value);
	boolean validateCommunicationType(CommunicationType value);
	boolean validateProtocol(Protocol value);
	boolean validateDataFormat(DataFormat value);
	boolean validateSelector(ServiceAspectPointcutSelector value);
	boolean validateEffectiveType(PointcutType value);
	boolean validateEffectiveSelectorName(String value);
	boolean validateEffectiveValue(String value);
	boolean validatePrintableEffectiveValue(String value);
	boolean validateOrderedPointcutTypes(EList<PointcutType> value);
}
