/**
 *
 * $Id$
 */
package lemma.adapted.xcore.technology.validation;

import lemma.adapted.xcore.data.PrimitiveType;
import lemma.adapted.xcore.data.PrimitiveValue;

import lemma.adapted.xcore.technology.OperationTechnology;
import lemma.adapted.xcore.technology.PropertyFeature;
import lemma.adapted.xcore.technology.TechnologyAspect;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.technology.TechnologySpecificProperty}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TechnologySpecificPropertyValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateType(PrimitiveType value);
	boolean validateDefaultValue(PrimitiveValue value);
	boolean validateFeatures(EList<PropertyFeature> value);
	boolean validateOperationTechnology(OperationTechnology value);
	boolean validateTechnologyAspect(TechnologyAspect value);
	boolean validateIsMandatory(boolean value);
}
