/**
 *
 * $Id$
 */
package lemma.adapted.xcore.technology.validation;

import lemma.adapted.xcore.technology.AspectFeature;
import lemma.adapted.xcore.technology.JoinPointType;
import lemma.adapted.xcore.technology.TechnologySpecificProperty;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lemma.adapted.xcore.technology.TechnologyAspect}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TechnologyAspectValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateFeatures(EList<AspectFeature> value);
	boolean validateJoinPoints(EList<JoinPointType> value);
	boolean validateProperties(EList<TechnologySpecificProperty> value);
	boolean validateIsSingleValued(boolean value);
}
