/**
 *
 * $Id$
 */
package dact.validation;

import dact.ActivityGroup;
import dact.DomainNode;
import dact.DomainNodeOperationMapping;
import dact.Parameter;
import dact.ParameterMapping;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dact.Activity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityValidator {
	boolean validate();

	boolean validateToTransform(Boolean value);
	boolean validateOwnedParameters(EList<Parameter> value);
	boolean validateParameterMappings(EList<ParameterMapping> value);
	boolean validateRoot(ActivityGroup value);
	boolean validateOwnedDomainNodes(EList<DomainNode> value);
	boolean validateProcessedDomainNodeMappings(EList<DomainNodeOperationMapping> value);
}
