/**
 *
 * $Id$
 */
package dact.validation;

import dact.Activity;
import dact.ActivityEdge;
import dact.ActivityNode;
import dact.ConditionalNode;
import dact.ParallelNode;
import dact.Scope;
import dact.StructuredActivityNode;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;

/**
 * A sample validator interface for {@link dact.ActivityGroup}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityGroupValidator {
	boolean validate();

	boolean validateOwnedNodes(EList<ActivityNode> value);
	boolean validateOwnedEdges(EList<ActivityEdge> value);
	boolean validateScope(Scope value);
	boolean validateActivity(Activity value);
	boolean validateStructuredActivityNode(StructuredActivityNode value);
	boolean validateConditionalNode(ConditionalNode value);
	boolean validateParallelNode(ParallelNode value);

	boolean validateParent(EObject value);
}
