/**
 *
 * $Id$
 */
package dact.validation;

import dact.AggregateRoot;
import dact.Entity;
import dact.Expression;
import dact.Identifier;
import dact.Property;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dact.DomainNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DomainNodeValidator {
	boolean validate();

	boolean validateAggregate(AggregateRoot value);
	boolean validateResult(Identifier value);
	boolean validateEntity(Entity value);
	boolean validateMainExpr(EList<Expression> value);
	boolean validatePropertyChain(EList<Property> value);
}
