/**
 *
 * $Id$
 */
package dact.validation;

import dact.DomainObject;
import dact.InstanceProperty;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dact.InstanceValue}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InstanceValueValidator {
	boolean validate();

	boolean validateIsInstanceOf(DomainObject value);
	boolean validateOwnedProperties(EList<InstanceProperty> value);
}
