/**
 *
 * $Id$
 */
package dact.validation;

import dact.Property;
import dact.ValueSpecification;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dact.InstanceProperty}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InstancePropertyValidator {
	boolean validate();

	boolean validateIsInstanceOf(Property value);
	boolean validateValue(EList<ValueSpecification> value);
}
