/**
 *
 * $Id$
 */
package dact.validation;

import dact.Activity;
import dact.Operation;
import dact.ParameterDirection;
import dact.ParameterRole;

/**
 * A sample validator interface for {@link dact.Parameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParameterValidator {
	boolean validate();

	boolean validateDirection(ParameterDirection value);
	boolean validateRole(ParameterRole value);
	boolean validateOperation(Operation value);
	boolean validateActivity(Activity value);
}
