/**
 *
 * $Id$
 */
package dact.validation;

import dact.Activity;
import dact.CallOperationAction;
import dact.Identifier;
import dact.Parameter;
import dact.ParameterMappingType;
import dact.ValueSpecification;
import dact.Variable;

/**
 * A sample validator interface for {@link dact.ParameterMapping}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParameterMappingValidator {
	boolean validate();

	boolean validateType(ParameterMappingType value);
	boolean validateOperationParameter(Parameter value);
	boolean validateIdentifier(Identifier value);
	boolean validateVariable(Variable value);
	boolean validateActivityParameter(Parameter value);
	boolean validateValue(ValueSpecification value);
	boolean validateAction(CallOperationAction value);
	boolean validateActivity(Activity value);
}
