/**
 *
 * $Id$
 */
package dact.validation;

import dact.DomainEvent;
import dact.Identifier;
import dact.ValueSpecification;
import dact.Variable;

/**
 * A sample validator interface for {@link dact.SignalAction}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SignalActionValidator {
	boolean validate();

	boolean validateEvent(DomainEvent value);
	boolean validateVariable(Variable value);
	boolean validateIdentifier(Identifier value);
	boolean validateValue(ValueSpecification value);
}
