/**
 *
 * $Id$
 */
package dact.validation;

import dact.Expression;
import dact.SpecRule;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dact.SpecOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SpecOperationValidator {
	boolean validate();

	boolean validateIsInvariant(Boolean value);
	boolean validateOwnedRules(EList<SpecRule> value);

	boolean validateRules(EList<SpecRule> value);

	boolean validateRawString(String value);
	boolean validateValidatesSpecExpr(EList<Expression> value);
}
