/**
 *
 * $Id$
 */
package dact.validation;

import dact.Scope;
import dact.Type;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dact.Variable}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VariableValidator {
	boolean validate();

	boolean validateType(Type value);
	boolean validateUpperBound(Integer value);
	boolean validateLowerBound(Integer value);
	boolean validateAccessibleScopes(EList<Scope> value);
	boolean validateScope(Scope value);
}
